### ISSUE TITLE
[Feature] optimization guide?

### ISSUE THREAD

**Issue by rrrevin** [HDInnovations/UNIT3D-Community-Edition#1000]
Does anyone have a sizing guide or performance optimization guide for HIGH traffic sites?
Settings for networking (tcp/udp options?), database, indexes, disk, iptable rules, preferred web server, webserver options settings, etc..

I know of a few sites running unit3d (> 2.0) that are having SERIOUS performance issues with this software. Countless timeouts, both on the web and track side.

**Comment by HDVinnie** [comment]
Theres some tutorials here. But it is different per server per site. There is no tuning that fits all sites needs.

https://discord.gg/DNnZpz

**Comment by innocente205** [comment]
@rrrevin Like to swap notes? I'm on discord. tryingmybest#9961
