### ISSUE TITLE
No query results for model [App\Models\UserActivation].

### ISSUE THREAD

**Issue by NemoSciri** [HDInnovations/UNIT3D-Community-Edition#1009]
This is a fresh install. The activation email goes out, I can get it, however, when I click the link it shows:

Error 404: Page Not Found
No query results for model [App\Models\UserActivation].

However, it seems it does activate the account.

How can I fix this so that it shows the user that the account was activated and they can now login or redirects them to login or something?

What could cause this issue?

**Comment by NemoSciri** [comment]
Actually, just checked and it seems the accounts are being created already activated somehow, maybe this is why the email link doesnt work?

**Comment by HDVinnie** [comment]
You mean the default owner account and two system accounts that are created during installer process? If so there is no activation email that's sent during installer. There is a test email that is attempted to be sent to make sure your email configs work.

**Comment by NemoSciri** [comment]
No. If I enable registration and create a new user account, it gets the email for verification, but it can login immediately and the link goes the the above 404 error.

You can test this yourself at https://www.nemosciri.org

If you create an account, you will see what I mean. You can use a mailnesia.com email address so that you don't have to use your own.

Please take a look.

**Comment by NemoSciri** [comment]
I have just done a signup to show you.

Username: nstest123
Password: nstest123
Email Inbox: http://mailnesia.com/mailbox/nstest123

I have not clicked the activation link. The account can still login however. And when you open that inbox and click the activation link, it throws the error.

**Comment by HDVinnie** [comment]
I just signed up and cannot login as I haven't activated my account yet via email link.

[![Screen-Shot-2019-12-09-at-9-04-42-AM.png](https://i.postimg.cc/G2HnDf2b/Screen-Shot-2019-12-09-at-9-04-42-AM.png)](https://postimg.cc/sQdLdw7L)

After activating I can now login.

[![Screen-Shot-2019-12-09-at-9-06-56-AM.png](https://i.postimg.cc/mkKLhsyx/Screen-Shot-2019-12-09-at-9-06-56-AM.png)](https://postimg.cc/7JM8QjRX)

**Comment by NemoSciri** [comment]
Interesting. I will try from a different device and test this again.

**Comment by NemoSciri** [comment]
Reproduced again on Android Google Chrome. Also on Ubuntu Google Chrome. Both times using different internet connections (4g on phone, wifi on pc). Both times I used mailnesia.com email addresses. Which browser and OS is this that it is working on?

**Comment by NemoSciri** [comment]
![Screenshot from 2019-12-09 15-52-44](https://user-images.githubusercontent.com/58690995/70446050-d80a5e80-1a9c-11ea-9244-a15e3cadb804.png)
![Screenshot from 2019-12-09 15-53-20](https://user-images.githubusercontent.com/58690995/70446051-d8a2f500-1a9c-11ea-92c4-bf5b4f14dbad.png)
![Screenshot from 2019-12-09 15-53-39](https://user-images.githubusercontent.com/58690995/70446052-d8a2f500-1a9c-11ea-91cf-6fb45d29abcc.png)
![Screenshot from 2019-12-09 15-54-05](https://user-images.githubusercontent.com/58690995/70446053-d8a2f500-1a9c-11ea-95c0-c5a659327adf.png)

**Comment by NemoSciri** [comment]
Also on Firefox Ubuntu this happens. Just tested it there.

**Comment by NemoSciri** [comment]
The user is showing as already in the "User" group instead of the Validating group...

**Comment by HDVinnie** [comment]
Not sure. I just tested on your site fine. OS and Browser wouldn't matter. Also working fine on demo and multiple other UNIT3D powered sites. Are you using password reset or mass validate users tool? As that's only other way accounts can be validated and thus will get the 404 because the link is no longer valid.

**Comment by NemoSciri** [comment]
Just tested a few things. It is the email address that causes the issue.

It works fine on an other email but with mailnesia.com addresses, it bypasses the verification somehow. This is a security issue and should be fixed. Please test using a mailnesia.com address and you will then see it.

**Comment by HDVinnie** [comment]
Well dude look at the first line for the email provider you're using.

http://mailnesia.com

Disposable email at its best. Whenever you need to register on a site and you don’t want to give out your primary email address, use any @mailnesia.com address instead. `Email verification links are visited automatically in the background to validate the account instantly!`

**Comment by NemoSciri** [comment]
OMG. Now I feel so stupid. Thank you. I will close this now...

**Comment by HDVinnie** [comment]
This is why there is also a email whitelist/blacklist in UNIT3D you can use.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/config/email-white-blacklist.php
