### ISSUE TITLE
[Bug] Newly Created Pages Not Showing In List

### ISSUE THREAD

**Issue by NemoSciri** [HDInnovations/UNIT3D-Community-Edition#1010]
**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**
1. Go to /dashboard/pages
2. Click on Add a new page
3. Fill in title and page content
4. Click Add Page
5. Go back to /dashboard/pages
6. Doesn't show in list

**Expected behavior**
Expected it to show in list with edit and delete buttons like the pre-made pages.

**Notes**
Page can be edited by changing the number in the URL on another edit page up until you find it. For example the first created page can still be edited by going directly to: /dashboard/pages/7/edit but there is no link or listing in the dashboard for it.

Also suggested, a checkbox to add it to the links and which category in links to add it, so that for example you can check the box "Add to footer links?" and choose from a dropdown "Pages" or "Info".

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser: Chrome

**Additional context**
Deleted all cache and cookies and ran a clear all cache on server. No fix.

**Possible Fix?**
No idea. Hoping you can tell me.

**Comment by HDVinnie** [comment]
This is indeed a bug I can replicate. I will have a fix pushed tonight. It will be part of the next v2.7.0 release.

Also @NemoSciri if you haven't already join our discord.
https://discord.gg/cu4GR2

**Comment by NemoSciri** [comment]
I will look into Discord. I haven't used it before. Maybe it isn't popular in my country. However, I did go ahead and sponsor you since you and your script are so much help in getting my private torrent tracker up and running. I will also send you on bitcoin something later. ;-)

Thank you.

**Comment by HDVinnie** [comment]
Thank you for your sponsorship. UNIT3D is still under a lot of development making it better and better. Hope you enjoy it. And the Discord is a nice play to chat in realtime. Ask questions about the code and get support.

**Comment by NemoSciri** [comment]
I have added but I must wait 5 minutes before I can post a high there?

Also, yes. I like that it is under development. Gives me the opportunity to find bugs like this one, as well as offer suggestions to make it better for future users and myself. And also it being under development means the developers like yourself are active and can respond to questions, commends, concerns, recommendations, request, etc. where as a finished project goes abandoned quite quickly and noone cares anymore you just use it or you don't.

**Comment by HDVinnie** [comment]
👍 Look forward to seeing your bug reports, questions, commends, concerns, recommendations, request, etc.

PS: The 5 min validation on discord is just to help against spammers.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.3.0
