### ISSUE TITLE
 [Enhancement] Autoload of Disposable / Temporary Emails

### ISSUE THREAD

**Issue by NemoSciri** [HDInnovations/UNIT3D-Community-Edition#1011]
**Is your feature request related to a problem? Please describe.**
Currently, you must add a list of email domains to ban manually. However, I am suggesting that we add a feature to auto-pull them from one of the GitHub projects that have a list that is maintained.

**Describe the enhancement you'd like**
In the file /config/email-white-blacklist.php , adding a feature that is true or false for "auto-blacklist" and a blacklist URL such as "https://raw.githubusercontent.com/martenson/disposable-email-domains/master/disposable_email_blocklist.conf" that is maintained regularly.

**Describe alternatives you've considered**
The only other way is to copy that list into gedit and then use replace to replace all /n with /n/t' and then replace /n with ',/n and correct the first and last entry then copy and paste into the blacklist array in the file.

**Additional context**
I think this would be extremely useful to many who don't want temp emails a lot of which seem to automatically click the activation link without even verifying the email.

**Comment by HDVinnie** [comment]
Good idea. Ill look into auto fetching from that repo.

**Comment by NemoSciri** [comment]
Thanks. Think it will help out anyone who wants to avoid the embarrassment of my earlier bug report that turned out to be them auto-activating the account and also those who want to avoid fake accounts during open reg-season. 

Also, I would caution that you should note the first entry for some reason has a "*." in front of domain. Maybe filter that before loading the list. I'm assuming that domain has many subs that are also used but that wildcard may cause issues in your scripts. I'd prefer maybe either exclude that one, or filter for "*." before loading the list so it loads the main domain. My testing shows that with just the main domain, subdomains also get blocked.

**Comment by HDVinnie** [comment]
This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.
