### ISSUE TITLE
[Bug] Cards view not working

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#1015]
**Describe the bug**
Clicking 'Cards' in the torrents page produces an error

**To Reproduce**
1. Go to 'Torrents..'
2. Click on 'Cards...'
3. Serves Error 500. In laravel log produces "prod.ERROR: Creating default object from empty value"

**Expected behavior**
Cards view should be served.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.6
- Laravel Version: 6.04
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7
- Web Server Driver & Version: nginx
- OS Driver and Version: ubuntu 

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**
Full error text:
`[2019-12-14 00:19:23] prod.ERROR: Creating default object from empty value {"exception":"[object] (ErrorException(code: 0): Creating default object from empty value at /var/www/html/app/Console/Commands/AutoHighspeedTag.php:54)
[stacktrace]
#0 /var/www/html/app/Console/Commands/AutoHighspeedTag.php(54): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError(2, 'Creating defaul...', '/var/www/html/a...', 54, Array)
#1 [internal function]: App\\Console\\Commands\\AutoHighspeedTag->handle()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(522): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): value(Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(591): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(202): Illuminate\\Container\\Container->call(Array)
#8 /var/www/html/vendor/symfony/console/Command/Command.php(255): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(189): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#10 /var/www/html/vendor/symfony/console/Application.php(915): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#11 /var/www/html/vendor/symfony/console/Application.php(272): Symfony\\Component\\Console\\Application->doRunCommand(Object(App\\Console\\Commands\\AutoHighspeedTag), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#12 /var/www/html/vendor/symfony/console/Application.php(148): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(90): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(131): Illuminate\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#15 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#16 {main}
"}
`

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Provided error has nothing to do with torrent cards view. Provide proper error.

**Comment by innocente205** [comment]
Sorry, that's the error that appeared when I clicked on the cards button, so I assumed cause and effect. Where would I find the 'proper error' please?

**Comment by HDVinnie** [comment]
In the log viewer or log file itself.

**Comment by innocente205** [comment]
Ok, thanks. That's the only error in the log file for today. Maybe I was jumping to the wrong conclusion. The cards are working now. Found it! php ran out of memory. Apologies.
