### ISSUE TITLE
[Feature] Invite only system

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1019]
**Is your feature request related to a problem? Please describe.**
Most private trakers have an invite only system in place 
**Describe the solution you'd like**
A system like this would be a great feature with the option for admins to enable or disable this 
https://laraveldaily.com/laravel-auth-make-registration-invitation-only/

**Describe alternatives you've considered**
https://laraveldaily.com/laravel-auth-make-registration-invitation-only/
**Additional context**

**Comment by HDVinnie** [comment]
There is already an Application System.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/e561385de4d64ddff6ceccaef19fbff3684ef294/config/other.php#L178

If that is set to `true` then users can apply to get into the site at https://unit3d.org/application

Of course Application signup will not work even if set to true if https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/e561385de4d64ddff6ceccaef19fbff3684ef294/config/other.php#L125 invite-only is set to false aka open registration.
