### ISSUE TITLE
[Enhancement] external torrent support

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1020]
**Is your feature request related to a problem? Please describe.**
Currently if I add an external torrent - I have to download it before it will seed for a new website adding lots of torrents will take forever and most would become out of date very quickly 
**Describe the enhancement you'd like**
to be able to add external torrents that keep their trackers and add our site trackers to the seeds
**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
External torrents system like in xbtit is for allowing Public Torrents. UNIT3D-Community-Edition is a private tracker software and a external torrents system we will NOT be adding.
