### ISSUE TITLE
[Enhancement] A subscription page

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1021]
**Is your feature request related to a problem? Please describe.**
Adding a subscription page for users to donate per month week etc 
**Describe the enhancement you'd like**
after a users makes a payment for a week month etc they will receive upload credits to their account, maybe a new badge VIP status as seen on other private trackers like iptorrents etc 
**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
There is already a paid donations plugin. One is not planned to be baked into core at this time.

https://discord.gg/ntnPxzG
