### ISSUE TITLE
[Enhancement] Page editor for admins

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1022]
**Is your feature request related to a problem? Please describe.**
There is no way of editing pages currently unless you manually edit the files
**Describe the enhancement you'd like**
A better method of adding or editing pages in the admin panel 
**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
Could you be more clear in your issues? Pages.....what pages?

There is the pages system already. https://unit3d.org/dashboard/pages

If you are asking too be able to edit every page in the codebase then you of course need to edit the code....

**Comment by nomadtechiemike** [comment]
Sorry I mean a way of editing the pages directly from the admin area, make it easier to add content or update information, rather than have to edit each page via code - a build in page editor

**Comment by HDVinnie** [comment]
As explained on Discord this already exist.
