### ISSUE TITLE
[Bug] Not create new forum

### ISSUE THREAD

**Issue by MyAlien** [HDInnovations/UNIT3D-Community-Edition#1023]
Hello,
Since the new version
since the update to the last version, I get an error 500 when I create a new forum or even see this by default.
It's the same on the demo site.

Thank you for your support.

`prod     Error     21:55:34     
Missing required parameters for [Route: users.show] [URI: users/{username}]. (View: /var/www/html/resources/views/forum/index.blade.php) {"userId":4,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Missing required parameters for [Route: users.show] [URI: users/{username}]. (View: /var/www/html/resources/views/forum/index.blade.php) at /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:17)`

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7
- Laravel Version:6.7.0
- PHP Version:7.4

Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. `v2.3.0`
