### ISSUE TITLE
[Feature] 2FA authentication

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1024]
**Is your feature request related to a problem? Please describe.**
looking through the code there seems to be a 2 factor authentication script but I cannot see how I can enable it?
**Describe the solution you'd like**
A two factor authentication to make the site more secure 
**Describe alternatives you've considered**
https://www.5balloons.info/two-factor-authentication-google2fa-laravel-5/

or 

https://medium.com/@ryanlebel/add-two-factor-authentication-to-your-laravel-5-application-in-6-steps-ba1a7bc0f404
**Additional context**

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/e561385de4d64ddff6ceccaef19fbff3684ef294/config/auth.php#L119

After turned on you can enabled in your account settings.
