### ISSUE TITLE
[Enhancement] Add Delete Buttons in Pm Outbox

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#1027]
**Is your feature request related to a problem? Please describe.**
Deleting private messages from the outbox is rather long winded. 

**Describe the enhancement you'd like**
Delete buttons on the outbox listing in the same way as on the inbox. When deleted, return to the outbox (not the inbox, as is the case when deleting individual messages from the message display)

**Describe alternatives you've considered**
None. The only option at the moment is open each message and delete from the message display.

**Additional context**

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/1029
