### ISSUE TITLE
[Enhancement] Replies from the outbox go to the originator, not the current user.

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#1028]
**Is your feature request related to a problem? Please describe.**
Messages 'replied to' from the outbox are addressed to the current user, so come straight back into the inbox. Would be better to go to the recipient of the original message. 

**Describe the enhancement you'd like**
Private messages 'replied to' from the outbox should go to the other recipients, not the current user.

**Describe alternatives you've considered**
None

**Additional context**

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/1029
