### ISSUE TITLE
[Bug] Error while trying to upload a torrent.

### ISSUE THREAD

**Issue by DON-IDE** [HDInnovations/UNIT3D-Community-Edition#1030]
**Describe the bug**
A user was trying to upload something (Damn know what he was typing...) and he got 500 error.
I asked him to upload to demo just to be sure that it was the same there.
The laravel log is this:
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF4i-uch...' for column 'nfo' at row 1 (SQL: insert into `torrents` (`name`, `slug`, `description`, `mediainfo`, `info_hash`, `file_name`, `num_file`, `announce`, `size`, `nfo`, `category_id`, `user_id`, `imdb`, `tvdb`, `tmdb`, `mal`, `igdb`, `type`, `anon`, `stream`, `sd`, `internal`, `moderated_at`, `moderated_by`, `updated_at`, `created_at`) values (Samurai Rebellion AKA Joi-uchi Hairyo tsuma shimatsu 1967 1080p WEB-DL DD+2.0 H 264-SbR, samurai-rebellion-aka-joi-uchi-hairyo-tsuma-shimatsu-1967-1080p-web-dl-dd20-h-264-sbr, [center]

**To Reproduce**

**Expected behavior**
Upload the torrent or explain to user what the error was.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
NFO file your trying to upload is no good.
