### ISSUE TITLE
[Feature]Sorting items in playlists

### ISSUE THREAD

**Issue by roormonger** [HDInnovations/UNIT3D-Community-Edition#1041]
A feature that lets you sort the items in a playlist by release date, tm/imdb rating, title, resolution, etc. Or just custom ordering.

**Comment by xR4E** [comment]
Just to add to it, sorting it kind of works. I created playlists and they sort fine until you add 17 items, in two playlists the order was broken from the 17th torrent onwards. If you remove it, it's sorted correctly again
