### ISSUE TITLE
[Enhancement] Replace WysiBB with CKEditor 5

### ISSUE THREAD

**Issue by nomadtechiemike** [HDInnovations/UNIT3D-Community-Edition#1042]
**Is your feature request related to a problem? Please describe.**
Writting content as a web developer in BBcode is a pain - being able to create pages using html code is uch easier.
**Describe the enhancement you'd like**
change the current BB code editor WysiBB to CKEditor 4 or 5
**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
Not going to change it out. 

1) BBCODE is a standard in the torrent community for descriptions.
2) You can use HTML in page creation. Example: `<h1>TESTING</h1>`
