### ISSUE TITLE
"Who is online?" not displaying the right users[Bug]

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D-Community-Edition#1043]
The bottom of the front page shows the people who are online. We noticed it sometimes doesn't show all the persons that are online, because the user shows online in the chatbox, but not on the bottom of the site.

**Comment by HDVinnie** [comment]
```
        // Online Block
        $users = User::with('group', 'privacy')
            ->withCount([
                'warnings' => function (Builder $query) {
                    $query->whereNotNull('torrent')->where('active', '1');
                },
            ])
            ->where('last_action', '>', now()->subMinutes(5))
            ->get();
```

Its not broken. Chat user count is based of users in chat whether idle or active. The online block shows users active within the last 5min. Active meaning they have made a action.
