### ISSUE TITLE
[Enhancement] API Allow searching for filename inside torrent

### ISSUE THREAD

**Issue by PyR8zdl** [HDInnovations/UNIT3D-Community-Edition#1066]
**Is your feature request related to a problem? Please describe.**
I'd like to use the API to automate certain tasks such as uploading new and old releases without the worry of uploading dupes.

Since the torrent title can differ from the release name, and multiple releases can be attatched to the same tmdb_id this can cause an issue when uploading new torrents unattended programmatically.

**Describe the enhancement you'd like**
I see the filenames for each file within a .torrent file is already stored in DB. I suggest the API take advantage of that and allow searching for filenames in torrent files.

So a search for ```Bless.the.Harts.S01E10.Tying.the.Not.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb.mkv``` Would return the following potential results...

```Bless.the.Harts.S01.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb```
```Bless.the.Harts.S01E10.Tying.the.Not.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb```

This would be a foolproof way to automate uploads without the possibility of uploading dupes.
This would also allow a staff member to purge single episodes after a pack has been uploaded.
And for users this would allow the ability to automate cross seeding.

I suggest adding a new parameter such as ```file_in_torrent``` so regular searches don't query the files DB and vice-versa.

It might also be a good idea to make the filename search case-insensitive.

**Describe alternatives you've considered**
The only other alternative is to use the regular search and hope the torrent title matches the real release name. But this wouldn't be good for an untended script.

**Additional context**
I could show you an example of this feature on another trackers api if needed.

**Comment by HDVinnie** [comment]
Added
