### ISSUE TITLE
[Bug] PM popup from user profile does not accept CRs

### ISSUE THREAD

**Issue by kevin201** [HDInnovations/UNIT3D-Community-Edition#1067]
**Describe the bug**
When you press 'Enter' in a pm from the profile page, nothing registers. The message must be sent in one long continuous line.

**To Reproduce**
1. Go to a profile page
2. Click on the blue envelope.
3. Type something, hit 'Enter', nothing happens.

**Expected behavior**
A carriage return should be input, and shown on the output.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by innocente205** [comment]
Fixed in #1285
