### ISSUE TITLE
[Bug] $history->client_downloaded = $real_uploaded;

### ISSUE THREAD

**Issue by OlafvdSpek** [HDInnovations/UNIT3D-Community-Edition#1074]
```
$history->client_downloaded = $real_uploaded;
```

This looks suspicious. ;)

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Http/Controllers/AnnounceController.php

**Comment by HDVinnie** [comment]
@OlafvdSpek thank you for pointing this out! It has now been fixed. 

PS: One day hope to add XBT support. Great job on that.

**Comment by HDVinnie** [comment]
@OlafvdSpek I'm trying to find a way to get in touch with you. Are you on discord or could email me at unit3d@protonmail.com ?
