### ISSUE TITLE
[Bug] Chat issues and ideas

### ISSUE THREAD

**Issue by DON-IDE** [HDInnovations/UNIT3D-Community-Edition#1080]
**Describe the bug**
Chat has alot of issues. I decided to put all of them together. Hope it is ok..

1) Group Chat. When you have 2 or more private conversations if you are active on USER1 conversation and USER3 send a message you will see the messages in the active window. Check the image:
http://imgbox.com/Gwegs7OX

2) Nerdbot posts topics from staff only forum and everyone can see the topic title (Not the message inside)

3) When a user sends a PM on chat and you refresh the page the chat thinks that you saw the message and turns from green to red so you don't know you have a new message if you refresh the page.

4) Can't delete chat rooms you create

5) Ability to edit your own messages
It would be nice to be able also to edit your messages and not only delete.

6) Maybe display/have some emoji you for fast use.
It would be much easier/faster/user friendly to have some emoji already displayed in Chat and not have to search or type for them.

Thank you very much for all your work and your time to fix all those issues.

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
One issue per issue.

You have 4 bugs and 2 enhancements in one issue. Open one for each as I have stated many times.

You also failed to fill out the template complete.
```
UNIT3D (please complete the following information):

UNIT3D Version:
Laravel Version:
PHP Version:
Database Driver & Version:
Web Server Driver & Version:
OS Driver and Version:


Desktop (please complete the following information):

OS:
Browser:
Version:
```
