### ISSUE TITLE
[Enhancement]

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1082]
At the moment there is no way to delete a torrent once it is uploaded. If an error is made and the torrent needs to be removed, it cannot be done. I am referring to situations where you are unable to get in to the "details" page to delete

A "DELETE" function to be available on both the  the browse page and, delete options within the staff panel.

**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
Sure it can. Open your eyes and you shall see.

![](https://i.imgur.com/TN7fStX.png)

**Comment by torman365** [comment]
yes I know but, if you cannot get into the details page, you cannot delete it

**Comment by torman365** [comment]
There was an instance when we loaded the TMDB number but when we uploaded to site, the torrent was there but we  could not get in to the details page at all and therefore, not able to delete a useless torrent. We get 
 Trying to get property 'title' of non-object (View: /var/www/html/resources/views/torrent/partials/movie_tv_meta.blade.php

this applies to all TMDB number entries not just one so, if we get locked out of details page, how do we get rid of the torrent?

**Comment by HVRVKVT** [comment]
@torman365 

1. Try using the direct link to edit  `https://example.com/torrents/TorrentNumber/edit`
2. Then set the ids to 0 and submit
3. Delete it.

**Comment by torman365** [comment]
yes that works
