### ISSUE TITLE
[Enhancement] Force Update Users PID

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1096]
At present  you cannot change the PID on members account unless you are the actual member. We need to be able to do this as Staff/Admin.

I would request that changing PID be an option available to Staff/Admin in both members CP and in Staff panel

**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
In future add proper title to your issues after the default prefix.
