### ISSUE TITLE
[Enhancement]  Add Mass Deletion Of Torrents

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1100]
Deleting dead or old torrents following repack has to be done one by one at the moment.

Enhancement I would like, the ability search for and to mass delete torrents.

**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by masterfo78** [comment]
push

**Comment by HDVinnie** [comment]
> push

What are you pushing?
