### ISSUE TITLE
[Bug]Seedbox Duplicate IP

### ISSUE THREAD

**Issue by masterfo78** [HDInnovations/UNIT3D-Community-Edition#1108]
**Describe the bug**
Hello why can't you enter the same ip. We have users who share a seedbox and you can only enter one user.

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
There is not need to have duplicate IP records. It is only needed once to set high speed tags on torrents. If its a shared IP then anyone using that box will get high speed tag on torrents there seeding regardless if it was them that registered the IP or not. This is not a bug and is intentional.
