### ISSUE TITLE
[Enhancement] I.P Tracking

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1109]
The ability to keep track of members I.P is an essential part of a torrent site so that dupe accounts and multiple users on same I.P can be checked to avoid cheats or malicious intrusion. It is also helpful  searching for members by I.P address.

Could you please introduce I.P tracking in Staff panel

**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
We will not be adding IP logging.....thats one thing UNIT3D strives about. Storing as little personal info as needed and encrypting what we do. I know many will not want this.

**Comment by torman365** [comment]
IP Logging is an integral part of site security and is used by the majority of established torrent sites. It has nothing to do with storing personal info but more to prevent the abuse of the site.

**Comment by HDVinnie** [comment]
> IP Logging is an integral part of site security and is used by the majority of established torrent sites. It has nothing to do with storing personal info but more to prevent the abuse of the site.

1000% disagree.

**Comment by HDVinnie** [comment]
You do realize that IP Logging is 99% `inefficient` right? You mean to tell me you think its worth logging users IP addresses to catch the few that are to stupid to use a VPN?

**Comment by torman365** [comment]
So you allow no way of checking for dupe accounts? If there is another method it would be good to know. I understand VPN can complicate that but it also argues against the "storing personal info" suggestion. Sites with a quarter of a million peers are open to abuse where smaller sites are not but, you have decided so will leave it at that.

**Comment by HDVinnie** [comment]
Duplicate to https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1151
