### ISSUE TITLE
[Enhancement] I.P Tracking

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1110]
The ability to keep track of members I.P is an essential part of a torrent site so that dupe accounts and multiple users on same I.P can be checked to avoid cheats or malicious intrusion. It is also helpful searching for members by I.P address.

Could you please introduce I.P tracking in Staff panel

**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
Duplicate
