### ISSUE TITLE
Disc space almost 100gb

### ISSUE THREAD

**Issue by vuurvogel** [HDInnovations/UNIT3D-Community-Edition#1112]
Is it normal with the auto installer
It takes almost 100Gb webspace
and this is a clean instal (not in use yet)
https://gyazo.com/6ce4df5dc38e94378b38535a7cbf8233

**Comment by HDVinnie** [comment]
Not at all. Fresh install with Ubuntu 18.04 / PHP / NGINX / MySQL / UNIT3D and other required dependencies comes to about `4-5GB`.

**Comment by vuurvogel** [comment]
Then i dont know where it is coming from its a fresh instal,
you are always welcom to take a look.

**Comment by HDVinnie** [comment]
Well maybe your server was not formatted properly. I can assure you its not UNIT3D.

**Comment by vuurvogel** [comment]
Okay i will take it up with the hoster they have set me up on a new server
Thanks for the reply

**Comment by PyR8zdl** [comment]
Run ``df -h`` in your terminal. What's the output?
