### ISSUE TITLE
[Enhancement] Use user_id for pool checking instead of IPs

### ISSUE THREAD

**Issue by HVRVKVT** [HDInnovations/UNIT3D-Community-Edition#1114]
Using PIDs instead of [ip_checking](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/fe4576ddda8a5d4781d47bfb487dbd5252919223/app/Http/Controllers/PollController.php#L95) to prevent voting more than once, is not only preferable, but also a more robust solution. While one could easily change IP, who would want to reset their PID just to vote once more?

**Comment by HDVinnie** [comment]
This needs to be removed all together. Instead just check user_id. The poll system needs to be refactored. It is old and was built like this because early UNIT3D supported both usage for a private or public tracker.

**Comment by HVRVKVT** [comment]
even better :thumbsup:
