### ISSUE TITLE
[Backup]

### ISSUE THREAD

**Issue by vuurvogel** [HDInnovations/UNIT3D-Community-Edition#1116]
**auto installer needs pasword**
Pasword have been set

If i go to dasboard make full backup then download it to my home pc

It not takes my pasword
I must fill it in for my own first time
and then it ask pasword for UNIT3D also set

But he say pasword is wrong??

**Comment by HDVinnie** [comment]
By default the ZIP password is your APP_KEY.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/dbd5566b66edf91348fd90765199b7321a06d074/config/backup.php#L235
