### ISSUE TITLE
[Feature] IP logging for peers and web

### ISSUE THREAD

**Issue by gyakkun** [HDInnovations/UNIT3D-Community-Edition#1151]
**Is your feature request related to a problem? Please describe.**
There's currently no active IP logging ~~despite seedbox registration(passively enable by user)~~. 

For private use of a tracker (ought to understand why some sites **have to** keep private), staff values the **subsistence** of the site and the **personal safety** of user's/staff's offline identity, **OVER** some privacy issues or efficiency of server code.

That's why cheating is **absolutely** not permitted in private trackers, since it features one's morality and therefore is related to the safety/security of the site. AFAIK, private trackers in my country form an alliance to impose penalty on cheating. Once they ascertain a user‘s cheating behavior in one site then all sites of the alliance would ban this user cascadingly.

For peers, there are some clients which may later be figured out that can be used to cheat. Nevertheless, some sites impose even stricter rules on seedbox requiring their user must not use an IP-sharing box. Here peer IP logging can be used for cheat check and rule compliance audit, as running quantity of bandwidth via VPN is not an economical choice (at least not, judging from my country's status quo).

For web, one can easily judge by IP logs that whether two or more accounts actually belong to a same user, which is also considered as a **severe** cheating behavior. 

Considering code efficiency, the IP-logging sites mentioned above are mostly running forks of [*nexusphp*](https://github.com/ZJUT/NexusPHP), a rather "primitive" tracker server written in php. There was no profound framework in the era when codebase of nexusphp became practically stable enough to use, which gave the reason that almost all queries were directly written in the routed page. You should understand after giving a glance at that code. But that also features a little higher "efficiency" for logging, though the burden for database should have no difference comparing with using framework like Laravel.

That's why I think IP logging should be optionally enable for private use. **It should really be considered as a feature of UNIT3D, as a promising next-gen tracker.**

**Describe the solution you'd like**
Make it configurable in staff dashboard. Create an independent table for logging.
Further implement cheat check logic judging by IP.

**Describe alternatives you've considered**
Set timeout for each log and make a periodical clear in queue workers.

**Additional context**
No additional context.

**Comment by gyakkun** [comment]
@HDVinnie Sorry for bothering you again on this topic, but I really need you final opinion, it will decide our dev plan.

**Comment by HDVinnie** [comment]
> @HDVinnie Sorry for bothering you again on this topic, but I really need you final opinion, it will decide our dev plan.

Please join the discord so we can discuss this. https://discord.gg/vJ5rJz
