### ISSUE TITLE
hit and run warning removal[Bug]

### ISSUE THREAD

**Issue by xplodexx** [HDInnovations/UNIT3D-Community-Edition#1170]
**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**
mine site max users got hit and run  warning i want to remove warning from them via artisan kindly help 

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
You failed to follow our Issue Template. If you have questions use our discord. https://discord.gg/YsSW4n
