### ISSUE TITLE
[Help] Users auto banned due to warning on ac 

### ISSUE THREAD

**Issue by xplodexx** [HDInnovations/UNIT3D-Community-Edition#1171]
**Describe the bug**
Due to warning on ac users got banned

**To Reproduce**
1. updated and updated hit & run by mistake
2. 480 users got banned on 21-02-2020

**UNIT3D (please complete the following information):**
- UNIT3D Version:v2.2.7
- Laravel Version: Ver. 6.16.0
- PHP Version: php7.4.1
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version:

**Additional context**
Kindly help me unban the users banned on 21-02-2020 n make them user 

**Possible Fix?**
tried many commands did not worked

**Comment by Nanda-to** [comment]
This is not a bug, so don't tag it as one. 

I told you what you have to do in Discord to unban everyone, but if they were not all a single member type then you'll have to fix them yourself.

This will remove everyone from the banned group to the default user group, you may need to double check the group_id's and created_at values depending on 1, when it happened and 2, what the ids are for the banned group and users group on your installation. Even though they should be the same as they are internal groups you shouldn't of messed with really.
```
UPDATE users, bans
SET users.group_id = '3'
WHERE users.group_id = '5'
AND bans.created_at LIKE '2020-02-22%'
```
and if you want to get rid of all the ban logs, you can run this. It doesn't matter if you do this or not as this will only show up in the staff dashboard in the ban logs section
`DELETE FROM bans WHERE created_at LIKE '2020-02-22%'`

**Comment by xplodexx** [comment]
but how to run it in my sql i got this https://gyazo.com/17ce8564f557bd60158e7fa2d4d0d51f

**Comment by xplodexx** [comment]
Failed to execute SQL : SQL SET users.group_id = '3' WHERE users.group_id = '5' AND bans.created_at LIKE '2020-02-22%' failed : Unknown system variable 'group_id'

**Comment by xplodexx** [comment]
https://gyazo.com/f931eea954d8169479b735db0212c9a8 here gets the error

**Comment by Golumpa** [comment]
You need to select the database first,

`use UNIT3D;`

Change UNIT3D to whatever the database is called your using.
