### ISSUE TITLE
[Bug] Adding incorrect TMDB code causes Error 500 on torrent page and on torrent category pages

### ISSUE THREAD

**Issue by staticza** [HDInnovations/UNIT3D-Community-Edition#1184]
**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**

1. Upload or edit an existing torrent.
2. Change TMDB ID to an invalid value.
3. Browse to torrent or browse to category page with that torrent on.
4. Observe error 500

**Expected behavior**
Either:
* page displays without movie/TV info
* OR Editing incorrect value not allowed.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: UNIT3D Community Edition (Nex-Gen Torrent Tracker) v2.2.7
- Laravel Version:Ver. 6.15.1
- PHP Version: php7.4.3
- Database Driver & Version: 10.4.12-MariaDB-1:10.4.12+maria~bionic-log
- Web Server Driver & Version: nginx
- OS Driver and Version: ubuntu 18.04

**Desktop (please complete the following information):**
 - OS: various
 - Browser: various
 - Version: various

**Additional context**

**Possible Fix?**

* Check for valid IMDB/TMDB values before accepting?
* Easy way to find invalud IMDB values.

**Comment by HDVinnie** [comment]
@staticza provide the error 500 in detail from logs.

**Comment by staticza** [comment]
Laravel Log:

```
Trying to get property 'title' of non-object (View: /var/www/html/unit3d/resources/views/torrent/partials/movie_tv_meta.blade.php) {"userId":3,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): Trying to get property 'title' of non-object (View: /var/www/html/unit3d/resources/views/torrent/partials/movie_tv_meta.blade.php) at /var/www/html/unit3d/resources/views/torrent/partials/movie_tv_meta.blade.php:14)
--
```

**Comment by HDVinnie** [comment]
@staticza its now fixed

**Comment by staticza** [comment]
Tested and it's working now.

**Comment by innocente205** [comment]
For info, as well as the cards and movie_tv_meta blades, this problem also exists in:

/var/www/html/app/Http/Controllers/TorrentController.php:924)
/var/www/html/resources/views/requests/request.blade.php:251)
/var/www/html/resources/views/torrent/similar.blade.php:46)
/var/www/html/resources/views/torrent/similar.blade.php:66)
/var/www/html/resources/views/torrent/similar.blade.php:71)
/var/www/html/resources/views/user/downloads.blade.php:79)
/var/www/html/resources/views/user/filters/history.blade.php:25)
/var/www/html/resources/views/user/private/active.blade.php:128)
/var/www/html/resources/views/user/private/downloads.blade.php:132)
/var/www/html/resources/views/user/private/torrents.blade.php:161)
