### ISSUE TITLE
[Bug] If you delete a room where users are active their chat is broken

### ISSUE THREAD

**Issue by staticza** [HDInnovations/UNIT3D-Community-Edition#1187]
**Describe the bug**
If you delete a room where a user is active their chat is effectively disabled.  Only blank chatbox is shown.

**To Reproduce**
1. Enter a room (such that on users table chatrooom_id=3 say)
2. Go to staff dashboard and delete room with same ID.
3. Go to home page and observe non-working chat.

**Expected behavior**
Chat should continue to work with user bumped to another room or room_id 1.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: UNIT3D Community Edition (Nex-Gen Torrent Tracker) v2.2.7
- Laravel Version:Ver. 6.15.1
- PHP Version: php7.4.3
- Database Driver & Version: 10.4.12-MariaDB-1:10.4.12+maria~bionic-log
- Web Server Driver & Version: nginx
- OS Driver and Version: ubuntu 18.04

**Desktop (please complete the following information):**
 - OS: ubuntu 19.10
 - Browser: Chrome
 - Version:

**Additional context**

**Possible Fix?**
I fixed it manually by updating the chat_room_id on the user table to 1 for the users that were set to the room that was deleted.

**Comment by cbj4074** [comment]
When we fix this, let's be sure not to hard-code the room ID to which affected users are sent. In other words, we should look-up the record by slug or name, as we've done more recently in other places.

**Comment by HDVinnie** [comment]
I believe we need to also add a `boolean` column to a lot of tables called `system_required`. So if true it cannot be deleted. Like the default `General` chatroom. So if staff make new rooms and then delete it any users in that room revert the the default system_required room.

**Comment by nikosuk** [comment]
i created a chatroom (i am owner account)
i shouted some linesin the room , then i deleted it.
when i go to home page, .. chat is empty .. and no controls at all

![Captureqqq](https://user-images.githubusercontent.com/57614897/80589293-92860800-8a22-11ea-884b-08917a89f5de.PNG)

**Comment by HDVinnie** [comment]
As you can see @nikosuk this is still a open known bug.
