### ISSUE TITLE
[Bug] Don't install in /var/www/html

### ISSUE THREAD

**Issue by OlafvdSpek** [HDInnovations/UNIT3D-Community-Edition#1189]
`/var/www/html` appears to be the default install directory. This is kinda dangerous, as this directory is served by web servers by default. The nginx conf is updated accordingly, but if for whatever reason a web server is running with the stock conf, database credentials and other files are exposed..

**Comment by HDVinnie** [comment]
I get what your saying but it is noted in the automated installer README right at the top, `"NOTE: This only works for a fresh server with nothing on it but a new OS install!"`.

If users install manually then that's on them to do it correctly. I don't see this being classified as a bug at all.
