### ISSUE TITLE
[Bug] User validating stays on

### ISSUE THREAD

**Issue by DXDHD** [HDInnovations/UNIT3D-Community-Edition#1190]
**Describe the bug**
A user remains unvalidated even after mass mavidation 

**To Reproduce**
1. It shows on my version of UNIT3D Admin panel

**Expected behavior**
Its expected to go away

**Screenshots**
https://malzo.com/i/2020/03/01/AZx.png

**UNIT3D (please complete the following information):**
- UNIT3D Version:  v2.2.7
- Laravel Version: 6.5.2
- PHP Version: 7.4
- Database Driver & Version: 5.7.29-0ubuntu0.18.04.1
- Web Server Driver & Version: nginx
- OS Driver and Version: Ubuntu 18.04.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 

**Additional context**
Its been there for last 2 versions. 

**Possible Fix?**
No

**Comment by shlandturtle** [comment]
Mass validation command checks only for users in validation group who are active = 0. Is this user perhaps active = 1?
