### ISSUE TITLE
[Bug] Side navigation bar no longer works as intended on Firefox

### ISSUE THREAD

**Issue by shlandturtle** [HDInnovations/UNIT3D-Community-Edition#1192]
**Describe the bug**
Side navigation bar is constantly open (and can't be collapsed) when using Firefox. This issue arrive during one of the last 62 commits.
On Chrome and Chrome-based browsers this problem does not exist.

**To Reproduce**
1. Go to site using Firefox
2. Side navigation is wide open
3. Go to site using Chrome or it's derivative
4. Side navigation works as before

**Expected behavior**
Side nav should collapse and work on FF too.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7 (on commit 95033bd100e5cfc7d64f2df0f6340671de091646)
- Laravel Version: 6.17.0
- PHP Version: 7.4.2
- Database Driver & Version: mysql 5.7.29
- Web Server Driver & Version: nginx  1.15.8
- OS Driver and Version: Ubuntu 18.04

**Desktop (please complete the following information):**
 - OS: All of them.
 - Browser: Firefox 73
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Not able to replicate on FireFox 72.0.2 (64-bit)

[![Image from Gyazo](https://i.gyazo.com/c6b0ec49a3e8af7759db96955db37ab7.gif)](https://gyazo.com/c6b0ec49a3e8af7759db96955db37ab7)

I can set side nav in settings just fine.
https://unit3d.site/users/UNIT3D/settings

**Comment by HDVinnie** [comment]
I have discovered the issue.

**Comment by HDVinnie** [comment]
It appears the PR by @werrpy https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/1188 uses lookbehinds aka `?<=` in regex. News to me as well but it appears look behinds are not supported in FF, Safari and others. 

For reference: 
https://bugzilla.mozilla.org/show_bug.cgi?id=1225665
https://caniuse.com/#feat=js-regexp-lookbehind

Have a solution @werrpy ? Otherwise will need to revert.

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/63b84ffa679b2d54bbf43f9951a4b7a150f8b686
