### ISSUE TITLE
[Bug] Newlines not possible in certain views of sending PM's

### ISSUE THREAD

**Issue by shlandturtle** [HDInnovations/UNIT3D-Community-Edition#1212]
**Describe the bug**
When sending PM from the button in users profile, the PM box does not accept any newlines. This causes awful looking PM's.
Additionally, when moderating torrents from the torrents page, the same problem exists. On the main moderation view / list newlines are possible, but only when postponing.

**To Reproduce**
1. Go to users profile
2. Click on send PM button
3. Newlines not possible, all text will be on single line
Alternatively:
1. Go to torrent moderation
2. Click on a torrent to go to it's page
2. Postpone or reject
3. Newlines not possible, all text sent will be on single line.

**Expected behavior**
While rest of the PM styling choices are not that important especially in moderation PM's, newlines should be supported regardless.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7
- Laravel Version: 6.17.0
- PHP Version: 7.4.2
- Database Driver & Version: mysql 5.7.29
- Web Server Driver & Version: nginx 1.15.8
- OS Driver and Version: Ubuntu 18.04

**Desktop (please complete the following information):**
 - OS:
 - Browser: Firefox 73, Chrome 80
 - Version:

**Additional context**

**Possible Fix?**
When clicking the PM icon on users profile, redirect to /mail/create with the username already entered in to the recipient field. This would allow using the same editor to send the message.
For moderation tasks, the reasoning box should support newlines for both buttons and both views.

**Comment by HDVinnie** [comment]
Duplicate #1067
