### ISSUE TITLE
[Feature]Allow only a specific group 

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#1252]
Allow only a specific group (supporters) 
to be able to download torrents from the site
<img width="960" alt="Download" src="https://user-images.githubusercontent.com/32823071/77678294-39ddce00-6f91-11ea-85f7-3713328b2912.png">
and no one else

**Comment by HDVinnie** [comment]
This sounds like a pay2leech feature which I will not add.
