### ISSUE TITLE
[Bug] Incorrect links to pages > 1 in forum post/topic searches

### ISSUE THREAD

**Issue by stonedbovines** [HDInnovations/UNIT3D-Community-Edition#1255]
**Describe the bug**

A forum post search that results in more than one page of results does not provide correct links to pages > 1

**To Reproduce**

Visit SITE/forums/search

Enter a search term that will result in multiple pages (eg the letter e!)

The first page of results is at SITE/forums/search?name=&body=e&category=&sorting=created_at&direction=desc

Check the links at the bottom to subsequent pages
Page 2, for example, shows as SITE/forums/search?name=&page=2

**Expected behavior**

Expect pages to provide the correct links
eg something like SITE/forums/search?name=&body=e&page=2&category=&sorting=created_at&direction=desc

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.7
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

User not admin, so not sure

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

This issue also shows up in forum topic searches.

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by Oha-you** [comment]
Note: issue is not reproduced in latest version (checked at https://unit3d.site)

Can be closed.

![2021-04-14_025430](https://user-images.githubusercontent.com/82098328/114635243-fbff3500-9ccc-11eb-9c91-1eb838637dbb.png)
