### ISSUE TITLE
[Feature] block user in chatbox

### ISSUE THREAD

**Issue by kdezmac** [HDInnovations/UNIT3D-Community-Edition#1260]
**Is your feature request related to a problem? Please describe.**
When someone is starts acting belligerently i'd like to be able to block them **permanently**. I don't want to see their messages or get sound alerts every time they talk

**Describe the solution you'd like**
_/block user_ to hide their messages

**Describe alternatives you've considered**
Reporting certain people, especially staff members, is ineffective. Private tracker staff are like cops; They vehemently protect each other regardless of context or whether or not they're right. This leads to a blatant disregard of the rules and creates an imbalance where regular users need to walk on eggshells while staff members can do as they please without consequences. This reflects poorly on the staff and the site as a whole. 

**Additional context**
ignoring users is one of the most basic features of a chat system

**Comment by stonedbovines** [comment]
I'd like to see this on forum posts as well.

One way to manage this, that doesn't require the database to keep track of it, is to 'class' each user-provided section of content with the username. For example, the chatbox has each entry wrapped inside a <li class="sent" ... ></li> construct. If that was to be extended to eg <li class="sent" class="stonedbovines" ... ></li> a user that wanted to not see my 'pithy comments' could just set local CSS to make .stonedbovines invisible. At any point that user-provided content is currently displayed, the username is already known.

**Comment by HDVinnie** [comment]
feel free to open a pull request @stonedbovines
