### ISSUE TITLE
[Feature] Possibility to turn OFF moderation

### ISSUE THREAD

**Issue by nightcomdev** [HDInnovations/UNIT3D-Community-Edition#1262]
**Is your feature request related to a problem? Please describe.**
Not all projects that this script is implemented have wide community. People who are registered on UNIT3D Platform can have possibility to upload torrents without moderation.

My problem: From nowhere even when I (owner) upload torrent I have to approve it and it's not working (approving), I have Error 500. Searching solution whole day and easier in my case turn off moderation on whole site (only trusted people here). Reject and Postpone working fine, just Approve not.

**Describe the solution you'd like**
Option in Back End: Turn Off moderation

**Describe alternatives you've considered**
Edit file to change from `true` to `false`

Short info about my env:
- automatic installation on ubuntu 16.04
- server behind reverse proxy (reverse proxy on Apache)
- UNIT3D on Nginx
- separate VM
- remoteip, x-forwarded-for mod_remoteip not configured on reverse proxy server and UNIT3D host

**Comment by HDVinnie** [comment]
It would help if you told us what the error 500 was.

**Comment by nightcomdev** [comment]
Error 500: Internal Server Error!
Our server encountered an internal error.
Sorry For The Inconvenience

That is the message when I press "Approve" on torrent, I can Reject it, Delete it ....but not Approve.

**Comment by Golumpa** [comment]
thats not the error, go to your staff dashboard, laravel logs, there you should find the detail error you get.

**Comment by nightcomdev** [comment]
Thank you @Golumpa 
`prod.ERROR: Trying to get property 'id' of non-object {"userId":3,"exception":"[object] (ErrorException(code: 0): Trying to get property 'id' of non-object at /var/www/html/app/Repositories/ChatRepository.php:341)`

in laravel logs I have only this error repeating over 60 times

**Comment by HDVinnie** [comment]
You need to change back the `system_required` bot name to SystemBot.

As for this Feature request. You can already simply just make all groups `Trusted` in group settings so they bypass moderation.

**Comment by nightcomdev** [comment]
but where to change it? You mean in GUI? or is it in `.env` ?

**Comment by HDVinnie** [comment]
change what?

**Comment by nightcomdev** [comment]
group I know that it can be done in GUI but where I can change `system_required` bot name because in GUI in section bots I see name SystemBot so it's not this one I guess

**Comment by HDVinnie** [comment]
Sorry I misread the error. It the chatroom. Im guessing you renamed the default room from General?

**Comment by HDVinnie** [comment]
Anyway if you change the default chatroom name for announces then you need to also set it in the config.

chat.php
 `'system_chatroom' => 'General',`

**Comment by nightcomdev** [comment]
you are my man!!!! I did changed name of chat room but I didn't know that it will affect whole torrent addon, anyway thank you!
