### ISSUE TITLE
[Feature] Implment hCaptcha

### ISSUE THREAD

**Issue by whitedragonn** [HDInnovations/UNIT3D-Community-Edition#1265]
**Is your feature request related to a problem? Please describe.**
I recall the reason why unit3d doesn't have recaptcha is due to recaptcha tracking a lot of user data, which you wouldn't want for a torrent tracker. hCaptcha is designed by cloudflare and is a lot more privacy driven.

**Describe the solution you'd like**
I'd like to see hCaptcha implemented https://www.hcaptcha.com/

**Describe alternatives you've considered**
reCaptcha, but it's bad.

**Additional context**
https://www.hcaptcha.com/

**Comment by HDVinnie** [comment]
UNIT3D already has its own hidden captcha.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Helpers/HiddenCaptcha.php
