### ISSUE TITLE
[Enhancement] Contribution Guidelines

### ISSUE THREAD

**Issue by Anan5a** [HDInnovations/UNIT3D-Community-Edition#1266]
**Is your feature request related to a problem? Please describe.**
Not a problem.
**Describe the enhancement you'd like**
I'd like to add/update some feature of this application. But there's no docs on how should I do it. I understand its a laravel based project. But the actual functional code is not same for every project. SO it will be helpful if there was a documentation.
Features I'd like to enhance/add:
Add custom option and logic to Bonus system
Enforce certain seed ratio
Change the title of user level

**Describe alternatives you've considered**
None
**Additional context**
Development

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/CONTRIBUTING.md

**Comment by Anan5a** [comment]
@HDVinnie I already read the COC. But the actual information about what file has what functionality is really hard to decipher

**Comment by HDVinnie** [comment]
Ok so I assume then you have not worked with Laravel before?

**Comment by Anan5a** [comment]
I've not worked with completed applications. And did not used all of the laravel features. So I'm fairly new in laravel ecosystem

**Comment by HDVinnie** [comment]
Ok well we don't have a guide going that deep. If you need to learn Laravel I suggest https://laracasts.com. Otherwise if you have questions about the code feel free to use our discord.
