### ISSUE TITLE
[Bug] Supervisor is unable to run laravel-echo-server

### ISSUE THREAD

**Issue by Anan5a** [HDInnovations/UNIT3D-Community-Edition#1272]
**Describe the bug**
Supervisor cannot run ```laravel-echo-server```
**To Reproduce**

**Expected behavior**
Everything should be running

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS: Ubuntu 18 LTS
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**

```
root@ubuntu-virt-test:/var/www/html/UNIT3D# supervisorctl
unit3d-queue:unit3d-queue_00           RUNNING   pid 6824, uptime 0:00:02
unit3d-queue:unit3d-queue_01           RUNNING   pid 6823, uptime 0:00:02
unit3d-socket-io:unit3d-socket-io_00   FATAL   Exited too quickly (process log may have details)
```
But if I run as root in the terminal that works

**Comment by HDVinnie** [comment]
Did you check the supervisor log?

`But if I run as root in the terminal that works`
If you run what? What command?

Are you using HTTPS? Letsencrypt? More info is needed.

**Comment by Anan5a** [comment]
Not using https
It's a local environment
Command is
```laravel-echo-server start```
And supervisor log gor that process has only one message ```unable to write lock file```       
I've checked permissions and everything is owned    by ```www-data```

**Comment by Anan5a** [comment]
@HDVinnie  any news?
