### ISSUE TITLE
[Bug]Subtitles

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#1273]
**Describe the bug**
subtitles load, but when you try to download them error 500

File not found at path: var/www/html/public/files/subtitles/5e940ddc79e2c.srt {"userId":3,"exception":"[object] (League\Flysystem\FileNotFoundException(code: 0): File not found at path: var/www/html/public/files/subtitles/5e940ddc79e2c.srt at /var/www/html/vendor/league/flysystem/src/Filesystem.php:389)

**To Reproduce**
try downloading a loaded subtitle

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.3.0
- Laravel Version: 6.18.3
- PHP Version: 7.4.4

**Comment by HDVinnie** [comment]
does `var/www/html/public/files/subtitles` exist?

**Comment by Gideon75** [comment]
/var/www/html/public/files/subtitles
yes 
and inside there are subtitles loaded

**Comment by HDVinnie** [comment]
`sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +`

Can you try running that to make sure perms are correct and trying again?

**Comment by Gideon75** [comment]
i did
error 500 if i try to download

File not found at path:  var/www/html/public/files/subtitles/5e9412c829113.srt  {"userId":3,"exception":"[object]  (League\\Flysystem\\FileNotFoundException(code: 0): File not found at  path: var/www/html/public/files/subtitles/5e9412c829113.srt at  /var/www/html/vendor/league/flysystem/src/Filesystem.php:389)

**Comment by Gideon75** [comment]
now it gives me error even if I try to eliminate it,  not before
