### ISSUE TITLE
[Enhancement] in the user profile see also the last used IP

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#1274]
**Is your feature request related to a problem? Please describe.**
When registrations are open, it would be useful to be able to compare the ip of new users with those who have been banned

**Describe the enhancement you'd like**
see the last used IPs in the users panel, even if they are not shared

**Comment by HDVinnie** [comment]
Duplicate to https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1151
