### ISSUE TITLE
Automatically chatbox has been flushed. How to disable it?

### ISSUE THREAD

**Issue by RememberForgottenHits** [HDInnovations/UNIT3D-Community-Edition#1280]
**Is your feature request related to a problem? Please describe.**
I have installed unit3d 7 times on a clean server and each time this automatic chatbox flushing occurs back.
The last fresh installation was done two days ago. Sometimes it clears the chat box after about 30 minutes, but sometimes it happens every several hours.
![FLUSH-potik](https://user-images.githubusercontent.com/34457020/79573046-acd8f100-80c6-11ea-8fe0-ad803b4e9c17.png)

**Describe the enhancement you'd like**
Is there any way to disable this system at all or it would be possible to make a history page where all the old text will be saved

**Describe alternatives you've considered**

**Additional context**
Laravel error log is also no information about it. 

My server conf is:
Ubuntu 18.04
Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz, 8 cores	
30GB ram

**Comment by HDVinnie** [comment]
This is not an enchantment. It it impossible for that function to be run and post that message to chatbox unless a user with a staff role is clicking flush chatbox from the staff dashboard. So ask them.

**Comment by RememberForgottenHits** [comment]
Thanks for answering but I am the sole owner and there is no more staff or admins privileges users. Fresh install and only 3 users. I don't click this button in the admin panel. Yesterday I just did a reinstall and after installing so about 5 minutes started again Chatbox flushing.
