### ISSUE TITLE
[Bug] Chat leaks Userdata

### ISSUE THREAD

**Issue by fionera** [HDInnovations/UNIT3D-Community-Edition#1290]
**Describe the bug**
When you join the Chat or a User interacts with it. Every User currently subscribed to that channel gets all Userdata. This includes all Torrents the user uploaded (even anonymous ones), seedboost, ratio etc. 

**To Reproduce**
1. Go to the Chat
2. Click open the Dev Tools
3. Open the Websocket Connection (and pray that your browser doesnt crash because of 28MB Frames)
4. ???
5. Profit

**Expected behavior**
Not leak all Userdata

**UNIT3D (please complete the following information):**
- UNIT3D Version:  -
- Laravel Version: -
- PHP Version: -
- Database Driver & Version: -
- Web Server Driver & Version: -
- OS Driver and Version: -

**Desktop (please complete the following information):**
 - OS: -
 - Browser: -
 - Version: -

**Additional context**

**Possible Fix?**

**Comment by HDVinnie** [comment]
Im not able to see torrents a user uploaded. Care to show how your seeing that. I can see the basic user info that's not considered personal info. The personal info is hidden via the models protected array.

```
    protected $hidden = [
        'email',
        'password',
        'passkey',
        'rsskey',
        'remember_token',
        'api_token',
    ];
```

**Comment by fionera** [comment]
Just go to your reference tracker, open the dev console and look into the websocket connection.
