### ISSUE TITLE
[Feature] Torrent custom Poster

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#1294]
**Is your feature request related to a problem? Please describe.**
in some torrent categories, meta system does not apply.
Like Software, Adult, etc

**Describe the solution you'd like**
It would be useful to introduce a field for custom poster image on some torrents' categories

**Describe alternatives you've considered**
I was thinking about an extra option, when you create or edit torrents' categories, where you could enable " Custom Poster "  if needed

**Additional context**
![1Capture](https://user-images.githubusercontent.com/57614897/80101377-fcf9fc80-8579-11ea-94d7-ba0e93edde9d.PNG)

**Comment by Gideon75** [comment]
I think many would like it, it's bad to have torrents without posters

**Comment by bigcaibao** [comment]
I think that's an important feature. @HDVinnie

**Comment by HDVinnie** [comment]
People are more then welcome to submit PRs
