### ISSUE TITLE
[Bug] Hover Poster Image

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#1297]
**Describe the bug**
When viewing torrent page, hovering over torrent posters does not work. Clicking on Poster, opens bigger picture.
while ...
When viewing torrent CATEGORY page, hovering over torrent posters DOES work . Clicking on Poster, does NOT..

**To Reproduce**
1. Go to 'https://domain/torrents.'
2. Click on 'torrent poster'
3. Hover over torrent poster
4. Go to 'https://domain/categories/ - select a category (eg movies)
5. Click on 'torrent poster'
6. Hover over torrent poster

**Expected behavior**
Should be able to click on poster (open bigger pic ) both in main torrents view as well as in torrent Category view.
Should be able to hover over poster (showoverlay small poster )both in main torrents view as well as in torrent Category view

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
This is not a bug....its one or the other and the hover will be removed for the SWAL click popup.
