### ISSUE TITLE
[Bug] Got syntax error when composer install

### ISSUE THREAD

**Issue by littlecxm** [HDInnovations/UNIT3D-Community-Edition#1312]
**Describe the bug**
Got syntax error when composer install at `AppServiceProvider.php`  line 78:

![image](https://user-images.githubusercontent.com/16154023/80306670-4a36d200-87f7-11ea-9f47-efba13857be9.png)

- UNIT3D Version: master
- Laravel Version: 6.x
- PHP Version: 7.3.15
- Composer Version : 1.10.5

**Comment by HDVinnie** [comment]
## <a name="versions"></a> 🚨 Version Support Information
 Version     | Status                   | PHP Version Required
:------------|:-------------------------|:------------
 2.3.x       |  Active Support :rocket: | >= 7.4
 2.0.0 to 2.2.7|  Active Support :rocket: | >= 7.3
 1.0 to 1.9.4|  End Of Life :skull:     | >= 7.1.3

update your php
