### ISSUE TITLE
[Bug] Errors in Log Files

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#1320]
**Describe the bug**
it is shown in Laravel Logs

**To Reproduce**
when i watched today's log i found the following errors repeated several times:

Trying to get property 'size' of non-object {"exception":"[object] (ErrorException(code: 0): Trying to get property 'size' of non-object at /var/www/html/app/Console/Commands/AutoPreWarning.php:60)

and also:
preg_match(): Unknown modifier '?' (View: /var/www/html/resources/views/page/page.blade.php) {"userId":13314,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): preg_match(): Unknown modifier '?' (View: /var/www/html/resources/views/page/page.blade.php) at /var/www/html/app/Helpers/Markdown.php:1208)

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.3.0
- Laravel Version: 6.18.10
- PHP Version: 7.4.5
- Database Driver & Version: 
- Web Server Driver & Version:
- OS Driver and Version:

**Comment by HDVinnie** [comment]
One bug per issue please. Re open separate issues if still facing problems.
