### ISSUE TITLE
Installation steps for Debian

### ISSUE THREAD

**Issue by karibuTW** [HDInnovations/UNIT3D-Community-Edition#1326]
Hello guys,
I've seen a great script for the installation for Ubuntu, but this will not work for Debian.
At the moment, we need to do it manually.

I've check the official documentation and wrote my own tutorial to install it on a fresh server.
I wanted to share all the steps I had to do:
https://freedif.org/unit3d-how-to-install-a-torrent-tracker

How this can help, if anyone is having issue to install it.

Thanks for this great project!

**Comment by HDVinnie** [comment]
@karibuTW thanks fr the guide. Ill add it to the documentation repo.
https://github.com/HDInnovations/UNIT3D-Docs

**Comment by karibuTW** [comment]
Super, thanks! Happy to contribute.

**Comment by mcangeli** [comment]
I hate to drag up an old subject, but is there any chance this doc is laying around anywhere??

**Comment by HDVinnie** [comment]
Going to go with no. We support Ubuntu and the Debian guide was done by a community member which appear gone and was extremely outdated anyway.
