### ISSUE TITLE
Any interest in creating/adding a Docker image?

### ISSUE THREAD

**Issue by denis-ev** [HDInnovations/UNIT3D-Community-Edition#1327]
no context needed

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/334

Also https://github.com/sysu-ipv6/UNIT3D-Deploy

Also I believe @leighmacdonald is making one. I do not use docker myself but am more then happy to link a official docker if one is made and maintained.

**Comment by leighmacdonald** [comment]
Correct, i have one in the works, though its super early. I'm only using it for development not deployment yet, it would need to be generalized for the larger audience before i make a PR.

There is also an ansible based docker-compose setup in the works from what i understand,  in addition to the deploy project linked.

**Comment by denis-ev** [comment]
That's good to know, thanks for the feedback.
