### ISSUE TITLE
[Bug] Pages cannot accept second video

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#1328]
**Describe the bug**
I am trying to insert 2 youtube videos in FAQ page but second one messes the page up.

**To Reproduce**
1. Go to staff panel - Pages
2. Edit a  page ( page 2 in my case), although does not work in any page
3. Try to enter 2 youtube videos, one after the other
4. Save page
5. See error

**Expected behavior**
Should be showing 2 youtube videos instead it shows this message : 

<iframe src="https://www.youtube-nocookie.com/embed/
hello again
[video="youtube"]arQ6ZEHXTBo?rel=0" width="640" height="480" frameborder="0" allow="autoplay; encrypted-media" allowfullscreen>

**Screenshots**
https://i.postimg.cc/pVwnvTBZ/1Capture.png

**UNIT3D (please complete the following information):**
- UNIT3D Version:  2.3.0

**Comment by dariusrz** [comment]
i have too same error.

**Comment by JamesPSS** [comment]
Hi

This is working in V5 
![56d7dff86da72a432b6a15b5150efbb6](https://user-images.githubusercontent.com/76886517/103529441-f7351480-4e85-11eb-9345-a85370168829.png)

**Comment by HDVinnie** [comment]
@JamesPSS strange. What markup are you using? As this error persist one demo site using the latest code in master.

**Comment by JamesPSS** [comment]
> @JamesPSS strange. What markup are you using? As this error persist one demo site using the latest code in master.

So i did some more testing. Test picture is where i use the iframe 

so like this
`<iframe width="560" height="315" src="https://www.youtube.com/embed/GlPlfCy1urI" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>`

But i can see on the demo site if you using the video button you will only get the first video and one time i got one video that was cut off. 

I can see that is more to it and i will check whats going on there. But for now you can use the iframe from youtube it will work
