### ISSUE TITLE
[Bug] Alternative to email invite

### ISSUE THREAD

**Issue by bolach** [HDInnovations/UNIT3D-Community-Edition#1335]
Hello
When is not possible to send the invite via mail, it is possible to share a link to signup with that?
After we create a invite, the system give us a code on invites page, so its possible to create a link with that code?

**Comment by HDVinnie** [comment]
This is not a BUG. Please follow our issue guidelines. 

UNIT3D requires one to have mail service for multiple functions/features of the codebase. 

As even if you do use the invite code to build the URL out manually whoever uses it will will to activate there account via a email....
