### ISSUE TITLE
[Enhancement] Lookup IMDb ID when using TMDB on upload page

### ISSUE THREAD

**Issue by d2dyno** [HDInnovations/UNIT3D-Community-Edition#1343]
**Is your feature request related to a problem? Please describe.**
If a user enters a TMDB ID for the upload page, IMDb doesn't auto populate. This leaves ratings empty, which is bad user experience.

**Describe the enhancement you'd like**
Use TMDB title for lookup on IMDb

**Comment by HDVinnie** [comment]
This will be resolved in the new Media Hub meta data system that is coming soon.

**Comment by HD4Free-Gizmo3D** [comment]
how about using the tmdb api eg:
Movie: 300: Rise of the Empire
https://api.themoviedb.org/3/movie/53182?api_key=xxxx
so in that we have the tmdb number 53182 for the movie, api key we all have
in the return there is "imdb_id":"tt1253863" returned, just need to trim left 2 chars and populate imdb field

just my 2 cents

**Comment by HDVinnie** [comment]
https://streamable.com/zy4wrk
