### ISSUE TITLE
[Bug] TV-Shows 'Rated: Unknown'

### ISSUE THREAD

**Issue by d2dyno** [HDInnovations/UNIT3D-Community-Edition#1344]
**Describe the bug**
No content rating is displayed on torrent page.

**To Reproduce**
1. Go to a tv-show torrent page.

**Expected behavior**
Should display content rating that TMDB provides.

**Screenshots**
![screenshot-blutopia xyz-2020 05 17-06_56_08](https://user-images.githubusercontent.com/2421939/82143712-9039f100-980b-11ea-9a3a-ed696a1dabdd.png)

**Comment by HDVinnie** [comment]
Thanks for opening an issue. This will be resolved in the new Media Hub meta data system that is coming soon.
