### ISSUE TITLE
[Enhancement] Make freeleech possible on upload page

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1353]
**Is your feature request related to a problem? Please describe.**

**Describe the enhancement you'd like**
Make it possible for the upload to be made free when making the upload rather than having to upload and then make it free
**Describe alternatives you've considered**

**Additional context**
At the moment there is no way to make a torrent free other than uploading it to the site first, this is something that needs to be implemented when making the upload.

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/1365
