### ISSUE TITLE
[Bug] Nginx Fail

### ISSUE THREAD

**Issue by AlucardSama04** [HDInnovations/UNIT3D-Community-Edition#1355]
**Describe the bug**
I'm trying to install UNIT3D via install.sh

**To Reproduce**
1. Go to 'installer'
2. Run `sudo ./install.sh`
3. Wait

**Expected behavior**
?

**Screenshots**
https://imgur.com/a/BYOjSCZ
**UNIT3D (please complete the following information):**
- UNIT3D Version: last
- Laravel Version: last
- PHP Version: last
- Database Driver & Version: last
- Web Server Driver & Version: last
- OS Driver and Version: last

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Version: last

**Additional context**

**Possible Fix?**
Nope

**Comment by HDVinnie** [comment]
@AlucardSama04 Im unable to replicate and this issue does not belong in this repository. Open it here. https://github.com/poppabear8883/UNIT3D-INSTALLER
