### ISSUE TITLE
[Enhancement] Reinstate the "Site Log" that was in a previous version

### ISSUE THREAD

**Issue by TheRover404** [HDInnovations/UNIT3D-Community-Edition#1363]
**Is your feature request related to a problem? Please describe.**
In a previous version of UNIT3D the Site Log was available under Staff Dashboard. This was extremely useful. After the last update it was replaced with the "Audit Log" (not useful). 

**Describe the enhancement you'd like**
Re-instate the Site Log as Staff often need to know who has performed actions on the site (e.g who had edited or deleted torrents, edited or deleted forum posts etc),

**Describe alternatives you've considered**
The audit log may contain this info but it is not easy to understand and does not show who has performed actions 
**Additional context**

**Comment by torman365** [comment]
This is something that is a requirement in order to check who has done what on the site. At the present time, the audit log gives very little info and no search capabilities.

**Comment by TheRover404** [comment]
Yet again, I've had to manually search through 81 pages of audit log to find the action I was looking for. In this case deleting a forum post. Previously I had to search through about 60 pages to find who had deleted a torrent. The audit log is not fit for purpose. Why is it limited to 50 entries?
Please bring back the Site Log and make it searchable.
