### ISSUE TITLE
[Bug] Reserved characters in filters (type, category)

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#1366]
**Describe the bug**
Including reserved characters (e.g. '/', '&', '|') in type or category name disables the 'filter on click' function in the torrent filters. 

**To Reproduce**
1. Change a category or type name to include one of '/', '&', or '|'.
2. Go to the torrents page and open the filters.
3. Click on the amended category or type.

Happens on current demo site.

**Comment by HDVinnie** [comment]
Simple fix. Ill short it tomorrow. Thanks for pointing it out.
