### ISSUE TITLE
 [Enhancement] Ability for staf to remove/edit shoutbox comments and gifs

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1367]
**Is your feature request related to a problem? Please describe.**
The shoutbox has no function for staff to be able to edit or remove unwanted comments or gifs etc , 
**Describe the enhancement you'd like**
Options for staff to edit or delete shoutbox comments 
**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
There is a delete option for staff.....click the `red` x by the users message.
