### ISSUE TITLE
[Enhancement] Remove the "Filled Requests cannot be deleted" rule

### ISSUE THREAD

**Issue by TheRover404** [HDInnovations/UNIT3D-Community-Edition#1370]
**Is your feature request related to a problem? Please describe.**
When deleting a request the prompt "Are you sure you want to delete this Request? This request can only be deleted if it has not been filled." is shown.
If it's been filled the request cannot be deleted by Admin.
**Describe the enhancement you'd like**
No-one apart from the OP cares about a filled request and the request list soon becomes very untidy with many filled requests.
When Admin come to clear up the list it's very time consuming to have to reset each and every filled request before deleting it (especially with the bug that crashes pages >1 in any forum list).
Admin should be able to remove any requests regardless of the request status.

**Describe alternatives you've considered**

**Additional context**

**Comment by HDVinnie** [comment]
> No-one apart from the OP cares about a filled request and the request list soon becomes very untidy with many filled requests.

I do not agree with this at all. There is NO reason to delete requests that are filled when there are search filters to view unfilled ones only. 

[![Screen-Shot-2020-06-01-at-8-50-26-PM.png](https://i.postimg.cc/kXrK6gk7/Screen-Shot-2020-06-01-at-8-50-26-PM.png)](https://postimg.cc/grDn1mz7)

Therefor this requested change is denied.
