### ISSUE TITLE
[Enhancement] Move language selection to footer

### ISSUE THREAD

**Issue by d2dyno** [HDInnovations/UNIT3D-Community-Edition#1383]
**Is your feature request related to a problem? Please describe.**
The flag being next to my profile link/photo doesn't look clean. Most, if not all users, will only change the language on site 1x, and leave it. I don't see the use of having this setting in the forefront taking up screen real estate.

**Describe the enhancement you'd like**
Move the language selector / flag dropdown, to footer, sidebar, or settings.

![screenshot-unit3d site-2020 06 08-19_31_22](https://user-images.githubusercontent.com/2421939/84093008-ac6e1f80-a9be-11ea-88c1-d40dcc3400b3.png)
![screenshot-unit3d site-2020 06 08-19_30_49](https://user-images.githubusercontent.com/2421939/84093010-ad06b600-a9be-11ea-86ff-1b46da53b828.png)

**Comment by HDVinnie** [comment]
Probably best in user settings. Ill do this tonight.
