### ISSUE TITLE
Consult

### ISSUE THREAD

**Issue by luckyWait** [HDInnovations/UNIT3D-Community-Edition#1400]
Hi, nice to meet you.

I have an off-topic consultation, **I really hope you don't mind.**

I want to start a torrent's website with a private tracker, I know how to program in some programming languages but I don't know how to develop websites, I can understand HTML and CSS to an acceptable level but that doesn't make me a web developer, I need to hire a real one, the problem is... I don't know how much the developer will charge me, I want to use open source projects to create the website, among them UNIT3D, **with that in mind would you know how much it will cost me to hire one?**

The content is a separate issue, I'm just interested in the developer designing the site based on a sketch I'm going to give him, get the tracker working and apply some security measures. Later on I will add the content myself.

Thanks.

**Comment by HDVinnie** [comment]
Use the discord server for questions like this. https://discord.gg/Bf47vws

PS: There is no number I can throw out there. All devs are different and it depends on EXACTLY what you want done. Beware of scammers though. Never pay someone up front.
