### ISSUE TITLE
[Bug] The Process class relies on proc_open, which is not available on your PHP installation.

### ISSUE THREAD

**Issue by Unit3dlover** [HDInnovations/UNIT3D-Community-Edition#1411]
**Describe the bug**
A clear and concise description of of what the bug is.
unable to update it shows The Process class relies on proc_open, which is not available on your PHP installation.
Argument 1 passed to Symfony\Component\Process\Process::__construct() must be of the type array, string given, called in /var/www/html/app/Console/ConsoleTools.php on line 109

  at vendor/symfony/process/Process.php:140
    136|      * @param int|float|null $timeout The timeout in seconds or null to disable
    137|      *
    138|      * @throws LogicException When proc_open is not installed
    139|      */
  > 140|     public function __construct(array $command, string $cwd = null, array $env = null, $input = null, ?float $timeout = 60)
    141|     {
    142|         if (!\function_exists('proc_open')) {
    143|             throw new LogicException('The Process class relies on proc_open, which is not available on your PHP installation.');
    144|         }

  1   app/Console/ConsoleTools.php:109
      Symfony\Component\Process\Process::__construct()

  2   app/Console/Commands/GitUpdater.php:187
      App\Console\Commands\GitUpdater::process()

**Expected behavior**
it should update with git updater

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:v2.6.0
- Laravel Version:Ver. 7.20.0
- PHP Version:7.4.6
- OS Driver and Version: ubuntu 20

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
This was fixed here. https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/c0d0050ea0e0ed268515c602e22d34ba7bfd7807

You will manually have to replace your `ConsoleTools.php` on your server with the new one.
