### ISSUE TITLE
[Feature]Personal rip button

### ISSUE THREAD

**Issue by nelsokege** [HDInnovations/UNIT3D-Community-Edition#1417]
It isn't always clear to the moderator whether an upload has been ripped by the uploader themselves or whether it was merely reuploaded. 

If an upload is unacceptable, a moderator may handle things differently if they know they're dealing with the releaser themselves. For example, they may wish to help them fix the release rather than outright rejecting it. Alternatively, they may wish to ask them to verify sources or the software they used. 

Users may also offer more appreciation when they are thanking/tipping the original releaser rather than a reuploader. When an internal or staff member uploads an external release, users have been known to assume that the release itself was internal.

It would be useful to have a button on the upload form with a title such as "Personal Rip", which would indicate this information to staff and - if the uploader doesn't wish to remain anonymous - to the rest of the userbase.

**Comment by HDVinnie** [comment]
Not a bad idea. Thanks.
