### ISSUE TITLE
Torrents not showing on torrent page after reinstall [Bug]

### ISSUE THREAD

**Issue by alphalinux2020** [HDInnovations/UNIT3D-Community-Edition#1422]
**Describe the bug**
files were restored in public folder and imported Sql
torrents are showing by links  but not in torrent page

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: v2.7.0
- Laravel Version:Ver. 7.22.1
- PHP Version:php7.4.3
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
yamraaj you can keep trying but telly will NOT be helped!
