### ISSUE TITLE
[Bug] Rules page gives 500 error

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#1429]
**Describe the bug**
As title says, Laravel log:
preg_match(): Unknown modifier '?' (View: /var/www/html/resources/views/page/page.blade.php) {"userId":4,"exception":"[object] (Facade\\Ignition\\Exceptions\\ViewException(code: 0): preg_match(): Unknown modifier '?' (View: /var/www/html/resources/views/page/page.blade.php) at /var/www/html/app/Helpers/Markdown.php:1208)

**To Reproduce**
1. Go to 'Side Nav.'
2. Click on 'Rules.'

**Expected behavior**
Rules Page to open

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.4
- Laravel Version: 6.18.3
- PHP Version: 7.4.5
- Database Driver & Version: 5.7.31 
- Web Server Driver & Version: nginx
- OS Driver and Version: Ubuntu 18.04

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by fmohican** [comment]
Fix:
`app\Helpers\Markdown.php` at line `1208`
replace `preg_match('#^&#?\w+;#', $Excerpt['text'])` with `preg_match('~#^&#?\w+;#~', $Excerpt['text'])`

**Comment by HDVinnie** [comment]
@fmohican feel free to open a pull request.

**Comment by fmohican** [comment]
Hello,
Sure, I will do it, but over the weekend because I'm out of town this week.
