### ISSUE TITLE
[Bug] $meta->plot is not setted

### ISSUE THREAD

**Issue by fmohican** [HDInnovations/UNIT3D-Community-Edition#1434]
**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**
1. Upload any torrent with category TV that doesn't have plot on tmdb/tvdb/omdb.
2. Make it feature
3. enjoy crash on front-page.

**Expected behavior**
Crash because $meta->plot doesn't exist.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 3.0.0
- Laravel Version: 7.0
- PHP Version: 7.4.9
- Database Driver & Version: MariaDB 10.5
- Web Server Driver & Version: nginX 1.14
- OS Driver and Version: Debian 10

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Edge (Chrome based)
 - Version:  85.0.564.44

**Additional context**
https://gist.github.com/fmohican/5b96fe8a91e6bff85a9fbc193e2d7e86

**Possible Fix?**
In file `resources\views\blocks\featured.blade.php` at line 94
replace
```
{{ Str::limit(strip_tags($meta->plot), 200) }}...
``` 
with 
``` 
{{ Str::limit((isset($meta->plot) ? $meta->plot : ""), 200) }}... 
```

There would be better fix, by checking every "member" of object before use it, probability i will comeback with reply with whole fix. But for a moment just checking with `isset()` seems fine.

**Comment by HDVinnie** [comment]
MediaHub v1.0 will be released into UNIT3D Community Edition once 75 sponsors goal is met! This issue will be closed when that is released.

https://www.youtube.com/watch?v=SE44mc8SRHA
