### ISSUE TITLE
[Bug] Editing Tags

### ISSUE THREAD

**Issue by fmohican** [HDInnovations/UNIT3D-Community-Edition#1437]
**Describe the bug**
Tags are uneditable.

**To Reproduce**
1. Go and create any tags
2. Try to edit that tag
3. 404 [ No query results for model [App\Models\Type] ]
**Expected behavior**
Return to tag that was edited or to tags list

**Screenshots**
-

**UNIT3D (please complete the following information):**
Check #1434 

**Desktop (please complete the following information):**
Check #1434 

**Additional context**
-

**Possible Fix?**
Replace:
`<form role="form" method="POST" action="{{ route('staff.types.update', ['id' => $tag->id]) }}">`
to
`<form role="form" method="POST" action="{{ route('staff.tags.update', ['id' => $tag->id]) }}">`

**Comment by HDVinnie** [comment]
MediaHub v1.0 will be released into UNIT3D Community Edition once 75 sponsors goal is met! This issue will be closed when that is released.

https://www.youtube.com/watch?v=SE44mc8SRHA

**Comment by fmohican** [comment]
Till that sponsors is reached, can submit pull request to fix that problem in current version?

**Comment by HDVinnie** [comment]
Of course. PR's are always welcome and this is an easy one.
