### ISSUE TITLE
Everything works only the buttom publish,that one does not work

### ISSUE THREAD

**Issue by vuurvogel** [HDInnovations/UNIT3D-Community-Edition#1439]
**_And i can not log out_**

[stacktrace]
#0 /var/www/html/vendor/predis/predis/src/Connection/StreamConnection.php(314): Predis\\Connection\\AbstractConnection->onConnectionError()
#1 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php(120): Predis\\Connection\\StreamConnection->read()
#2 /var/www/html/vendor/predis/predis/src/Connection/AbstractConnection.php(112): Predis\\Connection\\AbstractConnection->readResponse()
#3 /var/www/html/vendor/predis/predis/src/Client.php(331): Predis\\Connection\\AbstractConnection->executeCommand()
#4 /var/www/html/vendor/predis/predis/src/Client.php(314): Predis\\Client->executeCommand()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(220): Illuminate\\Redis\\Connections\\Connection->command()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(54): Illuminate\\Redis\\Connections\\Connection->__call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(563): Illuminate\\Cache\\Repository->get()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(552): Illuminate\\Queue\\Worker->getTimestampOfLastQueueRestart()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(240): Illuminate\\Queue\\Worker->queueShouldRestart()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(144): Illuminate\\Queue\\Worker->stopIfNecessary()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(112): Illuminate\\Queue\\Worker->daemon()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(96): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#15 [internal function]: Illuminate\\Queue\\Console\\WorkCommand->handle()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#22 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#24 /var/www/html/vendor/symfony/console/Application.php(916): Illuminate\\Console\\Command->run()
#25 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#26 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#29 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#30 {main}

[stacktrace]
#0 /var/www/html/app/Helpers/Helpers.php(43): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleError()
#1 /var/www/html/app/Console/Commands/AutoNerdStat.php(125): href_torrent()
#2 [internal function]: App\\Console\\Commands\\AutoNerdStat->handle()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): call_user_func_array()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(37): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(95): Illuminate\\Container\\Util::unwrapIfClosure()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(39): Illuminate\\Container\\BoundMethod::callBoundMethod()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(596): Illuminate\\Container\\BoundMethod::call()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(134): Illuminate\\Container\\Container->call()
#9 /var/www/html/vendor/symfony/console/Command/Command.php(258): Illuminate\\Console\\Command->execute()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#11 /var/www/html/vendor/symfony/console/Application.php(916): Illuminate\\Console\\Command->run()
#12 /var/www/html/vendor/symfony/console/Application.php(264): Symfony\\Component\\Console\\Application->doRunCommand()
#13 /var/www/html/vendor/symfony/console/Application.php(140): Symfony\\Component\\Console\\Application->doRun()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(93): Symfony\\Component\\Console\\Application->run()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#16 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#17 {main}
"}

[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/helpers.php(433): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(84): tap()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(61): Illuminate\\Encryption\\EncryptionServiceProvider->key()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/EncryptionServiceProvider.php(33): Illuminate\\Encryption\\EncryptionServiceProvider->parseKey()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Encryption\\EncryptionServiceProvider->Illuminate\\Encryption\\{closure}()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\\Foundation\\Application->make()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(201): Illuminate\\Container\\Container->offsetGet()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(188): Illuminate\\Session\\SessionManager->buildEncryptedSession()
#12 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionManager.php(139): Illuminate\\Session\\SessionManager->buildSession()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(115): Illuminate\\Session\\SessionManager->createRedisDriver()
#14 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Manager.php(90): Illuminate\\Support\\Manager->createDriver()
#15 /var/www/html/vendor/laravel/framework/src/Illuminate/Session/SessionServiceProvider.php(52): Illuminate\\Support\\Manager->driver()
#16 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Session\\SessionServiceProvider->Illuminate\\Session\\{closure}()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#19 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#20 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\\Foundation\\Application->make()
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(118): Illuminate\\Container\\Container->offsetGet()
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}()
#24 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#28 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(1284): Illuminate\\Foundation\\Application->make()
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/RoutingServiceProvider.php(168): Illuminate\\Container\\Container->offsetGet()
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(805): Illuminate\\Routing\\RoutingServiceProvider->Illuminate\\Routing\\{closure}()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(691): Illuminate\\Container\\Container->build()
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(796): Illuminate\\Container\\Container->resolve()
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(637): Illuminate\\Foundation\\Application->resolve()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(781): Illuminate\\Container\\Container->make()
#35 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(119): Illuminate\\Foundation\\Application->make()
#36 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/helpers.php(747): app()
#37 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(405): response()
#38 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(313): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()
#39 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(210): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()
#40 /var/www/html/app/Exceptions/Handler.php(73): Illuminate\\Foundation\\Exceptions\\Handler->render()
#41 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(415): App\\Exceptions\\Handler->render()
#42 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(113): Illuminate\\Foundation\\Http\\Kernel->renderException()
#43 /var/www/html/public/index.php(53): Illuminate\\Foundation\\Http\\Kernel->handle()
#44 {main}

**Comment by HDVinnie** [comment]
Use the issue templates.....they are there for a reason.
