### ISSUE TITLE
[Enhancement] Extend notification system to allow notifications to be optionally sent by email

### ISSUE THREAD

**Issue by yesimanoob** [HDInnovations/UNIT3D-Community-Edition#1443]
**Is your feature request related to a problem? Please describe.**
UNIT3D has a nice notification system, but it is limited to use within the page itself. It would be great if notification support was extended so that notifications could also be sent by email. Optionally, of course, per the user's settings/preferences.

**Describe the enhancement you'd like**
If the setting is enabled, when a notification is issue for a user per the rules set in their profile an email is sent to the user, in addition to a notification being sent on the site's notification system.

**Describe alternatives you've considered**
None

**Additional context**
Thank you for your consideration.

**Comment by HDVinnie** [comment]
I agree this would be a nice enhancement. I will look into adding this functionality this week.
