### ISSUE TITLE
[Feature] VIP Status is not available i.e no start/end dates available

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#1446]
**Is your feature request related to a problem? Please describe.**
When a member is made a VIP (FOR DONATING) There is no option to see when they donated, how much they donated or, when the VIP period ends.

**Describe the solution you'd like**
We would appreciate The VIP Group details include the ability to enter the dates of both start and end VIP and the amount paid.

**Describe alternatives you've considered**
The only other way to determin when a VIP period expires is to keep external records which is not ideal and not as secure as an on site function

**Additional context**

**Comment by HDVinnie** [comment]
There is no Donation system in UNIT3D thus there is no reason to support this.

**Comment by torman365** [comment]
But you do have a VIP system that should have some sort of start/end period even if donations are not implemented.

**Comment by HDVinnie** [comment]
Where is there a VIP System...

**Comment by torman365** [comment]
Sorry, should have said VIP Group

**Comment by HDVinnie** [comment]
There is no VIP group either.....
