### ISSUE TITLE
[Bug] Quoting a comment that contains a quote results in badly formatted posts

### ISSUE THREAD

**Issue by Tzuriel25** [HDInnovations/UNIT3D-Community-Edition#1448]
**Describe the bug**
When you add the text to quote after the quote (which is where it goes by default) the new text appears to the right of the original.  If it's long, it starts to scroll under but it looks really bad.

**To Reproduce**
On Demo site: https://unit3d.site/forums/topics/2?page=1#post-4
1. Go to Forums
2. Create a Topic with some text
3. Quote that comment
4. Quote the quoted comment
5. Formatting error as above
**Expected behavior**

**Screenshots**
Original being quoted looks fine:
![image](https://user-images.githubusercontent.com/43972449/94866782-9cfb6200-0405-11eb-9749-d8582b1893f4.png)

Quoting that post with a new comment formats badly:
![image](https://user-images.githubusercontent.com/43972449/94866832-b3a1b900-0405-11eb-8f9e-18827a8ce4f9.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: Currently Running UNIT3D Community Edition (Nex-Gen Torrent Tracker) v3.0.0
- Laravel Version: Ver. 7.28.3
- PHP Version: php7.4.3
- Database Driver & Version: 8.0.21-0ubuntu0.20.04.4
- Web Server Driver & Version: 
- OS Driver and Version: UBUNTU 20.04

**Desktop (please complete the following information):**
 - OS: WIndows 10
 - Browser: Chrome
 - Version: 85.0.4183.121 (Official Build) (64-bit)

**Comment by TPS-Zappateers** [comment]
example: Pressing "quote" button on a post containing;

> [quote=@author#1]1st comment[/quote]
> 2nd comment

results in;

> [quote=@author#2][list]                          [*]                                                     [b][i][/i] Quoting @author#2 :[/b]                              1st comment                                                                              [/list]
> 2nd comment[/quote]

where I would expect to see;

> [quote=@author#2][quote=@author#1]1st comment[/quote]
> 2nd comment[/quote]
> 3rd Comment

So, author#1 is lost, and [list] & an empty [i] is introduced.
Depending on the length of the 3rd comment, it can appear as tzuriel explains, or can be lost completely.

Really dificult to explain any kind of work-a-round to members for this bug!
