### ISSUE TITLE
[Bug] Mass-PM takes too much memory

### ISSUE THREAD

**Issue by fionera** [HDInnovations/UNIT3D-Community-Edition#1450]
**Describe the bug**
When you have a lot of Users, the Mass-PM feature requires a very high memory limit and times out.

**To Reproduce**
1. Have 8000 users
2. Send a Mass Message
3. See error

**Expected behavior**
The messages should be send.

**UNIT3D (please complete the following information):**
- UNIT3D Version: master
- Laravel Version: -
- PHP Version: 7.4
- Database Driver & Version: -
- Web Server Driver & Version: Nginx 
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: -
 - Browser: -
 - Version: -

**Additional context**

**Possible Fix?**
The Messages should be send in the Background in batches and not as a single Call.

**Comment by HDVinnie** [comment]
@fionera im not able to replicate this. The mass pm function already loops through all users and dispatches a queued job.

```
        foreach ($users as $user) {
            $this->dispatch(new ProcessMassPM(self::SENDER_ID, $user->id, $subject, $message));
        }
```

It wouldn't send all 8000 at once unless using the `sync` queue driver. What do you suggest?

**Comment by HDVinnie** [comment]
@fionera be sure to test the latest PR. https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/1451

I am seeing no memory/timeout issues sending a mass pm to 18,500 users.
