### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#1456]
**Describe the bug**
after the update, the new torrents do not rank at the top of the torrents list, even in the toptorrents list

**To Reproduce**
1. upload a new torrent

**Screenshots**
[https://gyazo.com/efb094ea312c3122e53fcda87fa64991](url)

**UNIT3D (please complete the following information):**
- UNIT3D Version: 3.0.0
- Laravel Version: Ver. 8.9.0
- PHP Version: php7.4.3
- Database Driver & Version: 8.0.21-0ubuntu0.20.04.4

**Comment by HDVinnie** [comment]
The top torrents block works fine. Your just not giving it time for the cache to bust. As for the time that's due to what your server timezone is vs what you have in your app.php config.
