### ISSUE TITLE
[Bug] Gallery Create New Album not working

### ISSUE THREAD

**Issue by mkllrtxn** [HDInnovations/UNIT3D-Community-Edition#1457]
**Describe the bug**
Create new Album is not working under the Gallery section. It gives Bad IMDB Request

**To Reproduce**
1. Go to gallery
2. Click on Create New Album
3. Input data and IMDB ID
4. Error: Bad IMDB Request

**Expected behavior**
A new album is created with the uploaded images

**UNIT3D (please complete the following information):**
- UNIT3D Version: 3.0.0
- Laravel Version: 7.28.3
- PHP Version: 7.4.11
- OS Driver and Version: 5.7.31-0ubuntu0.18.04.1

**Desktop (please complete the following information):**
 - OS: Any
 - Browser: Any

**Comment by alvinlander** [comment]
can i assign this issue ?

**Comment by HDVinnie** [comment]
@alvinlander if you wish. OMDB has been removed from UNIT3D. Gallery system needs to be refactored.
