### ISSUE TITLE
[Feature] Please add a "50% freeleech" (half-download) option

### ISSUE THREAD

**Issue by yesimanoob** [HDInnovations/UNIT3D-Community-Edition#1475]
**Is your feature request related to a problem? Please describe.**
Not specifically, no.

**Describe the solution you'd like**
Please add a "half download" (50% freeleech) option that will only count 50% of the data downloaded for a specific torrent.

**Describe alternatives you've considered**
Have tried using double upload as an alternative, but with small communities and a few heavyweight autoleech seedbox users, double upload doesn't really do much for the average user.

**Additional context**
This feature is pretty common and available on other trackers. I wouldn't mind if the feature was configurable in a settings file with it off by default if there are folks who don't want this option to appear on their site.

**Comment by iamuser00110001** [comment]
Might be an idea to add some sort of percentage slider, from 10% to 100% ?

**Comment by HDVinnie** [comment]
My idea was to refactor the discount system for torrents. Pretty much remove the columns from the torrents table like `free`, `doubleup` and `featured`. Then create a new `torrent_buffs` table.

Something like:
```
        Schema::create('torrent_buffs', function (Blueprint $table) {
            $table->bigIncrements('id')->primary();
            $table->bigInteger('torrent_id')->index();
            $table->integer('user_id')->index();
            $table->boolean('freeleech')->default(false);
            $table->decimal('freeleech_percentage', 3, 2); // 0% to 100%
            $table->boolean('double_upload')->default(false);
            $table->boolean('featured')->default(false); // double_upload + 100% freeleech
            $table->dateTime('expired_at')->nullable();
            $table->timestamps();
        });
```

That way timed buffs and sliding freeleech percentage...I just haven't had time yet. PR's are welcome!!

**Comment by leighmacdonald** [comment]
I suppose this is basically what my pr @ #1483 does? Not sure it needs another table?

**Comment by HDVinnie** [comment]
@leighmacdonald its a start yes...still needs timed buffs and whatnot but def a start. I'll review it closer soon.
