### ISSUE TITLE
[Bug] No Peers after update to v4.0.0

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#1478]
**Describe the bug**
After the update to v4, there are no more peers in the peers table.
New nor previous existing torrents have any peers in the peer list (peers disappear).
Users have 0 Seeding torrents in their profiles, although they have several torrents seeding in their client.

**To Reproduce**
1. Update to v4
2. Create a new torrent (upload it) & start seeding it (force reannounce if needed)
3. Approve the torrent in unit3d and go to the peer list
4. No Peer will be shown even tho the client does not report any error.

**Expected behavior**
Peers will be listed and BON points earned.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 4.0.0
- Laravel Version: 1.6.2
- PHP Version: 7.4
- Database Driver & Version:
- Web Server Driver & Version: NGINX
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: any (not related to browser/client os)
 - Browser: any
 - Version:

**Comment by HDVinnie** [comment]
As noted in the release notes.

Be sure to run `php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo systemctl restart php7.4-fpm` after updating.

Then run: 
`php artisan tinker`
`$torrents = App\Models\Torrent::all();`
`foreach($torrents as $torrent) { $torrent->bumped_at = $torrent->created_at; $torrent->save(); }`

You should then run `php artisan fetch:meta` to fetch meta data for your preexisting torrents. Depending on how many you have this can take some time. Make sure you leave terminal open while command is processing. Do NOT close until complete.

`php artisan fetch:meta` will dispatch ALOT of jobs to process the new meta for your preexisting torrents. This will cause announce jobs to be delayed until meta is done processing this one time command. Rest assured the announce jobs are queued so they will process when meta is done.

I do suggest editing your supervisor config to have more processes like I did in the installer.
https://github.com/poppabear8883/UNIT3D-INSTALLER/commit/851df49b865d0336ac43be060b7fd22c70ff673a

`nano /etc/supervisor/conf.d/unit3d.conf` remove sleep and tries and bump processes to 10-15 depending on your servers specs. Then of course `php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo systemctl restart php7.4-fpm` to make sure they take effect.
