### ISSUE TITLE
[Feature] Improvement to forum search

### ISSUE THREAD

**Issue by PompeyNeil** [HDInnovations/UNIT3D-Community-Edition#1486]
**Is your feature request related to a problem? Please describe.**
When searching forums, I type in my search term and hit enter (carriage return), but nothing happens. I have to press the "Search" button for a "Topic Name Quick Search" or the "Update Results" button on a Forum Topic search. I'd normally expect the enter key to perform the default action
**Describe the solution you'd like**
When I press the enter key I would like it to perform the search as if I had pressed the "Search" or "Update Results" button 
**Describe alternatives you've considered**
None
![Search 1](https://user-images.githubusercontent.com/74563141/99294975-b6812d80-283c-11eb-83de-cb6b6acf82b9.JPG)
![Search 2](https://user-images.githubusercontent.com/74563141/99294977-b719c400-283c-11eb-8978-8d11902de5fa.JPG)

**Additional context**

**Comment by Tzuriel25** [comment]
Just to confirm this comes from the Zappateers staff
