### ISSUE TITLE
[Feature] Improve Torrent by Category view

### ISSUE THREAD

**Issue by PompeyNeil** [HDInnovations/UNIT3D-Community-Edition#1487]
**Is your feature request related to a problem? Please describe.**
When I select the Torrents view, some of the columns are sortable by clicking on the column heading: Name, Created At, Size, S, L, C. However, when I look at the Torrents by Category, the column heading sort feature is not available. The column descriptions for Created At, Size, S, L, C are also missing in the by Category view.
**Describe the solution you'd like**
Please make the column headings in the Torrents By Category view sortable (the same as the Torrents view) and include the column descriptions
![Torrent 1](https://user-images.githubusercontent.com/74563141/99297388-1b8a5280-2840-11eb-8179-4138487950f0.JPG)
![Torrent 2](https://user-images.githubusercontent.com/74563141/99297391-1c22e900-2840-11eb-8891-f96e536e3de3.JPG)

**Describe alternatives you've considered**
None
**Additional context**

**Comment by Tzuriel25** [comment]
Just to confirm that this is from the Zappateers staff.  Thanks
