### ISSUE TITLE
[Enhancement] Sub Category / Add separate Type for each Category

### ISSUE THREAD

**Issue by SNG66** [HDInnovations/UNIT3D-Community-Edition#1489]
**Describe the enhancement you'd like**
Add Sub Category
and add Types for each Category/Sub Category 

This will allow non-movie torrent trackers possible.

**Comment by LilTrublMakr** [comment]
I would also like to see this. Even though I am just messing around with trackers, I feel the current system of using 'types' is very clunky and hard to use past using just a few. 

IE: If you are running a general tracker, if you have tags for video formats, music formats, reading formats, game systems/formats, etc, you would easily have over 50 or maybe even over 100 types. Going through that list would be a nightmare. 

With the current system, I am more inclined to use the tags system more than the types.
