### ISSUE TITLE
[Bug] - Can´t get IRC announce to work

### ISSUE THREAD

**Issue by Neodkbits** [HDInnovations/UNIT3D-Community-Edition#1490]
Hello, i get this error when trying to upload,

irc-bot.php is edited.

 fwrite(): send of 116 bytes failed with errno=32 Broken pipe {"userId":3,"exception":"[object] (ErrorException(code: 0): fwrite(): send of 116 bytes failed with errno=32 Broken pipe at /var/www/html/app/Bots/IRCAnnounceBot.php:94)

**Comment by napzter13** [comment]
I got the same issue. Any explanations for it yet?
