### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by HengeDK** [HDInnovations/UNIT3D-Community-Edition#1492]
**Describe the bug**
Then you have more than 5 categories
the lidt of categories goes out of the screen to the right

**To Reproduce**
1. Create more than 5 torrent categories
2. Click on torrent and select categories
3. See the error in the right side off the screen
4. The categories is listed out of the screen

The categories should be listed under each other

**Screenshots**
![D1E3B2C5-20B2-4EEA-B725-3C7D00F06EE5](https://user-images.githubusercontent.com/9641867/100486038-aef63a00-3102-11eb-96d3-966303144ddd.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version:4.0.0
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:win 10
 - Browser:Firefox 
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by nikosuk** [comment]
i should note also that no category images are shown
