### ISSUE TITLE
Site layout issues

### ISSUE THREAD

**Issue by hucstar** [HDInnovations/UNIT3D-Community-Edition#1496]
Ubuntu20,  Automatic installation
I have successfully built a website, but  It looks like there's something wrong with its front.
![_20201129205251.png](https://i.loli.net/2020/11/29/LekBvHW9apAGJK1.png)
And I have clicked the button many times that agreed to get the cookie, but it does not respond any thing.
![_20201129205230.png](https://i.loli.net/2020/11/29/pa25SzMEcydOQ3h.png)
Could you give me some suggests? Thank you!

**Comment by HDVinnie** [comment]
I can suggest that you use the issue templates next time on GitHub. It's clear you did NOT successfully built a UNIT3D instance. You need to provide more info. Is site https? Did you use https during installer? What errors are you seeing in your browser console? Have you tried rebuilding your assets? If you cannot provide this info or do the tests I suggest hiring someone to setup UNIT3D for you as it works perfectly fine.

In the end this is not a BUG with UNIT3D and is clearly a misconfiguration / mistake from your end.
