### ISSUE TITLE
[Bug] Bon, warnings, etc. do not work

### ISSUE THREAD

**Issue by saulsr90** [HDInnovations/UNIT3D-Community-Edition#1517]
**Describe the bug**
Bon, warnings, etc. do not work

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 4.0
- Laravel Version: 8.15.0
- PHP Version: 7.4.13
- Database Driver & Version: Mysql 5.7.32-0ubuntu0.18.04.1
- Web Server Driver & Version: 
- OS Driver and Version: Ubuntu 18.04

**Additional context**
**In crontab:**

* * * * * www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\

**When I run the command manually:**
root@server:/var/www/html# php /var/www/html/artisan schedule:run
No scheduled commands are ready to run.

If I run one of the commands manually like the bonus one it works:
php artisan auto: bon_allocation

I have other tasks in the crontab that do work.

When I check the cron log this appears:
root @ server: / var / www / html # grep CRON / var / log / syslog
Dec 16 22:59:01 server CRON[1295]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 22:59:01 server CRON[1294]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 22:59:01 server CRON[1293]: (CRON) info (No MTA installed, discarding output)
Dec 16 22:59:01 server CRON[1292]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:00:01 server CRON[1317]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:00:01 server CRON[1316]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:00:01 server CRON[1314]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:00:01 server CRON[1315]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:01:01 server CRON[1422]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:01:01 server CRON[1421]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:01:01 server CRON[1420]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:01:01 server CRON[1419]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:02:01 server CRON[1431]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:02:01 server CRON[1432]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:02:01 server CRON[1430]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:02:01 server CRON[1429]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:03:01 server CRON[1438]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:03:01 server CRON[1439]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:03:01 server CRON[1436]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:03:01 server CRON[1437]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:04:01 server CRON[1447]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:04:01 server CRON[1446]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:04:01 server CRON[1444]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:04:01 server CRON[1445]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:05:01 server CRON[1485]: (www-data) CMD (php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:05:01 server CRON[1486]: (root) CMD (www-data php /var/www/html/artisan schedule:run >> /dev/null 2>&1\)
Dec 16 23:05:01 server CRON[1483]: (CRON) info (No MTA installed, discarding output)
Dec 16 23:05:01 server CRON[1484]: (CRON) info (No MTA installed, discarding output)

**Comment by HDVinnie** [comment]
They work fine. Confirmed locally, on demo and a production site. Something is wrong you end with cron. Whats in `sudo crontab -e`

**Comment by saulsr90** [comment]
Solved. I have modified it and instead of with the WWW-data user I do it with root although I know it is not necessary but at least it works like this for me.
