### ISSUE TITLE
auto-install ubuntu-20

### ISSUE THREAD

**Issue by rveyn** [HDInnovations/UNIT3D-Community-Edition#1519]
**Describe the bug**
I run the install scripts all was fine, until :

===============================================================================
    Configuring & Securing Database
================================================================================

cp -f /root/installer/src/Helpers/../Resources/ubuntu/mysql/my-large.cnf /etc/mysql/my.cnf
[░░░░░░░░░░░░░░░░░░░░░░░░░░░░] (Done!)
mysql_install_db
[============================] (Done!)

 [ERROR] sh: 1: mysql_install_db: not found

root@tyyu:~/installer#

**Comment by HDVinnie** [comment]
This issue doesn't belong here. Its installer related and you already opened a issue there.
