### ISSUE TITLE
[Bug] 500 error on first login after registration

### ISSUE THREAD

**Issue by Zorlin** [HDInnovations/UNIT3D-Community-Edition#1521]
**Describe the bug**
Users logging into the site for the first time are sometimes greeted with a 500 error. Clicking go home allows them to continue.

**To Reproduce**
* Create an account and log in

**Expected behavior**
No errors

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.0.0
- Laravel Version: Latest via installer
- PHP Version: 8.0.0
- Database Driver & Version: Latest MariaDB via installer
- Web Server Driver & Version: Latest Nginx via installer
- OS Driver and Version: Ubuntu 20.04 64-bit

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - Browser: Chrome, Firefox
 - Version: All versions as far as I can tell

**Additional context**
One of my first major users ran into it on first login :(

**Possible Fix?**
Laravel logs have this message a bunch of times

Too few arguments to function App\Helpers\BBCodeConverter::__construct(), 1 passed in /var/www/html/app/Models/Page.php on line 67 and exactly 2 expected (View: /var/www/html/resources/views/page/page.blade.php) {"userId":12,"exception":"[object] (ErrorException(code: 0): Too few arguments to function App\\Helpers\\BBCodeConverter::__construct(), 1 passed in /var/www/html/app/Models/Page.php on line 67 and exactly 2 expected (View: /var/www/html/resources/views/page/page.blade.php) at /var/www/html/app/Helpers/BBCodeConverter.php:24)

**Comment by HDVinnie** [comment]
Was fixed yesterday. As instructed just run `php artisan git:update`.

**Comment by Zorlin** [comment]
Yep, confirmed resolved after running that. Thanks!
