### ISSUE TITLE
How to delete new forum created

### ISSUE THREAD

**Issue by asgaros891** [HDInnovations/UNIT3D-Community-Edition#1529]
I went to staff dashboard - Forum - and I don't see anything there except to create a new one, but as I had created in the meantime a forum where I was wrong with the title, now I have no option to delete

OS Ubuntu 20.4
UNIT3d final version 5

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/categories/q-a
