### ISSUE TITLE
[Bug] Torrent Description Linux Line-breaks not applied

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#1542]
**Describe the bug**
If i post a torrent using mechanize (& unit3d API) the line breaks within the description are not applied and the whole content is on one single line.
The content for posting is copy & pasted from some nfo data.

**To Reproduce**

**Expected behavior**
Line breaks are applied as on the nfo where i copied the text from.

**Screenshots**
[https://i.imgur.com/j1kTpOQ.png](https://i.imgur.com/j1kTpOQ.png)
Screenshot from unit3d.site: [https://unit3d.site/torrents/2](https://unit3d.site/torrents/2)

**UNIT3D (please complete the following information):**
- UNIT3D Version: 4.0.0 & 5.0.0
- Laravel Version:
- PHP Version: 7 & 8
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by Oha-you** [comment]
Just checked this behavior both at https://unit3d.site/ from Windows and locally from Ubuntu: **can't reproduce**.

Copied text with LF line endings, pasted to torrent descriptions and forums posts (with BBCode off and on): each time line breaks were present.

I think issue is no longer relevant, can be closed. Ping: @HDVinnie
