### ISSUE TITLE
[Bug] Go to Torrent Grouping Page

### ISSUE THREAD

**Issue by MaikCZ** [HDInnovations/UNIT3D-Community-Edition#1544]
**Describe the bug**
`
prod.ERROR: Attempt to read property "genres" on null (View: /var/www/html/resources/views/torrent/groupings.blade.php) {"userId":3,"exception":"[object] (ErrorException(code: 0): Attempt to read property "genres" on null (View: /var/www/html/resources/views/torrent/groupings.blade.php) at /var/www/html/storage/framework/views/a11245ae62b0aaa58b1a7b688f5728a884b1d601.php:316
`

**To Reproduce**
1. Go to Torrent Grouping Page
2. See error

**Expected behavior**
No error 500.

**Screenshots**
none

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.0.0
- Laravel Version: 8.19.0
- PHP Version: 8.0
- Database Driver & Version: 8.0.22-0ubuntu0.20.04.3
- Web Server Driver & Version: nginx/1.18.0 
- OS Driver and Version: ubuntu 20.04.3

**Desktop (please complete the following information):**
 - OS: MAC OSX
 - Browser: CHROME
 - Version: 87.0.4280.88

**Additional context**
none

**Possible Fix?**
none

**Comment by HDVinnie** [comment]
fixed in a3ddbf0f218a8157a57174aae2e1838579020658
