### ISSUE TITLE
Coupons

### ISSUE THREAD

**Issue by TheFelin** [HDInnovations/UNIT3D-Community-Edition#1546]
one too many zero

![Screenshot_20201229_213923](https://user-images.githubusercontent.com/51317099/103312869-9d17f780-4a1e-11eb-99e9-d9bf2f07707f.png)
![Screenshot_20201229_213948](https://user-images.githubusercontent.com/51317099/103312875-a012e800-4a1e-11eb-8d9c-bdca9360cad2.png)

**Comment by HDVinnie** [comment]
UNIT3D Community Edition Issues tracker on GitHub is now strictly for BUG reports. You must follow the issue template for BUGS and give it a meaningful title after the [Bug] prefix or it will be closed without response.
