### ISSUE TITLE
[Bug] Invite activation ling

### ISSUE THREAD

**Issue by MaikCZ** [HDInnovations/UNIT3D-Community-Edition#1555]
**Describe the bug**
prod.ERROR: Access Token could not be retrieved from Twitch. {"userId":296,"exception":"[object] (MarcReichel\\IGDBLaravel\\Exceptions\\AuthenticationException(code: 0): Access Token could not be retrieved from Twitch. at /var/www/html/vendor/marcreichel/igdb-laravel/src/Builder.php:207)

prod.ERROR: Undefined array key 0 {"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1426)
[stacktrace]

No work activate invities activate link
See error
Expected behavior
No error 500.

Screenshots
none

UNIT3D (please complete the following information):

UNIT3D Version: 5.0.0
Laravel Version: 8.19.0
PHP Version: 8.0
Database Driver & Version: 8.0.22-0ubuntu0.20.04.3
Web Server Driver & Version: nginx/1.18.0
OS Driver and Version: ubuntu 20.04.3
Desktop (please complete the following information):

OS: MAC OSX
Browser: CHROME
Version: 87.0.4280.88
Additional context
none

Possible Fix?
none

**Comment by HDVinnie** [comment]
Games are not supported. Change your game categories to no meta. IGDB api is going to be removed.

**Comment by HDVinnie** [comment]
And the error you posted has nothing to do with invites

**Comment by MaikCZ** [comment]
Vinnie, another login error doesn't write, but a really active registration has a 500 error

**Comment by HDVinnie** [comment]
either open a proper issue or ask support on discord....

**Comment by HDVinnie** [comment]
and if your logs are not generating then delete them and fix your perms

`sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +`

**Comment by MaikCZ** [comment]
Log generated, this my file
[laravel-2021-01-03.log](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/5761065/laravel-2021-01-03.log)
