### ISSUE TITLE
[Bug]tool possible cheaters Error 500

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#1573]
since short when i tried to start tool possible cheaters i got an error "Error 500: Internal Server Error!"

1. Go to 'staff dashboard'
2. Click on 'possible Cheaters'
3. Wait
4. See error "Error 500: Internal Server Error!"

laravel log shows:
prod | Error | 10:30:08 | Call to a member function  toDayDateTimeString() on null (View:   /var/www/html/resources/views/Staff/cheater/index.blade.php)   {"userId":3,"exception":"[object] (ErrorException(code: 0): Call to a   member function toDayDateTimeString() on null (View:   /var/www/html/resources/views/Staff/cheater/index.blade.php) at   /var/www/html/storage/framework/views/2a38223dfe585c4b7e7de0f584e9b40087b42728.php:59)
-- | -- | -- | --

**Expected behavior**
to see possible cheaters when exists

**UNIT3D (please complete the following information):**
- UNIT3D Version: 3.00
- Laravel Version: Laravel Framework 7.27.0
- PHP Version: PHP 7.4.3
- Database Driver & Version:  mysql 8.0.22
- Web Server Driver & Version: nginx/1.18.0 (Ubuntu)
- OS Driver and Version: 

**Desktop (please complete the following information):**
 - OS: win 10
 - Browser: firefox
 - Version: 84.0.1 (64-Bit)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JamesPSS** [comment]
The UNIT3D Version: 3.00 is "End Of Life". 
You can see here what version thats is supported https://github.com/HDInnovations/UNIT3D-Community-Edition

**Comment by kREATUr67** [comment]
nice
