### ISSUE TITLE
[Bug] Error 500 after attempting to create poll

### ISSUE THREAD

**Issue by piratkongen** [HDInnovations/UNIT3D-Community-Edition#1586]
**Describe the bug**
When in Staff Area > Polls, Trying to create a new poll (the first one) with any text and and 2 answers, then clicking CREATE.
(Not multiple choice checked),
It returns error 500 at address:
**/dashboard/polls/store**

No Laravel log are recorded. (For the first time for an error 500)

**Expected behavior**
To create poll.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1
- Laravel Version: Ver. 8.21.0
- PHP Version: php8.0.0
- Database Driver & Version: 8.0.22-0
- Web Server Driver & Version: ubuntu0.20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280

**Comment by HDVinnie** [comment]
You'll need to provide the error. Make sure your perms are correct. Run `sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +` from project root and then try to create a poll. If fails check log.

**Comment by piratkongen** [comment]
Aight.

The error was:

```
3 arguments are required, 2 given {"userId":3,"exception":"[object] (ArgumentCountError(code: 0): 3 arguments are required, 2 given at /var/www/html/app/Models/Poll.php:124) | Stack
-- | --
```


And I was able to solve it by changing 
`\sprintf('%%s%', $slug)`
to
`\sprintf('%%s%%', $slug)`
on line 124 in /app/Models/Poll.php
