### ISSUE TITLE
[Bug] Error 500 on /dashboard/audits

### ISSUE THREAD

**Issue by piratkongen** [HDInnovations/UNIT3D-Community-Edition#1587]
**Describe the bug**
When in Staff Area, clicking on 'Activity log'
It returns error 500 at address:
**/dashboard/audits**

**Expected behavior**
Access Activity log.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1
- Laravel Version: Ver. 8.21.0
- PHP Version: php8.0.0
- Database Driver & Version: 8.0.22-0
- Web Server Driver & Version: ubuntu0.20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280

Stack error:
`SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size (SQL: select * from `audits` order by `created_at` desc limit 50 offset 0) {"userId":3,"exception":"[object] (Illuminate\\Database\\QueryException(code: HY001): SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size (SQL: select * from `audits` order by `created_at` desc limit 50 offset 0) at /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:678)`

**Comment by Tigerdyret** [comment]
We need the log.. check if the log file have the right permissons.

**Comment by piratkongen** [comment]
Running this in MySQL solved it:
`SET GLOBAL sort_buffer_size = 256000000;`
