### ISSUE TITLE
[Bug] Target class [App\\Http\\Controllers\\Staff\\Request] does not exist. at /vendor/laravel/framework/src/Illuminate/Container/Container.php:832

### ISSUE THREAD

**Issue by piratkongen** [HDInnovations/UNIT3D-Community-Edition#1588]
**Describe the bug**
When in Staff Area, clicking on 'Failed login attempts' OR 'Invite log' OR 'Warnings log'
It returns error 500 at addresses:
_/dashboard/authentications
/dashboard/invites
/dashboard/warnings_

**Expected behavior**
Access Failed Login attempts, access Invite log views and access warnings log.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1
- Laravel Version: Ver. 8.21.0
- PHP Version: php8.0.0
- Database Driver & Version: 8.0.22-0
- Web Server Driver & Version: ubuntu0.20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280

**Stack error:**
```
`
Target class [App\Http\Controllers\Staff\Request] does not exist. {"userId":3,"exception":"[object] (Illuminate\\Contracts\\Container\\BindingResolutionException(code: 0): Target class [App\\Http\\Controllers\\Staff\\Request] does not exist. at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:832)
--
`
```

All 3 pages gives exactly the same stack error. And can't seem to fix it without compromising the pages to everyone.

**Comment by JamesPSS** [comment]
Did you change something?. 

Its sayning that the file "App\Http\Controllers\Staff\Request" does not exist and i can't find anything that point to that thing in the source.

I need the full laravel log to see what happen and if you did change something i can't help.

**Comment by piratkongen** [comment]
Ah yes mb. I did change following in the controllers in order to limit access.
Didn't suspect that, because it worked fine on some staff pages, but only on these 3 it did not work.

![image](https://user-images.githubusercontent.com/77119791/104198462-8b731e80-5426-11eb-9951-78b83afb4217.png)

**Comment by JamesPSS** [comment]
Hi 

Before you can use the request function you need to tell the controller where to find it.

"use Illuminate\Http\Request;"

Then you can use the request.

And you can use 

\abort_unless($request->user()->group->is_admin, 403) If you don't need the $user variable other places.
