### ISSUE TITLE
[Bug] Filtering the torrent view on "Health" works exclusively only

### ISSUE THREAD

**Issue by TurtleWilly** [HDInnovations/UNIT3D-Community-Edition#1625]
**Describe the bug**
When using the "Filter" on the torrent index (`https://tracker.example/torrents`) to search or limit a search for torrents then using the `Health` values seem to work exclusively only, albeit the UI suggested it should work in an additive way.

Currently when selecting multiple values (e.g. "alive" *and* "dead") there are *no* results, instead results for all selected values.

E.g. just selecting "alive" -> results (OK), just selecting "dead" -> results (OK), but selecting "alive" and "dead" -> no results (FAIL)   Either the boolean logic should be fixed or the 3 separate checkmarks could become one single radio button. I personally would prefer the first way as it makes most sense.

**To Reproduce**
1. Go to '/torrents'
2. Click on 'Filter'
3. Scroll down to `Health`
3. Select multiple (more than one) values, e.g. "alive" and "dead"
4. Result: No results are displayed

**Expected behavior**
Results for all selected values should be displayed.

**Screenshots**
n/a

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1.0
- Laravel Version: 8.22.1
- PHP Version: 8.0.1
- Database Driver & Version: 5.7.32-0ubuntu0.18.04.1
- Web Server Driver & Version: n/a
- OS Driver and Version: Linux

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Safari
 - Version: n/a

**Additional context**
n/a

**Possible Fix?**
n/a

**Comment by HDVinnie** [comment]
This will be addressed in the torrent search refactor to Livewire. There is no ETA at this point however.

**Comment by Oha-you** [comment]
Issue should probably be reopened since merged changes in 1acc900664beab8453032f472700673b46f11884 have been undone in c7593365c5ff503ca0c271b33517ebcff54814de.
Using `orWhere` when only one Health option is checked will produce a wrong query, that's why I had to use variable variables in #1723 :)
