### ISSUE TITLE
[Feature] Multiple use invite codes

### ISSUE THREAD

**Issue by Zorlin** [HDInnovations/UNIT3D-Community-Edition#1626]
I would like to be able to make a limited invite link. So that you could give it out and say 50 people could use it to sign up. I want to be able to print a code on a business card and give it out.

Cheers!

**Comment by HDVinnie** [comment]
This issue tracker is for bugs only. Please use proper channels. https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/categories/feature-ideas
