### ISSUE TITLE
[Bug] Undefined array key 0

### ISSUE THREAD

**Issue by denis-ev** [HDInnovations/UNIT3D-Community-Edition#1627]
**Describe the bug**
```
ErrorException
Undefined array key 0
```

**To Reproduce**
New Server Ubuntu 20.04
Using automated Installation Script
Database User wasn't setup correctly (Password not accepted) fix that by changing the password

User gets recognised, but I cannot login.
Unknown user and/or password throws correct error message

**Expected behavior**
Login and be able to see backend

**Screenshots**

**UNIT3D (please complete the following information):**
automated installer Feb 03 2021

**Desktop (please complete the following information):**
 - OS: MacOS 11.1
 - Browser: Safari

**Comment by HDVinnie** [comment]
Appears your cache is busted. Just run `php artisan cache:clear` from project root.
