### ISSUE TITLE
[Bug] Potential issue with backups

### ISSUE THREAD

**Issue by Zorlin** [HDInnovations/UNIT3D-Community-Edition#1634]
**Describe the bug**
Backing up stuff throws an error in the Laravel logs.

**To Reproduce**
1. Create a backup and check the logs

**UNIT3D (please complete the following information):**
- UNIT3D Version: Currently Running UNIT3D Community Edition (Next-Gen Torrent Tracker) v5.0.0
- Laravel Version: Ver. 8.19.0
- PHP Version: php8.0.0
- Database Driver & Version: /usr/sbin/mysqld  Ver 8.0.23-0ubuntu0.20.04.1 for Linux on x86_64 ((Ubuntu))
- Web Server Driver & Version: nginx/1.18.0 (Ubuntu)
- OS Driver and Version: Ubuntu 20.04 64-bit

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: Latest stable

**Additional context**
Class "PhpZip\Constants\ZipEncryptionMethod" not found {"userId":3,"exception":"[object] (Error(code: 0): Class \"PhpZip\\Constants\\ZipEncryptionMethod\" not found at /var/www/html/app/Listeners/PasswordProtectBackup.php:33)

**Comment by HDVinnie** [comment]
You need to update to latest v5.1.0 where this was already addressed.
