### ISSUE TITLE
[Bug] Browsing Requests on X page, going forth to a request and then back, causing bug.

### ISSUE THREAD

**Issue by piratkongen** [HDInnovations/UNIT3D-Community-Edition#1635]
**Describe the bug**
When at Requests page, browsing on a page higher than the first one.
Then on URL /requests/filter?page=2, going forth to a torrent,
then going back again, it shows the faceted view without any style.

**Expected behavior**
View Request page X with normal styling.

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.1
- Laravel Version: Ver. 8.21.0
- PHP Version: php8.0.0
- Database Driver & Version: 8.0.22-0
- Web Server Driver & Version: ubuntu0.20.04.3

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Google Chrome
 - Version: 87.0.4280

**Comment by HDVinnie** [comment]
This is not a bug and is the nature of a faceted Ajax search system. As discussed before this will be "fixed" when we refactor the torrent search system to Livewire. https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/1432
