### ISSUE TITLE
[Bug] genre filter not working in torrent

### ISSUE THREAD

**Issue by Persival321** [HDInnovations/UNIT3D-Community-Edition#1638]
**Describe the bug**
When you try to filter by gender in torrents it doesn't work. It does not give any results.

**To Reproduce**
1. Go to '...' --> Torrents
2. Click on '....' --> Filter Genre

**Expected behavior**
If it worked I would filter by gender.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.1
- Laravel Version: 8.21
- PHP Version: 8.0.1
- Database Driver & Version: 5.7.33-0ubuntu0.18.04.1

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome

**Additional context**

I have seen that the Genre table from the mysql is empty of records.

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by Oha-you** [comment]
Looks like Genre filtering is fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/c7593365c5ff503ca0c271b33517ebcff54814de. Works fine, thanks!
