### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by will1869** [HDInnovations/UNIT3D-Community-Edition#1644]
**Describe the bug**
A clear and concise description of of what the bug is.
chatbox not working have to refresh so new 
**To Reproduce**

**Expected behavior**
to refresh on its own 
**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:3.00
- Laravel Version:version 7.30.4
- PHP Version:7.4
- Database Driver & Version: 8.023
- Web Server Driver & Version:
- OS Driver and Version: ubunto 20 lte

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome
 - Version:

**Additional context**
see you got the problem fixed on blu we would like to get it fixed on our site we dont have many members and our struglling

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by will1869** [comment]
can get chat to work by starting larvel in ssh but wont stay running as soon as leave ssh it stops

**Comment by HDVinnie** [comment]
UNIT3D Version:3.00 iss EOLand has not been supported for along time now.
