### ISSUE TITLE
[Bug] "Certified Banker!" Badge's Tooltip Is Wrong

### ISSUE THREAD

**Issue by TurtleWilly** [HDInnovations/UNIT3D-Community-Edition#1656]
**Describe the bug**
The tooltip of the "Certified Banker!" badge reports incorrect requirements. It claims "_Has 50,000 or more BON in Bank_", but the actual requirement (at least on the tested tracker) is 500,000 BON (ten times the amount).

**To Reproduce**
1. Go to "My Profile"
2. Scroll down to the "Badges" section
3. If there's a "Certified Banker!" badge hover the pointer over it and wait a bit until the tooltip appears 

**Expected behavior**
The tooltip should report the correct requirements.

**UNIT3D (please complete the following information):**
n/a

**Desktop (please complete the following information):**
 - OS: Mac OS X
 - Browser: Safari

**Comment by TurtleWilly** [comment]
> `@if ($user->seedbonus >= 50000)`
> I don't know if it's the best way but that's how I fixed it

I'm actually happy with the 500,000 value, just the tooltip's text should reflect it properly. :)

(Ideally it sould be dynamic in both cases —the check and the tooltip text— from a configurable limit, I guess.)

**Comment by andriuhaynes** [comment]
In addition,
There is a space in thousands_separator parameter in User.php Model in line return \number_format($this->seedbonus, 2, '.', ' '); 
This causes a wrong behavior when it evaluates $user->seedbonus >= 50000

**Comment by andriuhaynes** [comment]
it keeps happening :(
