### ISSUE TITLE
[Bug] Backup error

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#1665]
Hi.

When trying to launch a backup, it does not generate it and an error appears in the log.

1. Go to STAFF DASHBOARD / BACKUP MANAGER
2. Click on Create Full Backup or Files Backup or Database Backup
3. View "Please wait a few minutes ... "
4. the backup is not generated and the following message appears in the log:
[2021-03-12 11:03:30] prod.INFO: BackupManager called from staff dashboard  
[2021-03-12 11:03:30] prod.ERROR: Symfony\Component\Console\Exception\CommandNotFoundException: The command "backup:run" does not exist. in /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php:180
.....

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.2.0
- Laravel Version: 8.32.1
- PHP Version: 8.0.3
- Database Driver & Version: 8.0.23-0ubuntu0.20.04.1
- Web Server Driver & Version: 
- OS Driver and Version: ubuntu 20.04.1

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome/Firefox

**Additional context**
If I manually run the php artisan backup:run command it works fine.

Thanks

[error.txt](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/6129207/error.txt)

**Comment by HDVinnie** [comment]
Thanks. This is being looked into. It is an issue upstream and not UNIT3D itself.

**Comment by HDVinnie** [comment]
closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/fd299ade4a6a0ef2503a3b9385936f28e7ee3e9c

**Comment by hucstar** [comment]
I’m having the same problem.
