### ISSUE TITLE
[Bug] new installation using installer

### ISSUE THREAD

**Issue by HengeDK** [HDInnovations/UNIT3D-Community-Edition#1667]
**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**
1. run clean install using installer
2. go to site
3. login as admin
4. Error 500 

**Expected behavior**
login to site

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.20
- Laravel Version:
- PHP Version: 8
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**
[2021-03-12 14:17:31] prod.ERROR: Undefined array key 0 {"userId":3,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1424)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1627
