### ISSUE TITLE
[Bug] Chat not working after SSL cert is installed.

### ISSUE THREAD

**Issue by JacobP88** [HDInnovations/UNIT3D-Community-Edition#1693]
**Describe the bug**
My old server was running without SSL and everything worked just fine. I decided to install a SSL Cert, and the chat stopped working. I turned to the chat support, and was told that the installer should do the SSL, otherwise I had to reconfigure a lot of stuff.
On a fresh server, UNIT3D is installed via the installer, and SSL was also installed by the installer.
The chat is still not working. The online users says 0, and if you write something in the chat, it will only appear if you reload the page.

**To Reproduce**
N/a

**Expected behavior**
I expected the chat to work.

**Screenshots**
N/a

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.1.0
- Laravel Version: 8.33.1
- PHP Version: 8.0.3
- Database Driver & Version: MySQL 8.0.23
- Web Server Driver & Version: Nginx 1.18.0
- OS Driver and Version: Ubuntu 20.04.2 LTS

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro 19042.868
 - Browser: Google Chrome
 - Version:  89.0.4389.90

**Additional context**
N/a

**Possible Fix?**
N/a

**Comment by hucstar** [comment]
nonsupport cloudflare！

**Comment by JacobP88** [comment]
> nonsupport cloudflare！

The site is not on cloudflare.

**Comment by HEVCman** [comment]
How it was solved?
