### ISSUE TITLE
[Bug] Wrong Order in Lists under "Extra Stats"

### ISSUE THREAD

**Issue by TurtleWilly** [HDInnovations/UNIT3D-Community-Edition#1701]
**Describe the bug**
In some cases the ranking order under the various "Extra-Stats" lists, e.g. "Top Seeders" is wrong. I believe this happens when users restart their clients the hard way (aka crash) and they end up with "ghost peers." Then the order reflects the "multiplied" count. I'm not sure that's the actual reason though, but whatever the reason is: the output should be properly ordered.

**To Reproduce**
1. Go to 'https://yourtracker/stats
2. Click, e.g., on 'Users' and then, e.g. on 'Top Seeders'
3. Scroll down and check the list

**Expected behavior**
Entries are in proper order.

**Screenshots**
![strangeorder](https://user-images.githubusercontent.com/78424297/113302450-59c07400-9300-11eb-9db5-329bf930a586.png)

**UNIT3D (please complete the following information):**
n/a

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: Safari
 - Version: irrelevant

**Comment by Alkl58** [comment]
Can't reproduce, is this issue still appearing for you or other people?
