### ISSUE TITLE
[Bug] Unnecessary labels in views, "for=" attributes without ids

### ISSUE THREAD

**Issue by Oha-you** [HDInnovations/UNIT3D-Community-Edition#1716]
**Describe the bug**
Noticed two issues with `<label>` tags in views:
1. Looks like these (automated?) changes produced unexpected results: https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/1f7b8c9956961fcd69736b016d530e393adddbf0
    * Labels have been added around all inputs. They are bold by default: [_custom.scss#L501](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/resources/sass/main/_custom.scss#L501)
    * I think it doesn't follow any standards and makes text bold where it's not needed (see screenshots below)
2. There are many places where `label for="..."` is used but inputs don't have any `id=` set, like [edit_torrent.blade.php#L21](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/resources/views/torrent/edit_torrent.blade.php#L21)
    * `id` attribute (not `name`) should be set in order for `for=` label to focus the input on click: [MDN for label](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/label#attributes)

**To Reproduce**
- Go to any Edit or Settings page with form inputs:
    * `/users/<user>/settings`
    * `/dashboard/categories/1/edit`
    * `/dashboard/users/<user>/settings`

**Expected behavior**
1. Remove unnecessary labels around inputs
    * Alternatively: put one input inside one label ([example](https://html.spec.whatwg.org/multipage/forms.html#writing-a-form%27s-user-interface)), but remove global `font-weight: 700` style
2. Make sure `id` is set for each label with `for=` attribute

**Screenshots**
![2021-04-14_014430](https://user-images.githubusercontent.com/82098328/114631721-d4589e80-9cc5-11eb-870f-0591836ba2f4.png)
![2021-04-14_020234](https://user-images.githubusercontent.com/82098328/114631726-d7538f00-9cc5-11eb-8ff7-78486ce83544.png)

**UNIT3D:**
- UNIT3D Version: 5.2.0 (latest master)
- Laravel Version: 8.36.2
- PHP Version: 8.0.3
- Database Driver & Version: 8.0.23-0ubuntu0.20.04.1
- Web Server Driver & Version: nginx/1.18.0 (Ubuntu)
- OS Driver and Version: Ubuntu 20.04.2

**Desktop:**
 - OS: Ubuntu 20.04.2
 - Browser: Firefox
 - Version: 85.0

**Additional context**
MDN quote:
![2021-04-14_022925](https://user-images.githubusercontent.com/82098328/114633503-47afdf80-9cc9-11eb-9f33-7dfde65cb8be.png)

**Possible Fix?**
Manually check and fix all labels in views, provide a PR. I can help.

**Comment by HDVinnie** [comment]
This maybe will be resolved in the new UI 7-1 Pattern branch? @Roardom
