### ISSUE TITLE
[Bug]Error during update.

### ISSUE THREAD

**Issue by HanOddbjorn** [HDInnovations/UNIT3D-Community-Edition#1719]
Se the transcript of screengrab.

[Done]
==================================================
Updating UNIT3D Configuration File==================================================
git fetch origin && git checkout origin/master -- config/unit3d.php
[============================] (Done!)[Done]
==================================================
Setting Cache==================================================
Configuration cache cleared!

   Error

  Class "Laravel\Octane\OctaneServiceProvider" not found

  at vendor/laravel/framework/src/Illuminate/Foundation/Application.php:735
    731▕      * @return \Illuminate\Support\ServiceProvider
    732▕      */
    733▕     public function resolveProvider($provider)
    734▕     {
  ➜ 735▕         return new $provider($this);
    736▕     }
    737▕
    738▕     /**
    739▕      * Mark the given provider as registered.

      +29 vendor frames
  30  app/Console/Commands/GitUpdater.php:293
      Illuminate\Console\Command::call()

  31  app/Console/Commands/GitUpdater.php:158
      App\Console\Commands\GitUpdater::setCache()

**Describe the bug**
A clear and concise description of of what the bug is.

**To Reproduce**
It won't happen with another php artisan git:update

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: **v5.2.0**
- Laravel Version:**Ver. 8.36.2**
- PHP Version:**php8.0.3**
- Database Driver & Version:**MySql 8.0.23-0ubuntu0.20.04.1**
- Web Server Driver & Version:**nginx version: nginx/1.18.0 (Ubuntu)**
- OS Driver and Version:**Ubuntu 20.04.2 LTS 5.4.0-71-generic kernel**

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Firefox
 - Version: Latest

**Additional context**

**Possible Fix?**
Have no idea but the site stayed in maintenance mode and had to be bring back with up command.

Pleas ask if more info is needed. I got transcript from the hole update process.

**Comment by HDVinnie** [comment]
Just a cache issue. You should be able to run the updater again now just fine.
