### ISSUE TITLE
[Bug] Undefined Constant

### ISSUE THREAD

**Issue by masterdraco** [HDInnovations/UNIT3D-Community-Edition#1721]
**Describe the bug**
after a clean install i get internal server error 500 when i push the _Set All Cache   and this is what ends up in the log Undefined constant "Spatie\Backup\Commands\SIGINT" {"userId":3,"exception":"[object] (Error(code: 0): Undefined constant "Spatie\Backup\Commands\SIGINT" at /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php:877)

**To Reproduce**
1. Go to 'staff dashboard/commands'
2. Click on 'any command'
3. Internal server error 500

[laravel-2021-04-14.log](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/6311329/laravel-2021-04-14.log)

**UNIT3D (please complete the following information):**
- UNIT3D Version: Latest pulled from installer
- Laravel Version: 1.6.2
- PHP Version: 8.0.3
- Database Driver & Version: mysql 8.0.23
- Web Server Driver & Version:
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser: chrome, brave,edge
 - Version:

Problem does not exist when running command from shell

**Comment by HDVinnie** [comment]
This is a upstream issue. spatie/laravel-backup#1288

**Comment by HDVinnie** [comment]
@masterdraco im not able to replicate this locally or on the demo site. Spatie\Backup has nothing to do with cache commands and only is part of the backup manager.
