### ISSUE TITLE
[Bug] Helpdesk 405 Method Not Allowed when Closing a Ticket

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1725]
**Describe the bug**
Closing a Helpdesk Ticket over the "Action" Button on the main overview `/tickets` will result in a 405 Method not allowed error.
Closing it inside the ticket page (e.g. `/tickets/2`) works.

**To Reproduce**
1. Go to '/tickets'
2. Create a ticket
3. Close a ticket with "Action" -> "Close"

**Expected behavior**
´Ticket should be closed.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34812414/114768708-8ac18f80-9d69-11eb-94fd-2a5bba5fd951.png)
![grafik](https://user-images.githubusercontent.com/34812414/114768731-92813400-9d69-11eb-922c-8943a9c56b3b.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.2.0
- Laravel Version: Ver. 8.34.0
- PHP Version: php8.0.3
- Database Driver & Version: 8.0.23-0ubuntu0.20.04.1
- Web Server Driver & Version: n/a
- OS Driver and Version: Ubuntu 20.04 LTS

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 87.0

**Additional context**
Probably an easy fix with some incorrect set Submit thing.

**Possible Fix?**
n/a

**Comment by HEVCman** [comment]
yea I got this error too.
