### ISSUE TITLE
[Bug] Some movie torrents cannot be uploaded after updating with the last code 

### ISSUE THREAD

**Issue by hucstar** [HDInnovations/UNIT3D-Community-Edition#1728]
**Describe the bug**
Some movie torrents cannot be uploaded after merging the last code. Yeah, I don't understand why is just some specific types are not allowed like Full Disc Movies. TV is ok, Web movie is ok. So I think maybe there is some vulnerability somewhere in the latest code about uploading type selection. So I want to provide developers with this information. Note: There is no problem with naming.

**To Reproduce**
1. I have run `php artisan git:update` to update my website, now it is working well except Some types of movie-torrents cannot be uploaded. 
2. Test for uploading  TV, success
3. Test for uploading  Web-movies, success
4. Test for uploading  Full Disc-movies, lose

**Expected behavior**
Named as follows
Morning Star 2014 1080p GER BluRay AVC DTS-HD MA 5.1-SharpHD

**Screenshots**
![20210417135135.png](https://i.loli.net/2021/04/17/62EC4SmLswzWDav.png)

![Snipaste_2021-04-17_13-53-09.jpg](https://i.loli.net/2021/04/17/P6wuyZYWNa3o7Xb.jpg)

**UNIT3D (please complete the following information):**
- UNIT3D Version:5.2.0
- Laravel Version:8.34.0
- PHP Version:8.0.3
- Database Driver & Version:mysql5.7
- Web Server Driver & Version:n/a
- OS Driver and Version:Ubuntu 20.04 LTS

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: chrome
 - Version:89

**Additional context**
After testing, the same torrent can be uploade in Unit3d official website BLU , maybe because blu is not using the latest code?

Before the upgrade, they  can be upload that  there are special characters in the torren's name, and movies of the full disc type can also be upload too.

**Possible Fix?**
nothing

**Comment by Oha-you** [comment]
This one is on me (#1726). Sorry about that!

**Comment by hucstar** [comment]
> This one is on me (#1726). Sorry about that!

That all right！Thank you for your contribution to Unit3D and The number of pt amateurs！
