### ISSUE TITLE
[Bug] Create Ticket doesn't work (running on Git 2021.04.21)

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1736]
**Describe the bug**
Creating a ticket won't work, the website is then being rendered two times (see video below)

**To Reproduce**
1. Go to '/tickets'
2. Click on 'Create'
3. See error

**Expected behavior**
The screen for creating a ticket should appear

**Screenshots**

https://user-images.githubusercontent.com/34812414/115621252-8a3f7080-a2f6-11eb-94ee-b12a0e27be5d.mp4

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.2.0 (GIT Update from 2021.04.21)
- Laravel Version: Ver. 8.36.2
- PHP Version: php8.0.3
- Database Driver & Version: 8.0.23-0ubuntu0.20.04.1
- Web Server Driver & Version: Ubuntu 20.04
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: n/a

**Additional context**
n/a

**Possible Fix?**
n/a

**Comment by hucstar** [comment]
@Obi-Wana My situation is the same as him, which means it’s not an exception.
