### ISSUE TITLE
[Bug] Private Playlists not listed - can be accessed via the URL

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1742]
**Describe the bug**
When creating a private playlist it won't appear for the person who created it. Accessing the private list is only possible via the URL (e.g. `playlists/4`). Private Lists can also be accessed by other users.

**To Reproduce**
1. Go to '/playlists'
2. Click on 'Create new Playlist'
3. Set the Playlist to private
4. Create the playlist
5. Go to the main overview '/playlists'
6. Playlist does not appear
7. Access the playlist directly via the URL (can be accessed by anyone, even tho it is set as private)

**Expected behavior**
Private Playlists should appear in the playlist overview for the user.
Private Playlists shouldn't be accessible by other users.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34812414/116007430-08aa5400-a610-11eb-82b6-8ba66212f070.png)
![grafik](https://user-images.githubusercontent.com/34812414/116007459-21b30500-a610-11eb-9b3d-1d7fdf6b7050.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.2.0 
- Laravel Version: Ver. 8.38.0
- PHP Version: php8.0.3
- Database Driver & Version: 8.0.23-0ubuntu0.20.04.1
- Web Server Driver & Version: n/a
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: n/a

**Additional context**
n/a

**Possible Fix?**
n/a

**Comment by apoorvpal01** [comment]
I can work on this. Please assign it to me.

**Comment by HDVinnie** [comment]
> I can work on this. Please assign it to me.

You have been assigned @apoorvpal01

**Comment by apoorvpal01** [comment]
Thanks! I am setting up the project.
