### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Bluesteel533** [HDInnovations/UNIT3D-Community-Edition#1750]
**Describe the bug**
A few demo profiles are created, but the creation of the demo torrents is canceled with the error, see screenshot, there seems to be a timeout of the tmdb apikey causing this error.

**To Reproduce**
1. Go to ssh client
2. give the command php artisan demo:seed 
3. Scroll down and

**Expected behavior**
I have give the command in the mobile ssh Client.

**Screenshots**
![Screenshot_20210505-161843_Mobile SSH](https://user-images.githubusercontent.com/39230411/117448218-c3a2ed80-af3e-11eb-83c5-bc918a15752f.jpg)
![Screenshot_20210505-161835_Mobile SSH](https://user-images.githubusercontent.com/39230411/117448221-c4d41a80-af3e-11eb-9e6a-801831e4c264.jpg)
![Screenshot_20210505-161825_Mobile SSH](https://user-images.githubusercontent.com/39230411/117448224-c6054780-af3e-11eb-91ac-85faba358859.jpg)

**UNIT3D (please complete the following information):**
- UNIT3D Version:5.20
- Laravel Version:8
- PHP Version:8.1
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:Ubuntu 20.4

**Comment by HDVinnie** [comment]
unable to replicate.....demo seeder works fine.
