### ISSUE TITLE
[Bug] API Filtering not working

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#1751]
**Describe the bug**
When trying to send a GET request to the API using for e.g. /filter?tmdb=1 an error 500 is shown:
```
Non-static method Illuminate\Database\Eloquent\Model::newQuery() cannot be called statically {"userId":108,"exception":"[object] (Error(code: 0): Non-static method Illuminate\\Database\\Eloquent\\Model::newQuery() cannot be called statically at /var/www/html/app/Http/Controllers/API/TorrentController.php:363)
```

**To Reproduce**
1. Run: `curl --location --request GET 'https://unit3d.site/api/torrents/filter?tmdb=71116&api_token=APITOKENHERE' --header 'Cookie: __cfduid=d84748ff6d0673169c3088fceb28da0fd1620545103'`
2. Check the Laravel logs and see the error above (Error 500 gets returned)

**Expected behavior**
List of matching entries.

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.2.0
- Laravel Version: 8.40
- PHP Version: 8

**Possible Fix?**
Changing back to `->` will temporarily solve the issue:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/71ff333eb4df0aa71e19478c684aa24ebc6e84ef/app/Http/Controllers/API/TorrentController.php#L363

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/07bb03c9bcffd61942e8579e3d2a7d406ce7fdd7
