### ISSUE TITLE
[Bug] Magnet Links not working

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1783]
**Describe the bug**
Using the magnet link in qBittorrent or Deluge will result in no data transfer. Peers are "finding" each other, but no meta-data about the files in the torrents or the filesize is being exchanged.
The announce status is "OK" and it is listed as being currently downloaded in the profile of the user.

The config in `torrent.php` is set: `'magnet' => 1,`

**To Reproduce**
1. Download any Torrent via Magnet Link
2. Open the Magnet Link in your preferred Torrent Client
3. See Peers seeing each other but no data exchanged

**Expected behavior**
It should load the meta-data and start downloading the torrent.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34812414/120039530-606c1e80-c005-11eb-8ecc-da442a3b2603.png)
![grafik](https://user-images.githubusercontent.com/34812414/120039572-724dc180-c005-11eb-93f5-d13dbe8fe479.png)
![grafik](https://user-images.githubusercontent.com/34812414/120039661-95787100-c005-11eb-937d-e4d0b868dff1.png)
![grafik](https://user-images.githubusercontent.com/34812414/120039750-b5a83000-c005-11eb-8002-ac3cf60e5ea0.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version:  v5.2.0 (Git on Master level)
- Laravel Version: 8.43.0
- PHP Version: php8.0.5
- Database Driver & Version: 8.0.25-0ubuntu0.20.04
- Web Server Driver & Version: n/a
- OS Driver and Version: ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: Windows / Linux
 - Browser: Firefox
 - Version: n/a

**Additional context**
n/a

**Possible Fix?**
n/a

**Comment by HDVinnie** [comment]
this is not a bug with UNIT3D....only rutorrent properly supports magnet links meta data for private tracker torrents.
