### ISSUE TITLE
[Bug] Having { } in the torrent title will lead to 500 Internal Server Error

### ISSUE THREAD

**Issue by Alkl58** [HDInnovations/UNIT3D-Community-Edition#1790]
**Describe the bug**
Uploading a torrent where the title includes `{ }` will lead to 500 Internal Server Error when opening the torrent after upload in the browser.

**To Reproduce**
1. Upload a Torrent
2. Set the torrent name to something like this `somestringabc {abc def}`
3. Open the torrent after upload

**Expected behavior**
No 500 Internal Server Error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/34812414/120565180-c9d89c80-c40c-11eb-89a0-af022b99cbab.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: Ver. 8.43.0
- PHP Version: php8.0.5
- Database Driver & Version: 8.0.25-0ubuntu0.20.04.1
- Web Server Driver & Version: n/a
- OS Driver and Version: Ubuntu 20.04

**Desktop (please complete the following information):**
 - OS: Windows / Linux
 - Browser: Firefox
 - Version: n/a

**Additional context**
n/a

**Possible Fix?**
n/a

**Comment by HDVinnie** [comment]
Whats the actual error?

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/33fc2a312317cb1182e23e02575b11ef0db2492c
