### ISSUE TITLE
Helpdesk System

### ISSUE THREAD

**Issue by brolaugh** [HDInnovations/UNIT3D-Community-Edition#18]
- Laravel Version: N/A
- PHP Version: N/A
- Database Driver & Version: N/A

### Description:
Currently there the bug submission system lets the user set the prioritization, this is never good because the user will almost always choose very high and never low because the issue is of high priority to them.

### Possible Fix:
Change the prioritization system to a category based ticket system. This allows the admins to create their own categories and they can prioritize the problems how they like without the user needing to know what really is high priority, making it harder for a user to misslabel their ticket.

**Comment by HDVinnie** [comment]
I am going to remove the whole simple bug report system thats in place and instead make a full on support/helpdesk system.
