### ISSUE TITLE
Error update v2.3 to v5.3

### ISSUE THREAD

**Issue by savertori** [HDInnovations/UNIT3D-Community-Edition#1800]
**Describe the bug**
We've been going along with development parallel to UNIT3D for a while, but we decided to update and found the image error when updating the database with php artisan migrate --seed. 

Git update is ok!

To Reproduce

   Using the migrate command, we encountered problem in steps: 
2020_05_19_023939_add_type_id_to_torrents_table
https://i.imgur.com/ZXM8Jfn.png
2020_05_26_053632_add_type_id_to_requests_table
2020_06_06_185230_create_resolutions_table
https://i.imgur.com/PmcULRA.png

If I delete these 3, it concludes and encounters the following error: 
https://i.imgur.com/0eZ3BQX.png

Expected behavior
Finish the migrate and stop the 500 error. 

Screenshots
Above, to describe it better. 

UNIT3D (please complete the following information):

    UNIT3D Version: v5.3.0
    Laravel Version: v8.34.0
    PHP Version: php8.0.5
    Database Driver & Version: 8.0.25-0ubuntu0.20.04.1
    Web Server Driver & Version: n/a
    OS Driver and Version: ubuntu 20.04

Desktop (please complete the following information):

    OS: Windows
    Browser: Firefox
    Version: n/a

Additional context
n/a

Possible Fix?
n/a

**Comment by HDVinnie** [comment]
@savertori are you on our Discord? 2.3 to 5.3 is a large jump and 2.3 is extremely EOL. There are a few things I need to ask and a few issues I see your doing.

**Comment by savertori** [comment]
Yes, we've already started talking, updating here.
