### ISSUE TITLE
[Bug] API filters endpoint should allow sort

### ISSUE THREAD

**Issue by seeyabye** [HDInnovations/UNIT3D-Community-Edition#1803]
The current API endpoint is rather inconsistent in terms of returned results

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/2dbadb0b759d6c9aababeafdcecccd105816edf3/app/Http/Controllers/API/TorrentController.php#L53-L56

Returns the latest torrents, but `api/torrents/filter` doesn't do the same.

I would like to propose the possibility of returning sorted results on the `filters` endpoint as well. This would simplify requests because tools build upon the API endpoint will have to decide when to use to `api/torrents` vs `api/torrents/filter`. It would be great if `api/torrents/filter` could return the same information as `api/torrents` when the same parameters are given as `api/torrents`.

**Comment by HDVinnie** [comment]
you want to be able to pass the sort params?

**Comment by seeyabye** [comment]
Yes, that's the goal.

If the filtering endpoint is used, the results returned are in the order of oldest torrents first, whereas the non-filtering endpoint does the opposite (the latest torrents are listed first) because of `latest()`.

I'm not sure if https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/f2c9281c4ee71e7c4003e7e2287d427b481747e9 solves this issue as I don't see the possibility to include sort params?

**Comment by HDVinnie** [comment]
I pushed one more commit.....sorting is now same between `api/torrents` and `api/torrents/filter`. Same as on site Livewire torrent list search system.
