### ISSUE TITLE
[Bug] New Backup manager fails to make a backup

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#1805]
Describe the bug
When you create a backup, an error appears in the log:
[2021-06-18 09:54:55] prod.ERROR: App\Jobs\ProcessBackup has been attempted too many times or run too long. The job may have previously timed out. {"exception":"[object] (Illuminate\\Queue\\MaxAttemptsExceededException(code: 0): App\\Jobs\\ProcessBackup has been attempted too many times or run too long. The job may have previously timed out. at /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:736)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(490): Illuminate\\Queue\\Worker->maxAttemptsExceededException()
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(404): Illuminate\\Queue\\Worker->markJobAsFailedIfAlreadyExceedsMaxAttempts()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(364): Illuminate\\Queue\\Worker->process()
#3 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Worker.php(158): Illuminate\\Queue\\Worker->runJob()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(117): Illuminate\\Queue\\Worker->daemon()
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php(101): Illuminate\\Queue\\Console\\WorkCommand->runWorker()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Illuminate\\Queue\\Console\\WorkCommand->handle()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Util.php(40): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure()
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(37): Illuminate\\Container\\BoundMethod::callBoundMethod()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(614): Illuminate\\Container\\BoundMethod::call()
#11 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(136): Illuminate\\Container\\Container->call()
#12 /var/www/html/vendor/symfony/console/Command/Command.php(256): Illuminate\\Console\\Command->execute()
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Command.php(121): Symfony\\Component\\Console\\Command\\Command->run()
#14 /var/www/html/vendor/symfony/console/Application.php(971): Illuminate\\Console\\Command->run()
#15 /var/www/html/vendor/symfony/console/Application.php(290): Symfony\\Component\\Console\\Application->doRunCommand()
#16 /var/www/html/vendor/symfony/console/Application.php(166): Symfony\\Component\\Console\\Application->doRun()
#17 /var/www/html/vendor/laravel/framework/src/Illuminate/Console/Application.php(92): Symfony\\Component\\Console\\Application->run()
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(129): Illuminate\\Console\\Application->run()
#19 /var/www/html/artisan(37): Illuminate\\Foundation\\Console\\Kernel->handle()
#20 {main}

To Reproduce

Go to Dashboard / Backups
Click on Create Full Backup
See error in logs
UNIT3D (please complete the following information):
UNIT3D Version: v5.3.0
Laravel Version: 8.43.0
PHP Version: 8.0.3
Database Driver & Version: 8.2.25
Web Server Driver & Version: Ngnix
OS Driver and Version: Ubuntu server 20.04.1

**Comment by HDVinnie** [comment]
@espiman Are you still experiencing this issue? I am unable to replicate it both on the demo site and a production site using the latest UNIT3D.
