### ISSUE TITLE
[Bug] Doesn't hide uploader name in peer list and history when uploaded as anonymous

### ISSUE THREAD

**Issue by agabob** [HDInnovations/UNIT3D-Community-Edition#1872]
**Describe the bug**
I'm not sure this is a bug or intended.
But I think that uploader want to hide their name in peer list and history page when uploaded as anonymous.

**To Reproduce**
1. User A set privacy setting to lowest
2. User A upload B as anonymous
3. Other users can't see uploader of B in torrent list
4. But other users can see A in peer list and history of B
5. Other users can guess who is a uploader of B

**Expected behavior**
Hide uploader name in peer list and history if it was uploaded as anonymous

**Comment by clandestine8** [comment]
This I believe is intended behavior as the Peer Table does not confirm or deny that a user is the uploader, it just shows the connected users. 

If a user wants to appear anonymous in this list, each individual user can controller their Privacy Settings to obscure their peer activity.

/users/[USER]/settings/privacy

`Allow users to see you in the torrent peer history table.`  `yes | no`

![image](https://user-images.githubusercontent.com/5833609/129479186-533ddf83-a59b-42d3-aabe-006ea42223db.png)
