### ISSUE TITLE
Error during Install

### ISSUE THREAD

**Issue by Argon-D** [HDInnovations/UNIT3D-Community-Edition#1877]
Hello guys I am trying to install UNIT3D on Ubuntu machine and I got this error:

https://ibb.co/p1z59YJ

If I manually try to install this lib i got this error 

sudo apt-get install libpng12-0
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libpng12-0 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

I am stuck :( , anyone have a solution ? 
Thanks in advance

**Comment by HDVinnie** [comment]
what version of ubuntu?

**Comment by Argon-D** [comment]
I've installed Ubuntu 20.04.2 LTS (Arm64) I am try to install on a rasp 4

**Comment by Argon-D** [comment]
anyone have any ideas how to fix? :(

**Comment by HDVinnie** [comment]
Can’t help you on a rasp 4. If trying to install for dev purposes just buy a cheap 4GB Ram digital ocean droplet and a domain. Or learn homestead and install locally without installer.

**Comment by Argon-D** [comment]
Gotcha ! Thanks

**Comment by clandestine8** [comment]
Looks to me like the libpng-12-0 library is not compiled for ARM since it is a legacy library.
