### ISSUE TITLE
[Bug] Users can see open tickets from other users

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#1890]
**Describe the bug**
When in the view /tickets/index, users can ticket the checkbox to "Show Closed Tickets" and they will be able to see other Open Tickets not created nor assigned to them.

**To Reproduce**
1. Go to 'unit3d.site/tickets'
2. Click on 'Show Closed Tickets'
3. See tickets you should not get listed there

**Expected behavior**
Only show tickets created by this user (when not modo)

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.3.0

**Additional context**

**Possible Fix?**
Remove line:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/2619befb99ad6bdbdc8fd2f2c92b1a55fac740a3/app/Http/Livewire/TicketSearch.php#L74

**Comment by Alkl58** [comment]
This should solve the issue.
![grafik](https://user-images.githubusercontent.com/34812414/132312581-9760d00c-0b03-4326-a99f-14c81fc0b8cb.png)
