### ISSUE TITLE
[BUG] Non-Livewire Redirects dont show Success/Error Message

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D-Community-Edition#1906]
<div type='discussions-op-text'>

<sup>Originally posted by **Obi-Wana** September 19, 2021</sup>
Buttons like the "Quick Comment" who are not yet moved to livewire will no longer show a "success" or "error" message after pressing it. 

For Example, go to unit3d.site.
Open any torrent and hit the "Report" button. 
The page will refresh, but no confirmation message will be shown on the top right of your screen.

Not sure if it makes sense to fix it, or just migrate those buttons to livewire where possible.</div>

**Comment by Obi-Wana** [comment]
Thx for the quick fix!
