### ISSUE TITLE
[Bug] laravel-echo-server not running/starting

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#1937]
**Describe the bug**
After a clean installation with the installer, the laravel echo server does not seem to be running. the chat box does not update correctly.
when I enter the command 'laravel-echo-server start' in the shell, the following error message appears:
Error: The config file could not be found 

**To Reproduce**
1. Go to 'shell'
2. try to start or force start laravel-echoo-server
3. See error

**Expected behavior**
i expect the the echo-server running.

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.3 (latest)
- Laravel Version: Currently Running php8.0.11
- PHP Version: Currently Running php8.0.11
- Database Driver & Version: Currently Running 8.0.26-0ubuntu0.20.04.3
- Web Server Driver & Version: Ubuntu 20.04 LTS
S Driver and Version:

**Screenshots**

![install](https://user-images.githubusercontent.com/67836615/135864343-fe4bff03-1fc9-43dd-9e6e-85ba9b0f8695.jpg)

![laravel-echo-server-fail](https://user-images.githubusercontent.com/67836615/135864393-0452c7f8-66c0-4342-b616-a201d63a7a72.jpg)

**Comment by HDVinnie** [comment]
When you’re on the homepage with the chat box open up your browser console and see if there is any errors.

also Are you accessing your site with or without the WWW in the address bar

**Comment by kREATUr67** [comment]
it happens both without and with 'www'. after the post i see the post in the console, then i see
GEThttps://jme-reunit3d.de:8443/socket.io/?EIO=3&transport=polling&t=NnBz2yk.
Then:
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://jme-reunit3d.de:8443/socket.io/?EIO=3&transport=polling&t=NnBw51E. (Grund: CORS-Anfrage schlug fehl).

[https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSDidNotSucceed](url)

**Comment by kREATUr67** [comment]
found out laravel-echo-server running
![51550372633_86b4cf1304_o](https://user-images.githubusercontent.com/67836615/135892723-bcf05d92-fc06-4005-abc3-60158be20082.png)

that was my fault, cause i tried to start or restart it from false folder.
also there is a file called 'laravel-echo-server.json' . 
Unfortunately the chat box only updates when I click on the button 'General' on the top of the box, but not when i enter something new.

**Comment by kREATUr67** [comment]
may be the issue has a false subject line now, must be somethink like 'chat box does not update itself'

**Comment by HDVinnie** [comment]
So if the server is running but not updating realtime correct? 

1) Are you running CloudFlare?
2) Run `sudo nano /etc/supervisor/conf.d/unit3d.conf` and try changing the user for `[program:unit3d-chat-server]` to `root` instead of `www-data` and then restart the server. 
```
php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload 
```

This will tell us if you have a permissions issue or not.

**Comment by kREATUr67** [comment]
1. i am not running CF
2. ok changed user for `[program:unit3d-chat-server] to root` , then did `php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload`
 
3. ![51552645706_5f87532a56_o](https://user-images.githubusercontent.com/67836615/135978680-1495046f-22a6-49e2-8abf-63cfad50b88e.png)
4. still does´nt update

**Comment by kREATUr67** [comment]
Meanwhile i think something with the older one server may be ram something other is not ok.
i think every install other errors the code itself and the install routine
couldn´t be the problem.
Today did a fresh install again. then chat box updating realtime. 
but then as i did 1st upload, the downloaded meta files after upload didn´t show in rutorrent.
so i now do a last try with this server, when doesn´t work , 
i order a new one. 
the task here i think can be closed or deleted.
Sry Vinnie that I used up all of your time, but thanks a lot for the help.

**Comment by kREATUr67** [comment]
so now meanwhile 6th install - i think - chat box also updates immediately and uploads will be recognized when upping into the client.

**Comment by HDVinnie** [comment]
Very strange. Maybe something with your provider. Glad it’s working for you as I couldn’t replicate it on fresh installs even for demo site.

**Comment by kREATUr67** [comment]
But again thx a lot for your help, from github i did now a lil´monthly support for you with the user kREATUr67 as long as i can. you will not find this nick in your channel. in discord i have another nickname. only 2 dollars a month, but as yoiu said, if some people do, it cxan help. may be write us
