### ISSUE TITLE
[Bug] Fresh install failed

### ISSUE THREAD

**Issue by jobber2955** [HDInnovations/UNIT3D-Community-Edition#1947]
**Describe the bug**
Using the install instruction on Ubuntu20.04, running "sudo ./install.sh", after it shows "Setting UTF8", an error occured
`E: The repository 'http://ppa.launchpad.net/nginx/development/ubuntu focal Release' does not have a Release file.`
and then
`Error: Adding ppa:linuxuprising/libpng12 Failed! 
 Please try re-running the script via 'sudo ./install.sh'`
i've tried using proxy/switch to root user/re-install on a fresh installed vm, but this error is still there
**To Reproduce**
1. Follow the install instruction, execute the install.sh script
2. After the script setting UTF8, the error occurs.

**Expected behavior**
UNIT3D can be successfully installed

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/17498767/136825363-0ff05421-8fda-4e74-bf89-e4992471ccb6.jpg)

**UNIT3D (please complete the following information):**
- UNIT3D Version: Not Installed
- Laravel Version: Not Installed
- PHP Version: 8.0
- Database Driver & Version: Mysql 8.0.24
- Web Server Driver & Version: Nginx 1.18
- OS Driver and Version: WAT is this

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Chrome
 - Version: Latest

**Additional context**
Nothing

**Possible Fix?**
It seems to be a ppa respority issue, but i'm not sure about this

**Comment by HDVinnie** [comment]
@jobber2955 Im thinking your hosts ubuntu image maybe modified for out of date. Run `apt-get update && apt-get upgrade` first then run the installer.

**Comment by HDVinnie** [comment]
@jobber2955 Weird im not able to replicate. What happens if you run `sudo add-apt-repository ppa:linuxuprising/libpng12`

**Comment by jobber2955** [comment]
@HDVinni
<img width="907" alt="screenshot" src="https://user-images.githubusercontent.com/17498767/136897618-982b5f77-b7b4-44fb-b013-4011a56d7e59.png">
e

**Comment by HDVinnie** [comment]
You ran `sudo add-apt-repository ppa:linuxuprising/libpng1` and not `sudo add-apt-repository ppa:linuxuprising/libpng12`

**Comment by jobber2955** [comment]
Waiting for your reply, If there's nothing else, i will close this issue.

**Comment by jobber2955** [comment]
@HDVinnie OKay then this may be my netword/location issue. Im in china and can not use foreign source/repo, this may be a networ issue than repo issue, thanks for answering, im closing this issue
