### ISSUE TITLE
[Bug] Request reseed returns error when a user in the history table has been pruned

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#1959]
**Describe the bug**
When a user in the history table gets pruned, his Username gets replaced with "System" in the torrent's history view.
When a user does now request a reseed, he gets an error 500.
Log says:
```
Call to a member function notify() on null at app/Http/Controllers/TorrentController.php
```

**To Reproduce**
1. Search a torrent with a user named "System" in the History list.
2. Hit "Request Reseed"
3. See error

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.3.0

**Possible Fix?**
PR will follow.

**Comment by HDVinnie** [comment]
https://github.com/michaeldyrynda/laravel-cascade-soft-deletes
