### ISSUE TITLE
[Bug] Attempt to read property "rating" on null (View: /var/www/html/resources/views/livewire/torrent-list-search.blade.php) 

### ISSUE THREAD

**Issue by maxpayneovh** [HDInnovations/UNIT3D-Community-Edition#1980]
Attempt to read property "rating" on null (View: /var/www/html/resources/views/livewire/torrent-list-search.blade.php) (View: /var/www/html/resources/views/livewire/torrent-list-search.blade.php)

**Comment by fmohican** [comment]
@HDVinnie would be better if we hide entire `span` if meta doesn't have `rating` or `vote_average`?

**Comment by HDVinnie** [comment]
@fmohican I was going to push a fix but currently working in another branch. To keep is like everywhere else just make it like so.

```
@if ($torrent->category->game_meta)
    <span class='badge-extra'>
        <img src="{{ url('img/igdb.png') }}" alt="igdb_id" style="margin-left: -5px;" width="24px" height="24px"> {{ $torrent->igdb }}
	<br>
	<span class="{{ \rating_color(round($meta->rating) ?? 'text-white') }}"><i class="{{ config('other.font-awesome') }} fa-star-half-alt"></i> {{ round($meta->rating ?? 0) }}/100 </span>
    </span>
@endif
```

**Comment by fmohican** [comment]
Nice, then we will wait till you're done with others. I will stash my commit.

**Comment by HDVinnie** [comment]
You can make the PR to close it
