### ISSUE TITLE
[Bug] Notifications blip but when i click on the bell there is none

### ISSUE THREAD

**Issue by FuNFooKaS** [HDInnovations/UNIT3D-Community-Edition#1982]
**Describe the bug**
it says i have  notification but when i click on the bell there is none

**To Reproduce**

1. Click on notification bell

**Expected behavior**
i should see my notifications

**Screenshots**
```
$user->unreadNotifications
<warning>PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=145 in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 82</warning>
=> Illuminate\Notifications\DatabaseNotificationCollection {#5346
     all: [
       Illuminate\Notifications\DatabaseNotification {#5203
         id: "7b2a4e16-ffa0-44a8-8e9f-8aeb77f31e35",
         type: "App\Notifications\NewThank",
         notifiable_id: 3,
         notifiable_type: "App\Models\User",
         data: "{"title":"Piper Has Thanked You For An Uploaded Torrent","body":"Piper has left you a thanks on Uploaded Torrent Fauci 2021 1080p DSNP WEBRip DD 5.1 x264-EVO","url":"\/torrents\/18"}",
         read_at: null,
         created_at: "2021-10-30 19:49:55",
         updated_at: "2021-10-30 19:49:55",
       },
     ],
   }
```

**UNIT3D (please complete the following information):**
- UNIT3D Version:Currently Running UNIT3D Community Edition (Nex-Gen Torrent Tracker) v5.3.0
- Laravel Version:Ver. 8.67.0
- PHP Version:php8.0.12
- Database Driver & Version:8.0.27-0ubuntu0.20.04.1
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:win 7
 - Browser:chrome
 - Version:Version 95.0.4638.54 (Official Build) (64-bit)

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by fmohican** [comment]
Hello,
This (may) happens cuz of mariadb, try to increase packet size of mariadb.

Would you like to check my.cnf? Please should look like :
```
[client]
port=3306
socket=/var/run/mysqld/mysqld.sock

[mysqld_safe]
socket=/var/run/mysqld/mysqld.sock

[mysqld]
user=mysql
pid-file=/var/run/mysqld/mysqld.pid
socket=/var/run/mysqld/mysqld.sock
port=3306
basedir=/usr
datadir=/var/lib/mysql
tmpdir=/tmp
lc-messages-dir=/usr/share/mysql
log_error=/var/log/mysql/error.log

symbolic-links=0

skip-external-locking
key_buffer_size = 256M
max_allowed_packet = 32M
table_open_cache = 256
sort_buffer_size = 1M
read_buffer_size = 1M
read_rnd_buffer_size = 4M
myisam_sort_buffer_size = 64M
thread_cache_size = 8

#innodb_use_native_aio = 0
innodb_file_per_table

max_connections=200
max_user_connections=50
wait_timeout=10
interactive_timeout=50
long_query_time=5
```

The key component is `max_allowed_packet = 32M`.

**Comment by FuNFooKaS** [comment]
i changed it to 100 restarted mysql see same error i see no notifications

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/1982#issuecomment-957132151 would not be related to notifications. It was for the `<warning>PHP Warning:  Packets out of order. Expected 1 received 0. Packet size=145 in /var/www/html/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php on line 82</warning>` in your console.

 However im not able to replicate this notifications bug. Anyone else experiencing this? I'll keep testing for now.

**Comment by HDVinnie** [comment]
This was invalid and due to the users browser blocking JS
