### ISSUE TITLE
[Bug] URL ending in "png" will throw NGINX 404 not found

### ISSUE THREAD

**Issue by crKtv** [HDInnovations/UNIT3D-Community-Edition#1999]
**Describe the bug**
If a URL ends with "png" it will forward to NGINX 404 Not Found error.

**To Reproduce**
1. Have a user named "qwertypng", "anythingpng", you get the point. I changed an existing user of unit3d.site to "jpng" 
2. Go to is profile at https://unit3d.site/users/jpng (If it throws the No query results for model [App\Models\User] the user is not available because of the reset and needs to be created again)
3. See error

**Expected behavior**
See is profile

**UNIT3D (please complete the following information):**
- UNIT3D Version: Whatever version is on the test site
- Laravel Version: Whatever version is on the test site
- PHP Version: Whatever version is on the test site
- Database Driver & Version: Whatever version is on the test site
- Web Server Driver & Version: Whatever version is on the test site
- OS Driver and Version: Whatever version is on the test site

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 95.0.4638.69

**Comment by HDVinnie** [comment]
This is something that needs to be adjusted in the NGINX config

**Comment by clandestine8** [comment]
This isn't actually related to unit3d since it is the nginx rewrite rules that would cause this. It could be a bug with the automated installer but could not be fixed in the Unit3d code base.

**Comment by HDVinnie** [comment]
Indeed it is a fault in the install Nginx config stub. I’m not around to fix it right now but we will need to push a patch to the installer and write some directions here as to what to change for ppl already using Unit3d

**Comment by crKtv** [comment]
Should I open the issue in the automated installer repo then?

**Comment by HDVinnie** [comment]
closed in https://github.com/poppabear8883/UNIT3D-INSTALLER/commit/0dd36bd11cb892cb9736edbd8a6dd4a99ce523e4

you can fix your current instance by running `nano /etc/nginx/sites-available/default` and making same changes you see in commit above. Save and exit. Then restart NGINX. `sudo systemctl reload nginx`
