### ISSUE TITLE
[Bug] Trailer error #2001

### ISSUE THREAD

**Issue by maxpayneovh** [HDInnovations/UNIT3D-Community-Edition#2002]
prod.ERROR: Undefined array key 0 {"userId":1,"exception":"[object] (ErrorException(code: 0): Undefined array key 0 at /var/www/html/vendor/laravel/framework/src/Illuminate/Collections/Collection.php:1580)

**Comment by HDVinnie** [comment]
Working fine https://unit3d.site/torrents/425 ..... provide a game id

**Comment by maxpayneovh** [comment]
134503
