### ISSUE TITLE
[Bug] Changing the required seedtime

### ISSUE THREAD

**Issue by LokiThor2021** [HDInnovations/UNIT3D-Community-Edition#2007]
**Describe the bug**
Changing the required seedtime value results in users getting a h&r.  

**To Reproduce**
1. Edit this line:  https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/aed196c542258b9a22e644068dbd2826fc47c4b5/config/hitrun.php#L36
2. Wait of the Cron job to run
3. Users that have torrents with  seedtime lower then that new required will start to get h&r

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: custom
- Laravel Version: 8
- PHP Version: 8
- Database Driver & Version: MySQL 8
- Web Server Driver & Version: nginx 
- OS Driver and Version: Redhat 8

**Desktop (please complete the following information):**
  Not relevant to the issue.

**Additional context**

**Possible Fix?**
Store the required seedtime in the db.

**Comment by savertori** [comment]
my suggestion for this is immune = 1 for everyone in the history.
