### ISSUE TITLE
[SUGGESTION] Dockerize for easy dev and production deployment

### ISSUE THREAD

**Issue by R3D4CTED** [HDInnovations/UNIT3D-Community-Edition#2021]
This project could be dockerized for easier deployment and development.

**Comment by HDVinnie** [comment]
The issue tracker is for BUGS only. Use the discussions section.

FYI already open here
https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/1327

I dont use docker so cannot make or support a official docker image.
