### ISSUE TITLE
Upload is not changing after enabling freeleech and double upload. [Bug]

### ISSUE THREAD

**Issue by MudabbirulSaad** [HDInnovations/UNIT3D-Community-Edition#2058]
**Describe the bug**
Upload is not changing after enabling freeleech and double upload.

**To Reproduce**
1. make 'freeleech' => true, 'doubleup' => true,'
2. when you leech anything, download will be counted.
3. See seeder's upload is not counting.

**Expected behavior**
The upload should be changed as usual. However, I've enabled double upload, so it should count double.

**Screenshots**
when freeleech and doubleup is 'true'
![image](https://user-images.githubusercontent.com/71183979/147279592-5c58755c-9a14-4f2d-8c7d-41ddcee316c0.png)

when freeleech is 'false' and double upload is 'true'.
![image](https://user-images.githubusercontent.com/71183979/147281647-8d2613cc-7c7e-4ed8-9ea1-b74a20238249.png)

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: *
- PHP Version: 8.0
- Database Driver & Version: 8.0.27-0ubuntu0.20.04.1 (Ubuntu)
- Web Server Driver & Version: nginx/1.18.0 (Ubuntu)
- OS Driver and Version: Ubuntu 20.04 LTS

**Desktop (please complete the following information):**
 - OS: all
 - Browser: all
 - Version: all

**Additional context**
Upload is not changing after enabling freeleech and double upload.

**Possible Fix?**
Don't know.

**Comment by HDVinnie** [comment]
Did you clear you config cache after making changes? Are you using OPCache?

**Comment by HDVinnie** [comment]
Your also looking at the wrong view...you need to look at history not peers.

**Comment by MudabbirulSaad** [comment]
I've cleared all cache from "dashboard/commands" 

Uploaded almost 242GB from a user but it's not showing on his info. I leeched his torrent but my download is counting but his upload is not raising.
![image](https://user-images.githubusercontent.com/71183979/147318142-37a0627c-9a9d-4005-a9ad-fb60b1319c06.png)

After turn off freeleech, his upload is raising.
![image](https://user-images.githubusercontent.com/71183979/147318203-355301e9-21d6-4d13-a1c4-504dcc958bc4.png)

**Comment by HDVinnie** [comment]
Your post makes no sense. In your images your download is NOT counting. You say it is yet the credited download shows 0. You say `Uploaded almost 242GB from a user` yet there is no way thats possible on either of the images you posted. 

Im not able to replicate this. That being said when you enable Global FL or Global DU you MUST run `php artisan clear:all_cache && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload`

If your using OPCache you need to clear that as well so instead run
`php artisan clear:all_cache && sudo systemctl reload php8.1-fpm && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload`
