### ISSUE TITLE
[Bug] No peers returned error when stop or pause torrent

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#2061]
**Describe the bug**
When stop or pause torrent in client, the status tracker is Tracker: [No peers returned]

**To Reproduce**
1. Go to torrent client
2. Click on stop or pause any torrent
3. See error

UNIT3D Version: 5.3.0 with latest changes
Laravel Version: 8.73.2
PHP Version: 8.1.0
Database Driver & Version: 8.0.27-0ubuntu0.20.04.1
Web Server Driver & Version: ngnix
OS Driver and Version: Ubuntu 20.4.3

**Comment by HDVinnie** [comment]
This is normal behavior and not a bug. There is no reason too send peers info to client on a stopped event.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/0a9135e3c80721a7f3e1fbb78a50004ca05edd0c/app/Http/Controllers/AnnounceController.php#L453-L454

**Comment by espiman** [comment]
> 

Hi HDVinnie, expected behavior would be like the first torrent in my screenshot, but not like the second, with a red x on the client.

![image](https://user-images.githubusercontent.com/17177009/147445578-4edb2b62-9aa3-4849-a815-a77277119a6b.png)

Thanks.

**Comment by HDVinnie** [comment]
What client as this does not happen with BitTorrent or Rtorrent

**Comment by espiman** [comment]
rtorrent 0.9.8/0.13.8

thanks

**Comment by HDVinnie** [comment]
@espiman try that ^

**Comment by espiman** [comment]
Thank you very much, it is perfect now.

Regards.
