### ISSUE TITLE
[Bug] Automated Installer

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2082]
**Describe the bug**
Error when using automated installer

**To Reproduce**

1. fresh installed server Ubuntu-2004-focal-64-minimal (Hetzner)
2. startet the install, short started & then shows:  
```
Preparing Environment For The Installer ...
=============================================

 Setting UTF8 ...
 OK

 Adding PPA Repositories ...
 OK

 Updating Packages ...
 OK

 Installing PHP ...
Extracting templates from packages: 100%
 OK

 Installing Composer ...
 OK

 Adding Installer Packages ...
 Error: Adding Installer Packages Failed!
 Please try re-running the script via 'sudo ./install.sh'
root@Ubuntu-2004-focal-64-minimal-hwe ~/installer
```

trying re-running the script via 'sudo ./install.sh' shows same error.

can you please proof what generates this error.

Wfg 

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Dupe https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/2079

**Comment by HDVinnie** [comment]
BTW @kREATUr67 this is now fixed
