### ISSUE TITLE
[Bug]laravel-echo-server not running/starting after install

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2083]
**Describe the bug**
Hello,  the install now ends without any error message: [OK] Done!

But chatbox does not automatically refresh, only with click on general chat-tab.

but ... laravel-echo-server runs:

`root@Ubuntu-2004-focal-64-minimal-hwe /var/www/html # Error: There is already a server running! Use the option '--force' to stop it and start another one.
`
did that with --force option, server shows running - no refresh.

no using CloudFlare. 

changed user in sudo nano /etc/supervisor/conf.d/unit3d.conf to root, restartet the server 
did then
`php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload`
result:
`Broadcasting queue restart signal.
No config updates to processes
Restarted supervisord`

still didn´t refresh.
![51831682068_d9f9dac73e_o](https://user-images.githubusercontent.com/67836615/150307375-9f6b7d1f-cfe1-4c6b-bd6d-49e26b85ebfd.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: v5.3.0
- Laravel Version: for all below - versions installed due automated installer
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Check your browser console for errors

**Comment by kREATUr67** [comment]
the browser console in chrome shows up following error:

VM1234:1 Mixed Content: The page at 'https://ourdomain.de/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://ourdomain.de:8443/socket.io/?EIO=3&transport=polling&t=NvtWbJO'. This request has been blocked; the content must be served over HTTPS.

i´ve tested now again in firefox and opera, there is not such kind of error.

**Comment by HDVinnie** [comment]
`nano .env`
Check your `APP_URL` and `MIX_ECHO_ADDRESS` and make sure they have https.

If they dont then add it and then clear cache `php artisan optimize` and then recompile `npx mix -p`

**Comment by kREATUr67** [comment]
they "both" were on http, did as you explained, now error in chrome is gone, refresh also works now in chrome.
thank you for your help.

**Comment by bitappend** [comment]
I hate to have to reopen this case.
Im seeing this too however .env was set for https. figuring that its possible it wasn't always https because the install was months ago i proceeded with:
php artisan optimize
and 
npx mix -p
with sudo of course. I then cleared all cache on the command page.
did i miss something or is this a new bug?

**Comment by HDVinnie** [comment]
> I hate to have to reopen this case.
> Im seeing this too however .env was set for https. figuring that its possible it wasn't always https because the install was months ago i proceeded with:
> php artisan optimize
> and
> npx mix -p
> with sudo of course. I then cleared all cache on the command page.
> did i miss something or is this a new bug?

not able to replicate....check browser console and read this issue like `php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload` and browser console.

**Comment by bitappend** [comment]
GET https://xxxxcensoredxxxx:8443/socket.io/?EIO=3&transport=polling&t=OpJ8ayH net::ERR_CONNECTION_REFUSED
f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
XMLHttpRequest.send (async)
f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
XMLHttpRequest.send (async)
f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
XMLHttpRequest.send (async)
f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
setTimeout (async)
hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
XMLHttpRequest.send (async)
f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
(anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 
        
        
        
        def looks ssl related

**Comment by HDVinnie** [comment]
> GET https://xxxxcensoredxxxx:8443/socket.io/?EIO=3&transport=polling&t=OpJ8ayH net::ERR_CONNECTION_REFUSED f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 XMLHttpRequest.send (async) f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 XMLHttpRequest.send (async) f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 XMLHttpRequest.send (async) f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) l.reconnect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 e.emit @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f.onError @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 setTimeout (async) hasXDR.e.onreadystatechange @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 XMLHttpRequest.send (async) f.create @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 f @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.request @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doPoll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.poll @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.doOpen @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 o.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h.open @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 h @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 l.open.l.connect @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 (anonymous) @ chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2 chat.js?id=f20ae2595b69bc1313bf20bf381a4e00:2
> 
> ```
>     def looks ssl related
> ```

you can send me an invite to `unit3d@protonmail.com` and I can look when I have a chance as im not able to replicate any chat issues in unit3d.

**Comment by bitappend** [comment]
invite sent
