### ISSUE TITLE
[Bug] permission error during file backup or full backup

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2084]
**Describe the bug**

After last issue, i now checked backup function, of this fresh install.
db backup running well, but when trying full backup oder files backup 
in laravel log theree will be no backup then,

Laravel Log shows: 
`ZipArchive::close(): Can't open file: Permission denied {"exception":"[object] (ErrorException(code: 0): ZipArchive::close(): Can't open file: Permission denied at /var/www/html/vendor/spatie/laravel-backup/src/Tasks/Backup/Zip.php:87)`

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: V5.3.0
- Laravel Version:
- PHP Version: 8.1
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Try running the following to make sure your permissions are not messed up.
```
sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' +
```

**Comment by kREATUr67** [comment]
Hello Vinnie,
that was apparently the cause. instant function full backup and file backup. 
you are as all know the best.

one small question. how did this error come about, is it plausible that something like this can happen when using automatic installers?
