### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2085]
**Describe the bug**
UInfortunate, now after clearing both issues #2083 & #2084, a new issue occured.
if i now call the function npx mix -p or npx mix watch, i get the following error message:

`root@Ubuntu-2004-focal-64-minimal-hwe /var/www/html # npx mix -p`
`npx: installed 1 in 0.629s`
`command not found: mix`

**To Reproduce**
1. Go to 'command line on server' folder /var/www/html and run # npx mix -p
2. See error

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
`sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npx mix -p`

**Comment by kREATUr67** [comment]
Thank you very much, is working now again, mix was found now

![51834233620_e6080e9350_o](https://user-images.githubusercontent.com/67836615/150519298-0f103ad0-03f4-42a7-8ea3-7839530fb0f1.png)
