### ISSUE TITLE
No Reseed button

### ISSUE THREAD

**Issue by andriuhaynes** [HDInnovations/UNIT3D-Community-Edition#2086]
**Describe the bug**
No reseed button in torrent blade

**To Reproduce**
1. Look for a torrent with less than 2 seeders
2. There is not option to request a reseed

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 5.3.0
- Laravel Version: 8.73.2
- PHP Version: 8.0.14
- Database Driver & Version: 
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Not how it works...the user must be actively leeching the torrent to seed the button
