### ISSUE TITLE
[Bug]local installation in vm, error 419 | PAGE EXPIRED after login

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2088]
**Describe the bug**
Hello Vinnie, sry for having question again.
Yesterday I set up a local installation in virtualbox under ubuntu 20.04 and installed it without "important" errors so as not to always have to develop on the server.

after no errors except with a newly set up gmail address i thought all went fine and will work now.
FQDN for Server vm1.jme included in host file, everything looked fine.
but after login i keep getting error 
`419 | PAGE EXPIRED`

did I miss something important?

is it perhaps the case that with local install something specific has to be set?

`
installation result cleaned up:`

`https://0bin.net/paste/w2aSnBIv#tKFJfs5n6NStx2b4Z9cB7ebCS78NCrFJL3hqPjHdZmn`

**To Reproduce**

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: version 5.3.0
- Laravel Version: actual
- PHP Version: actual
- Database Driver & Version: actual
- Web Server Driver & Version: actual
- OS Driver and Version: actual

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04.3 in virtualbox vm
 - Browser: chrome & firefox
 - Version: actual

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by kREATUr67** [comment]
I think i found out that SESSION_SECURE_COOKIE=true must be false using http.

**Comment by kREATUr67** [comment]
In chrome i can login after changing SESSION_SECURE_COOKIE to false. but in firefox it still doesn´t show style on login, and after try to login see blank page. shows error in console: 15:28:12.067 This error page has no error code in its security info aboutNetError.js:569:13

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition#-%EF%B8%8F-installation
