### ISSUE TITLE
[Bug] upgrading to 6

### ISSUE THREAD

**Issue by enrico1203** [HDInnovations/UNIT3D-Community-Edition#2107]
**Describe the bug**

In ClassLoader.php line 571:

  include(/var/www/html/vendor/composer/../nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php)
  : Failed to open stream: No such file or directory

git checkout origin/master -- resources/views/vendor/log-viewer/bootstrap-4/_master.blade.php
[============================] (Done!)error: pathspec 'resources/views/vendor/log-viewer/bootstrap-4/_master.blade.php' did not match any file(s) known to git

 Update resources/views/vendor/log-viewer/bootstrap-4/dashboard.blade.php (yes/no) [yes]:
 > yes

git checkout origin/master -- resources/views/vendor/log-viewer/bootstrap-4/dashboard.blade.php
[============================] (Done!)error: pathspec 'resources/views/vendor/log-viewer/bootstrap-4/dashboard.blade.php' did not match any file(s) known to git

 Update resources/views/vendor/log-viewer/bootstrap-4/logs.blade.php (yes/no) [yes]:
 > yes

root@vmi790697:/var/www/html#
[============================] (Done!)error: pathspec 'resources/views/vendor/log-viewer/bootstrap-4/logs.blade.php' did not match any file(s) known to git

 Update resources/views/vendor/log-viewer/bootstrap-4/show.blade.php (yes/no) [yes]:
 > yes

git checkout origin/master -- resources/views/vendor/log-viewer/bootstrap-4/show.blade.php
[============================] (Done!)error: pathspec 'resources/views/vendor/log-viewer/bootstrap-4/show.blade.php' did not match any file(s) known to git

tracker is offline now

**Comment by Obi-Wana** [comment]
Apparently, the logviewer has been removed. You can delete the files located at:
resources/views/vendor/log-viewer

**Comment by HDVinnie** [comment]
Mate where did the updater end?

**Comment by enrico1203** [comment]
Here: 
In ClassLoader.php line 571:

include(/var/www/html/vendor/composer/../nunomaduro/collision/src/Adapters/Laravel/IgnitionSolutionsRepository.php)
: Failed to open stream: No such file or directory

**Comment by HDVinnie** [comment]
```
php artisan optimize:clear && composer self-update && composer update && composer dump-autoload -o && sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npx mix -p && sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' + && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo service nginx restart && sudo systemctl restart php8.1-fpm
```

**Comment by enrico1203** [comment]
all completed but still Now i have Error 503: Service Unavailable!

**Comment by HDVinnie** [comment]
`php artisan up`

**Comment by enrico1203** [comment]
Thanks. all good now after php artisan up
