### ISSUE TITLE
[Bug]Bug fresh install during Cloning Source Files

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2109]
**Describe the bug**
in step  UNIT3D Settings and Configuration - cloning source files following error occured:

![51872386794_dc433f870e_o](https://user-images.githubusercontent.com/67836615/153272058-c7d6a049-3e5d-4d16-b031-f89a555f6bd5.png)

did a fresh install on fresh installed Ubuntu 20.04.3 LTS minimal
only installed git 1st, then run new install and saw this error

A clear and concise description of of what the bug is.

**To Reproduce**
1. starting fresh install after new server install
2. 

**Expected behavior**

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version:
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
server.php file was removed in Laravel 9

Have updated the installer. 
https://github.com/poppabear8883/UNIT3D-INSTALLER/commit/5f292dd57197c7da1280a541fa984c984df1e013
