### ISSUE TITLE
[Bug] backup also inserts the backup folder

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#2114]
**Describe the bug**
Backup also inserts the backup folder (with all the old) and the file created is enormous

**To Reproduce**
Backup

**Expected behavior**
The backup folder should not be included in the backup

**UNIT3D (please complete the following information):**

OS Linux 
PHP 8.1.2
DATABASE 8.0.28-0ubuntu0.20.04.3
LARAVEL Ver. 9.0.1

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Possible Fix?**
Exclude the backup folder

**Comment by HDVinnie** [comment]
Which backup folder? What is the full path it is backing up?

**Comment by Gideon75** [comment]
Backup manager, my folder is 
/var/www/new/storage/backups/SHARE

**Comment by HDVinnie** [comment]
well your dir doesn't match default UNIT3D which is `/var/www/html/storage/backups/UNIT3D`

Did you update your backup config?

**Comment by Gideon75** [comment]
The folder is set correctly in the configuration file (so from the beginning), the problem is that it backs up all its content
 'backup' => [

        /*
         * The name of this application. You can use this name to monitor
         * the backups.
         */
        'name' => 'SHARE',

**Comment by HDVinnie** [comment]
Ill test it now but it specifically excludes the storage dir 

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/3c72b6e2c260568bc48ff0b1081c21dad1459a95/config/backup.php#L47-L53

**Comment by Gideon75** [comment]
ok, in my config is not exclude, eclude only:
it didn't do that before the update, and I didn't change that afterwards

'exclude' => [
                    base_path('vendor'),
                    base_path('node_modules'),

**Comment by HDVinnie** [comment]
Well its been like that for years....check your configs.
