### ISSUE TITLE
[Bug] No seed/leech after update

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#2117]
**Describe the bug**
When I upgrade from 5.3 to 6.0 **everything worked**
This morning I did another update and the new ones don't work, so it's something updated between yesterday and today.

**To Reproduce**
yesterday upgrade fron 5.3 to 6 **ALL WORK**
today git:update **no leech/no seed**
**Screenshots**
https://gyazo.com/f8b684fb720790bbb8b50fab2399f4b8

**UNIT3D (please complete the following information):**
- UNIT3D Version: V6
- Laravel Version: 9.02 (with the previous update all work and laravel 9.01)
- PHP Version: 8.1.2
- Database Driver & Version: 8.0.28-0ubuntu0.20.04.3

**Possible Fix?**
Could it be Laravel 9.0.2?

**Comment by HDVinnie** [comment]
Due to use of Cloudflare
