### ISSUE TITLE
[Bug] Updating to Version 6

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#2119]
**To Reproduce**
Already on PHP 8.1
i run composer self-update
i run git:update

after running migrations the updater exited with this error :
...
...
Migrated:  2022_02_03_090219_update_torrents_table (1,224.42ms)
Migrating: 2022_02_06_210013_update_history_table

In Collection.php line 1581:

  Undefined array key 0

how can i resume the update proccess ? 
thanks in advance

**Comment by HDVinnie** [comment]
seems you have some history records that no longer have a relational torrent
you can go into tinker `php artisan tinker` and run `History::whereDoesntHave('torrent')->count();`
what it return?

**Comment by HDVinnie** [comment]
and what about `History::whereNull('torrent_id')->count();`

**Comment by HDVinnie** [comment]
@nikosuk should I close this?

**Comment by nikosuk** [comment]
>>> History::whereNull('torrent_id')->count();
=> 0
>>>

**Comment by nikosuk** [comment]
users also have reported problem in uploading torrents (invallid filenames in torrent files )
and some torrents give error 500 (they were working before)

**Comment by HDVinnie** [comment]
I mean so is your site up? The migration failed as you had History records in your DB that didn't have a torrent anymore. Would have just needed to run 
```
sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npx mix -p && php artisan optimize:clear && composer self-update && composer install && composer dump-autoload -o && php artisan optimize && sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' + && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo systemctl restart php8.1-fpm && php artisan up
```

Your other mention is not related too this topic. Open a separate issue.

**Comment by nikosuk** [comment]
i can run that now ?

**Comment by HDVinnie** [comment]
`$history = History::whereDoesntHave('torrent')->get();`

`foreach ($history as $h) { $h->delete(); }`

**Comment by nikosuk** [comment]
great, thank you
the invalid entries are now deleted.
Is there any way to re-run the database migrations ?

**Comment by nikosuk** [comment]
How can i resume the database migrations ? i believe the update is not finished for the database.
Thanks for your answer

**Comment by HDVinnie** [comment]
You would have to drop the column via mysql `ALTER TABLE history DROP COLUMN torrent_id;` and then rerun `php artisan migrate`

**Comment by nikosuk** [comment]
i did as you suggested but get this :

# php artisan migrate
Migrating: 2022_02_06_210013_update_history_table

   Illuminate\Database\QueryException

  SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'history_user_id_torrent_id_index' (SQL: alter table `history` add index `history_user_id_torrent_id_index`(`user_id`, `torrent_id`))

  at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712
    708▕         // If an exception occurs when attempting to run a query, we'll format the error
    709▕         // message to include the bindings with SQL, which will make this exception a
    710▕         // lot more helpful to the developer instead of just the database's errors.
    711▕         catch (Exception $e) {
  ➜ 712▕             throw new QueryException(
    713▕                 $query, $this->prepareBindings($bindings), $e
    714▕             );
    715▕         }
    716▕     }

      +12 vendor frames
  13  database/migrations/2022_02_06_210013_update_history_table.php:20
      Illuminate\Support\Facades\Facade::__callStatic()

      +21 vendor frames
  35  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

any ideas ?

**Comment by HDVinnie** [comment]
> i did as you suggested but get this :
> 
> # php artisan migrate
> Migrating: 2022_02_06_210013_update_history_table
> 
> Illuminate\Database\QueryException
> 
> SQLSTATE[42000]: Syntax error or access violation: 1061 Duplicate key name 'history_user_id_torrent_id_index' (SQL: alter table `history` add index `history_user_id_torrent_id_index`(`user_id`, `torrent_id`))
> 
> at vendor/laravel/framework/src/Illuminate/Database/Connection.php:712 708▕ // If an exception occurs when attempting to run a query, we'll format the error 709▕ // message to include the bindings with SQL, which will make this exception a 710▕ // lot more helpful to the developer instead of just the database's errors. 711▕ catch (Exception $e) { ➜ 712▕ throw new QueryException( 713▕ $query, $this->prepareBindings($bindings), $e 714▕ ); 715▕ } 716▕ }
> 
> ```
>   +12 vendor frames
> ```
> 
> 13 database/migrations/2022_02_06_210013_update_history_table.php:20 Illuminate\Support\Facades\Facade::__callStatic()
> 
> ```
>   +21 vendor frames
> ```
> 
> 35 artisan:37 Illuminate\Foundation\Console\Kernel::handle()
> 
> any ideas ?

Updated my post.

**Comment by nikosuk** [comment]
As usual you were correct. it run the migrations.

do i need to run again ::
sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npx mix -p && php artisan optimize:clear && composer self-update && composer install && composer dump-autoload -o && php artisan optimize && sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' + && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo systemctl restart php8.1-fpm && php artisan up

**Comment by HDVinnie** [comment]
> As usual you were correct. it run the migrations.
> 
> do i need to run again :: sudo rm -rf node_modules && sudo npm cache clean --force && sudo npm install && sudo npx mix -p && php artisan optimize:clear && composer self-update && composer install && composer dump-autoload -o && php artisan optimize && sudo chown -R www-data: storage bootstrap public config && sudo find . -type d -exec chmod 0775 '{}' + -or -type f -exec chmod 0644 '{}' + && php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload && sudo systemctl restart php8.1-fpm && php artisan up

Dont have to but never hurts to run it either

**Comment by nikosuk** [comment]
👍 
Thank you very much
