### ISSUE TITLE
[Bug] BBCode issue

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D-Community-Edition#2136]
### Discussed in https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/2135

<div type='discussions-op-text'>

<sup>Originally posted by **PierrePDP** February 22, 2022</sup>
I can for some reason not use the `[center]` tag on any of the pages. Doesn't seem to render correctly. Any ideas?</div>

**Comment by AssortedPDP** [comment]
Hey there - any idea on when this might be fixed?
