### ISSUE TITLE
[Bug] Seedboxes can not be deleted

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#2141]
**Describe the bug**
Seedbox can not be deleted.
404 Page not found:
No query results for model [App\Models\Seedbox] 3, test, eyJpdiI6Ikt3U2huSXd6UWh0YUpQL29kME5YeFE9PSIsInZhbHVlIjoiK2RUU0dqNzJFaGhyUHBSZDB6Y1VBQT09IiwibWFjIjoiOWIyMTFjNTRlZmI3ZWJkOTViNzQxOGVhYTEyMTA0ZDMzNjc3MmI2NjgwMjRmM2E4Y2E2YmYwYjRhMjFiYTI5YSIsInRhZyI6IiJ9, 2022-02-28T06:55:52.000000Z, 2022-02-28T06:55:52.000000Z

**To Reproduce**
1. Go to unit3d.site
2. Go to my profile
3. Create a seedbox with some IP, save it and then try to delete it

**UNIT3D (please complete the following information):**
- UNIT3D Version: 6.x

**Comment by Alkl58** [comment]
Change this:
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/04ce4c63445b54a6961507fd12fb471a950cbcdf/app/Http/Controllers/SeedboxController.php#L72

to this:
```php
protected function destroy(Request $request, $id): \Illuminate\Http\RedirectResponse
```
