### ISSUE TITLE
[Bug] E-mailblacklist don'twork

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#2158]
### UNIT3D Version

6.0.3

### PHP & Platform

PHP 8.1.3 ubuntu 20.04.3

### Laravel verion

9.3.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

with open registrations, users can't use temp-mails or fake mail

### Description

I had to test and email-blacklist don't work anymore.
Can both sendt invitation to a blocked domain and blocked domain can be used in application.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
UNIT3D `v6.0.3` requires PHP v8.1....you show PHP 8.0.

**Comment by Gideon75** [comment]
PHP
Currently Running php 8.1.3
