### ISSUE TITLE
[Bug] Triple Entries

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#2160]
### UNIT3D Version

6.0.3

### PHP & Platform

8.1.0 - Ubuntu 20.04

### Laravel verion

9.3.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Show one result per torrent instead of three

### Description

Hello, after the update to 6.0.0 i have noticed that in page :

https://example.com/users/username/torrents

i have triple entries.
This showed up after the Major update. Since then i have updated again hoping it would be fixed, and now i am using 6.0.3
Unfortunately this goes on :(
Does anyone else have the same problem ?
Any help would be appreciated

![Capture](https://user-images.githubusercontent.com/57614897/158047229-58d40c02-712b-4187-9829-e41bff73449e.PNG)

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Im not able to replicate this.

**Comment by HDVinnie** [comment]
Feel free to send an invite to `unit3d@protonmail.com`

**Comment by nikosuk** [comment]
hello,
any update on this issue ?
