### ISSUE TITLE
[Bug]  Error: Installing Composer Failed!

### ISSUE THREAD

**Issue by HanOddbjorn** [HDInnovations/UNIT3D-Community-Edition#2168]
### UNIT3D Version

none

### PHP & Platform

None php. Prestine Ubuntu 20.04 LTS

### Laravel verion

none

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I've used this installer several time without any problems.
Tried this 2 times now with same result.
![4ea25871703dc355595f6caf6aa59a88](https://user-images.githubusercontent.com/42607841/159466097-0c18fc1b-cf45-4855-9706-9c51a6846d2e.png)

### Description

Installer stops when trying to install php-pear.

Workaround:
Manual installed  PEAR then run installer again.

`$ curl -O https://pear.php.net/go-pear.phar
$ sudo php -d detect_unicode=0 go-pear.phar`

[https://pear.php.net/manual/en/installation.getting.php](url)
![6f72708b68fbb33bce7a8e3cdb1c1852](https://user-images.githubusercontent.com/42607841/159492094-5ab410e4-6acb-4428-88f5-f5c828d93e82.png)

### Stack trace & logs

```shell
None log. All is in the screendump.
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
@HanOddbjorn I cannot replicate this....just ran installer on two different servers just fine. 

[![Screen-Shot-2022-03-22-at-3-17-34-PM.png](https://i.postimg.cc/Fz55pMLj/Screen-Shot-2022-03-22-at-3-17-34-PM.png)](https://postimg.cc/1nHj5YMt)
