### ISSUE TITLE
[Bug] Treating the 25-100% freeleech buff as a category

### ISSUE THREAD

**Issue by probbzy** [HDInnovations/UNIT3D-Community-Edition#2171]
**Describe the bug**
When you browse torrents and use the advanced search filter for a specific category with the buff 0%, 25%, 50%, 75% or 100% freeleech ticked, it will treat this buff as its own category instead of a filter and will append the results of both the category and the buff. 

**To reproduce**

1. Go to torrents browse page (/torrents). 
2. Select "Advanced Search"
3. Select a category, e.g. "Movie"
4. Select a buff from the 0-100% freeleech range, e.g. "100% freeleech"
5. See that the number of results increase instead of decrease, and you can still see all the torrents in the category "Movie" that is not 100% freeleech, but you can also see all the torrents from the other categories that are 100% freeleech. 

**Expected behavior**
The buff will filter depending on selection, so in the example above it will only display movies that are 100% freeleech. 
If you select the buff "Double Upload", then it will filter and behave as expected (See screenshots). 

**Screenshots**
Only movies
![movies](https://user-images.githubusercontent.com/92372605/160254927-b5a30340-1f0e-4d17-b77a-a2dc8937af5a.png)

Movies with 100% Freeleech (Number of results increase)
![freeleech](https://user-images.githubusercontent.com/92372605/160254928-cd62f142-e811-46c6-bf0a-2e3f2443651a.png)

Expected behavior
![double](https://user-images.githubusercontent.com/92372605/160254926-dedbe306-f96c-42a5-a6f3-e7e2123867af.png)

**Comment by probbzy** [comment]
I made a mistake, looks like the buff "0% Freeleech" work, but not the buffs 25-100% freeleech.

**Comment by Alkl58** [comment]
I was poking around the controller some time ago and had the thought that it might lead to an issue, as the query for 25-100% is using `orWhere`.

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/3dafd2d4835513d3c3fff062032597bf5c3127be/app/Http/Livewire/TorrentListSearch.php#L287

Don't know how to fix, as I am not really familiar with search queries.
