### ISSUE TITLE
[Bug] legend badges and highspeed badge missing

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2200]
### UNIT3D Version

6.0.4

### PHP & Platform

8.1.2 Ubuntu 20.04.3 LTS

### Laravel verion

9.5

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Hello all.
a user on our site asked for badges for currently seeding, currently leeching and so on.
was watching then https://yourdomain.com/torrents?perPage=25 and cannot see badges for
currently seeding, currently leeching etc. behind the torrents when seeding or leeching it and so on.
also badge for highspeed torrents aren´t existent, may be since update from version 5.3 to 6 to 6.0.4 (our version actual)
for this informations, ia am not 100% sure since when this badges arent´t there anymore).

the 1st 2 in screenshot torrents are both highspeed and uploaded by myself and didn´t show badges behind the torrents.
is this being revised at the moment or is there an error on our side?

![torrentlistviewl3g3nds](https://user-images.githubusercontent.com/67836615/163795968-0dbf0b09-4e81-447b-98be-7682d86c4a90.jpg)

as an example a screenshot from older version

![52019022927_3a95e9661a_o](https://user-images.githubusercontent.com/67836615/164524674-a3e8c0ae-35c7-45ed-a37f-e39c2bd04cb7.png)

### Description

cannot see this 5 kind of badges on /html/resources/views/livewire/torrent-list-search.blade.php

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
You already have a discussion open here https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions/2197

Dont make dupes.
