### ISSUE TITLE
[Bug]dl error backup manager

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2208]
### UNIT3D Version

6.0.4

### PHP & Platform

8.1.2 Ubuntu 20.04.3 LTS

### Laravel verion

9.5

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

did create database backup with backup manager, database filesize ackupped is 87.09 MB

### Description

when i try to dl after finishing i get following error:  Error 500: Internal Server Error! 
it always shows same error, regardless of whether I want to download pure database backup or file backup.

### Stack trace & logs

```shell
[2022-04-25 08:25:11] prod.ERROR: Allowed memory size of 134217728 bytes exhausted (tried to allocate 65028096 bytes) {"userId":3,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 65028096 bytes) at /var/www/html/app/Http/Livewire/BackupPanel.php:167)
[stacktrace]
#0 {main}
"}
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by hucstar** [comment]
I met the same problem.

**Comment by HDVinnie** [comment]
This is a PHP error.....tune your PHP config. Otherwise SFTP the backup to your local machine.

**Comment by kREATUr67** [comment]
To say it straight away, none of the settings / changes in php.ini made have eliminated the error. 
old database backup with 19.84 MB possible. the next backup with 51.41 MB already produces the error described above.
After searching for alternative solutions I came across the following solution:

edited /html/app/Http/Livewire/BackupPanel.php
on line 137
```
        // Temporarily increase memory limit to 512MB
        ini_set('memory_limit','512M');
```

in this way, at least dl of backups of up to 102 mb were previously possible.
maybe this will help someone who, like me, just wants to make a pure database backup for a short time at home, without having to access the server separately.

the advantage of this variant is that the change only affects the livewire backup php and does not affect the other page settings at all.
**important**, during the process itself, no reactions possible in the same browser on this page. just wait for the download to finish. then other parts of the page can be opened normally again!!!

Thanks for reading, maybe it's a suitable solution for you too
