### ISSUE TITLE
[Bug] Torrent search view, visual bug

### ISSUE THREAD

**Issue by gamemnon** [HDInnovations/UNIT3D-Community-Edition#2266]
### UNIT3D Version

6.1.0

### PHP & Platform

php8.1.6 & 8.0.29-0ubuntu0.20.04.3

### Laravel verion

9.10.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Nothing appear in Firefox/Opera

### Description

Hello,

In torrent search view (advanced) when you select cat, type and other field a cercle appear on the screen and deplace himself if you select/deselect
Can reproduce it with Chrome 102.0.5005.63 (Build officiel) (64 bits) & Edge Version 102.0.1245.33 (Version officielle) (64 bits)

Thanks.

### Stack trace & logs

```shell
visual bug, no log
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by Roardom** [comment]
Caused by the @ supports() css added in https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/1cb3b0ecac1635ca782ff436b18b4e3b58ba8be8.

That css will be removed once more of the front-end refactor is complete.
