### ISSUE TITLE
[Bug] Filters by Start / End year don't work

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#2283]
### UNIT3D Version

6.2.1

### PHP & Platform

8.1.7 - Ubuntu 20.04.4 LTS

### Laravel verion

9.18.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I want to be able to filter releases over a period of time.

Eg: 
Category: Movies
Start year: 1990
End year: 1999 

### Description

Filters by year aren't working and the results are empty.
Unfortunately, the only logs generated by the application during the search are the ones below. No error at all.

### Stack trace & logs

```shell
==> nginx/access.log <==
172.70.110.169 - - [25/Jun/2022:16:47:54 -0300] "GET /torrents HTTP/1.1" 200 27236 "http://redacted.com/torrents?perPage=25&endYear=2003&startYear=2003" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
172.70.110.169 - - [25/Jun/2022:16:48:04 -0300] "POST /livewire/message/torrent-list-search HTTP/1.1" 200 124420 "http://redacted.com/torrents?perPage=25" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
172.70.110.169 - - [25/Jun/2022:16:48:05 -0300] "POST /livewire/message/torrent-list-search HTTP/1.1" 200 124422 "http://redacted.com/torrents?perPage=25&startYear=200" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
172.70.110.169 - - [25/Jun/2022:16:48:08 -0300] "POST /livewire/message/torrent-list-search HTTP/1.1" 200 124429 "http://redacted.com/torrents?perPage=25&startYear=2000" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
172.70.110.169 - - [25/Jun/2022:16:48:09 -0300] "POST /livewire/message/torrent-list-search HTTP/1.1" 200 124433 "http://redacted.com/torrents?perPage=25&startYear=2000&endYear=20" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/103.0.5060.53 Safari/537.36"
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
@costaht can you run `php artisan fetch:release_years` and try again. If works ill fix in next release.

**Comment by costaht** [comment]
Yes, it worked right away!!! Thanks a lot!

**Comment by costaht** [comment]
That might not be the type of solution you expect, but we "solved" this problem by scheduling the command you said to run hourly.

We added `$schedule->command('fetch:release_years')->hourly();` to `app/Console/Kernel.php` and it's been working great.

**Comment by HDVinnie** [comment]
> That might not be the type of solution you expect, but we "solved" this problem by scheduling the command you said to run hourly.
> 
> We added `$schedule->command('fetch:release_years')->hourly();` to `app/Console/Kernel.php` and it's been working great.

While it works its not how it should be. The command was to be used once when the feature was added. The year should be saved and updated upon torrent upload and edit. Ill make a PR soon ™️ for this.
