### ISSUE TITLE
[Bug]chatbox does not refresh anymore after updating firefox 103

### ISSUE THREAD

**Issue by kREATUr67** [HDInnovations/UNIT3D-Community-Edition#2321]
### UNIT3D Version

6.0.4

### PHP & Platform

8.1.2 Ubuntu 20.04.3 LTS 64bit

### Laravel verion

9.5

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

chatbox refresh after opening 'home'

```
User-Agent
	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:103.0) Gecko/20100101 Firefox/103.0
```

### Description

the refresh request leads to 200, but its marked red, and then when i right see the answer shows:

`Reason: CORS header 'Access-Control-Allow-Origin' does not match 'xyz'`

the error is the same on demo site [https://unit3d.site/](url)

greetings to all unit3d fans out there!

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Seems like a FF issue to me then. 

`nano .env` from project root.

Make sure `MIX_ECHO_ADDRESS` is using https and not http for site URL.

Save and exit and then reloadsupervisor. `sudo supervisorctl reload`

**Comment by kREATUr67** [comment]
changed to https, reloaded supervisor, but unfortunately issue stays in ff

**Comment by HDVinnie** [comment]
Try demo site now.

**Comment by kREATUr67** [comment]
well, yes you are right, there it works. first cannot really understand why does not work on our site.
but then somehow had a feeling to do `npx mix --production`

after i ´d done it, refresh again is working like a charme.

thank you very much for your help and advice vinnie.

have a good time
