### ISSUE TITLE
Types system to be relational to categories

### ISSUE THREAD

**Issue by torrentocarlo** [HDInnovations/UNIT3D-Community-Edition#237]
In one category, there is a wide variety of content. I think adding sub-categories would help to better navigate.

**Comment by HDVinnie** [comment]
That's what types are for

**Comment by esteban63** [comment]
Yes, but types are not specifically associated with this or that category.
For example, if I want to upload music, I will find the movies type in the list.

**Comment by xR4E** [comment]
I second this, I already asked for this a while back. :+1:  (on Discord)

**Comment by HDVinnie** [comment]
So instead of sub-categories we can just rework the types system to be relational to categories.

**Comment by esteban63** [comment]
Yep it's the same.

**Comment by HDVinnie** [comment]
This will be added for next release of UNIT3D v1.9

**Comment by torrentocarlo** [comment]
Yeah that's a great news.
Do you have an idea of the release date ?

**Comment by poppabear8883** [comment]
@torrentocarlo We never have ETA's on releases as right now everything is Early Access aka "Pre-Release". We are still under heavy development and the code base is updated often. Just feel comfortable that it is on the roadmap for v1.9 ;)

**Comment by torrentocarlo** [comment]
@poppabear8883 Ok so if I understand well, there will be not one big 1.9 update but one day when all features will be add, the project will be on 1.9 that's right ?

**Comment by poppabear8883** [comment]
@torrentocarlo what I mean is that if you see a v1.9 release, you can be sure it will indeed have this feature. Until then its just planned to happen at some point between now and then.

**Comment by torrentocarlo** [comment]
Ok that's clear thank you !

**Comment by LayerCorp** [comment]
This is a must! ;)

**Comment by HDVinnie** [comment]
This is done in `2.x.x` branch. This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.
