### ISSUE TITLE
[Bug] Missing seeds after update to 6.4.0

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2396]
### UNIT3D Version

6.4.0

### PHP & Platform

8.1.8

### Laravel verion

9.25.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Not sure what is causing it. No error message.

### Description

After updating to 6.4.0, active seeds seem to be missing. Only 1364 out of 2857 of my actively seeding torrents show up in the stats and seeders do not show up on torrents they are seeding. Others on my tracker are also having the same problem with missing seeds.

Some torrents you are seeding you dont shuw up as seeding at all.

Torrents have been restarted and reannounced, with no difference.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by FuNFooKaS** [comment]
Same problem on my site as well,but took like a week after the update to appear.

**Comment by HDVinnie** [comment]
Closed in `v6.4.1`
