### ISSUE TITLE
[Bug] Error on creating  public rss feed

### ISSUE THREAD

**Issue by FuNFooKaS** [HDInnovations/UNIT3D-Community-Edition#2409]
### UNIT3D Version

6.4.1

### PHP & Platform

8.1.7 ubuntu 20.0-4

### Laravel verion

9.28

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

when in dash trying to create a public rss feed  once done and hit submit it  should create the feed.

### Description

when in dash trying to create a public rss feed  once done and hit submit it pop up with this error

https://i.gyazo.com/thumb/1200/96a8d8220cd151a13528aeede270e645-png.jpg

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Fix the issue title please.

**Comment by FuNFooKaS** [comment]
fixed,sorry

**Comment by HDVinnie** [comment]
Are you still facing this issue? I cannot replicate it on latest UNIT3D @FuNFooKaS

**Comment by FuNFooKaS** [comment]
no it seems to be fixed
