### ISSUE TITLE
[Bug] Banner in README.md has grammer issue and Sex offender

### ISSUE THREAD

**Issue by myxomatosis** [HDInnovations/UNIT3D-Community-Edition#2445]
### UNIT3D Version

Latest

### PHP & Platform

N/A

### Laravel verion

N/A

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When I read the README.md file, I expect the grammar to be correct and not to see a sexual assaulter.

### Description

Instead when I read the README.md file, I see, "An open source HDInnovations project found by HDVinnie". It should be, "An open source HDInnovations project founded by HDVinnie". I also respectfully request the project banner to be updated so as to remove Kevin Spacey from the banner. He stands accused of sexual assault, pedophilia, and rape and has had a judgement of $31m against him for violating MRC's anti-harassment policy per the [BBC](https://www.bbc.com/news/entertainment-arts-62433694).

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by myxomatosis** [comment]
Thanks for taking a look anyway HDVinnie! I really appreciate your work.

**Comment by Digeri** [comment]
@myxomatosis  "I also respectfully request the project banner to be updated so as to remove Kevin Spacey from the banner." 

No, You should go put some Kevin Space between yourself and Github.
