### ISSUE TITLE
ppa repository isnt working

### ISSUE THREAD

**Issue by wht3v34** [HDInnovations/UNIT3D-Community-Edition#2481]
E: The repository 'https://ppa.launchpadcontent.net/linuxuprising/libpng12/ubuntu jammy Release' does not have a Release file.
 Error: Updating packages Failed! 
 Please try re-running the script via 'sudo ./install.sh' 

i tried removing the repo and then adding it by install script. but its same again and again.

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition#-automated-installer

22.04 is not supported yet

**Comment by wht3v34** [comment]
So no other way to install it?

**Comment by FuNFooKaS** [comment]
You could install it on 20.04 then upgrade to 22.04.

**Comment by HDVinnie** [comment]
^ until 22.04 is added

**Comment by wht3v34** [comment]
I've sent you an email regarding a tool few days ago i am waiting for your reply. Please reply. Thanks
