### ISSUE TITLE
[Bug] Demo Site appearse to be permanently down. (Error 503)

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#2525]
### UNIT3D Version

N/A

### PHP & Platform

N/A

### Laravel verion

N/A

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Demo Site appearse to be permanently down. (Error 503)

### Description

Demo Site appearse to be permanently down. (Error 503)

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
This is not a bug/issue. We're aware and can open an issue if you want but sponsorships are way down and project is nearing end.

**Comment by innocente205** [comment]
Thanks for the info. You're alright, as long as you're aware.
