### ISSUE TITLE
[Bug] Forum quotes not working when text has line break

### ISSUE THREAD

**Issue by Obi-Wana** [HDInnovations/UNIT3D-Community-Edition#2532]
### UNIT3D Version

6.5.'

### PHP & Platform

8.1.2

### Laravel verion

9

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When quoting posts with a line break, the quotation button does nothing.
It works on single line posts, tho.

### Description

Browser console shows error/warning messages related to the quotation button.
Happens on several UNIT3D based sites.

### Stack trace & logs

```shell
Warning:

Alpine Expression Error: '' string literal contains an unescaped line break

Expression: "
                            document.getElementById('forum_reply_form').style.display = 'block';
                            input = document.getElementById('bbcode-content');
                            input.value += '[quote=@Username]Text
here
with multi lines.[/quote]';
                            input.dispatchEvent(new Event('input'));
                            input.focus();
                        "

 
<button class="post__quote" title="Quote" x-data="" x-on:click="\n                      …                        ">
```

Error:
```
Uncaught SyntaxError: '' string literal contains an unescaped line break
    i https://url.tld/js/alpine.js?id=000007c248ff0d4afe6a425be6efd204:1
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by hucstar** [comment]
When I upgraded to version 6.5.0, the forum CSS effect was lost.

![](https://i.ibb.co/Wvs8fLP/1674464630223.png)

**Comment by Obi-Wana** [comment]
> When I upgraded to version 6.5.0, the forum CSS effect was lost.
> 
> ![](https://camo.githubusercontent.com/561ab8def941076333e4dd7a80bbf8ae33c117c0938f9b8811c3a0fafaa1cd4b/68747470733a2f2f692e6962622e636f2f57767338664c502f313637343436343633303232332e706e67)

This does not seem to be related to my issue (and did not happen to me).
Did you run `npx mix -p`? (Please do not reply in this issue, you may want to create a discussion thread or seek support on discord within the provided support channel.)

**Comment by HDVinnie** [comment]
This is fixed for next release. https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/46141cf28c24cd760e19c5bbf4db82cc548fe0f4
