### ISSUE TITLE
Smileys

### ISSUE THREAD

**Issue by klapvogn** [HDInnovations/UNIT3D-Community-Edition#2586]
Hi,

Thanks for a wonderful source, but I miss a thing and thats smileys in the forum, it that something you have considered to add?

**Comment by Roardom** [comment]
On windows/linux, press <kbd>Win</kbd>+<kbd>.</kbd>.
On macos, press <kbd>Cmd</kbd>+<kbd>Ctrl</kbd>+<kbd>Spacebar</kbd>.
