### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by klapvogn** [HDInnovations/UNIT3D-Community-Edition#2591]
### UNIT3D Version

6.5.0

### PHP & Platform

8.0.32-0ubuntu0.20.04.2 x64

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When I was in a good mod I did a guide in my forum, but in the heat of the moment I forgot to set a forum title. and when I hit save. All the work was gone and I needed to do the guide all over again.

### Description

When I was in a good mod I did a guide in my forum, but in the heat of the moment I forgot to set a forum title. and when I hit save. All the work was gone and I needed to do the guide all over again.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by Roardom** [comment]
Funny, I just ran into this last night. Already have a fix on the way.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/2592 for next release.
