### ISSUE TITLE
[Bug] line 1: mysql_install_db: command not found

### ISSUE THREAD

**Issue by bringlive** [HDInnovations/UNIT3D-Community-Edition#2606]
### UNIT3D Version

6.x.x

### PHP & Platform

8.1.2 - Ubuntu 22 LTS

### Laravel verion

9.2.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

Hope fix

### Description

[ERROR] sh: line 1: mysql_install_db: command not found

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
https://github.com/HDInnovations/UNIT3D-Community-Edition#-automated-installer

Says Ubuntu 20.04
Your using 22

**Comment by bringlive** [comment]
Please update,

**Comment by HDVinnie** [comment]
> Please update,

Or it's as simple as installing on 20.04. Then after install is complete if want to upgrade OS just run do-release-upgrade. Ubuntu 20.04 is a LTS and is no where near the 2030 end of life. 

Adding support to installer for other OS is an idea planned but there is no where near a ETA on it as this project might not last much longer.

**Comment by bringlive** [comment]
So downgrade then upgrade?
