### ISSUE TITLE
[Bug] the order of the actors is general, not by movie/series as it should be

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#2637]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2.1 Ubuntu 20.04

### Laravel verion

9.41

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

the order of the actors is stored in cast table, not in cast_movie/cast_tv as it should be

### Description

I will explain it with an example: With the movie Armageddon, if we edit it and do the processMovieJob, the actor Bruce Willis in the cast table assigns the order field the value 0 and if we do the same with the movie Ocean's Twelve. assigns the value 71.
This order should be by movie/tv, not by actor, since the order in which the photos appear in the movie/series torrent blade depends on it.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
Fixed in 7.x.x
