### ISSUE TITLE
Tracking Upcoming Releases

### ISSUE THREAD

**Issue by NghtCaptn** [HDInnovations/UNIT3D-Community-Edition#264]
To help RG's keep track of who's working on what to prevent duplicate releases from being made and so fourth. If one member of the RG puts in an entry it checks for any other entries in both the live torrents and the upcoming releases. So long as there's not another  It would also be good for letting the users view it so they can see what we're working on. There could be options for tracking the process like "Sourcing", "Remuxing", "Encoding", "Muxing", "Uploading", "Done". Also displaying how long each release will take and how much time is left set on a timer that the user from the RG sets.

**Comment by HDVinnie** [comment]
This is coming in the next release which will be v1.8.5
