### ISSUE TITLE
[Bug] edit a headline in a post

### ISSUE THREAD

**Issue by klapvogn** [HDInnovations/UNIT3D-Community-Edition#2654]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2.2 - 8.0.32-0ubuntu0.20.04.2

### Laravel verion

9.41.0

### Have you done this?

- [x] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I made a post yesterday. And decided to change the headline on it and i can see the change when I goto `https://url.com/forums/4` But I can't see the change from the forum overview `https://url.com/forums` is still the old overview name.

### Description

.

### Stack trace & logs

```shell
.
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
This will be solved soon in the forums refactor.

**Comment by HDVinnie** [comment]
fixed in v7 branch for next release
