### ISSUE TITLE
[Bug] Incorrect leecher count

### ISSUE THREAD

**Issue by espiman** [HDInnovations/UNIT3D-Community-Edition#2704]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2.1 Ubuntu 20.04

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When I delete a torrent with only 1 leecher (me) and 0 seeders , it should show up with 0 seeders and 0 leechers, however it shows 1 leecher.

### Description

When I delete a torrent with only 1 leecher (me) and 0 seeders , it should show up with 0 seeders and 0 leechers, however it shows 1 leecher, and if you click on the 1 leecher, it loads the empty leechers screen.

### Stack trace & logs

```shell
It is not necessary, it does not give any error.
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
What client are you using? Are you stopping the torrent so it sends the stopped event before deleting it?

**Comment by Roardom** [comment]
You're probably running into https://github.com/rakshasa/rtorrent/issues/899

**Comment by espiman** [comment]
Deluge 2.0.5
No, I delete the torrent directly as I always do. It correctly goes through the stopped event of the ProcessAnnounce job because it deletes the peer and updates the history.
It only fails if there are 0 seeders and 0 leechers

Thanks.

**Comment by Roardom** [comment]
From what I could find, it seems to occur on all stopped events. Can you check if the linked PR fixes the issue?

**Comment by espiman** [comment]
It seems to work correctly.

Thenk you!!!
