### ISSUE TITLE
[Bug] 7.x.x, Torrent not registered with this tracker.

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2711]
### UNIT3D Version

7.x.x

### PHP & Platform

8.2.3

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

.

### Description

When you upload a torrent, then delete it. And then reupload the same torrent and try to seed it, you just get the error: `Torrent not registered with this tracker.`

No error logs.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
solved
