### ISSUE TITLE
[Bug] 7.x.x, checkMinInterval not working

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2715]
### UNIT3D Version

7.x.x

### PHP & Platform

8.2.4

### Laravel verion

10.7.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

.

### Description

The function is not working correctly or at all.

### Stack trace & logs

```shell
no logs
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by LostRager** [comment]
From my logging, it seems like there is an issue with ` $randomMinInterval = random_int($setMin, $setMin * 2);`

**Comment by LostRager** [comment]
From my logging it seems like there is an issue with 

```
$prevAnnounce = $torrent->peers
            ->where('peer_id', '=', base64_decode($queries['peer_id']))
            ->where('user_id', '=', $user->id)
            ->first();
```

**Comment by LostRager** [comment]
Fixes the issue: `->select(['id', 'torrent_id', 'peer_id', 'user_id', 'left', 'seeder', 'port', 'updated_at'])`

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L393

**Comment by HDVinnie** [comment]
> Fixes the issue: `->select(['id', 'torrent_id', 'peer_id', 'user_id', 'left', 'seeder', 'port', 'updated_at'])`
> 
> https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/45dbf0849bd49cbc8bfdea5d01776eebea46697e/app/Http/Controllers/AnnounceController.php#L393

that would do it. nice find!
