### ISSUE TITLE
[Bug] small-bookmark-button performance hit

### ISSUE THREAD

**Issue by LostRager** [HDInnovations/UNIT3D-Community-Edition#2730]
### UNIT3D Version

7.x.x

### PHP & Platform

8.2.4

### Laravel verion

10.7.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

.

### Description

The bookmark button seems to be hogging alot processing power when there is a very large amount of torrents (2600) on the similar page. 
`@livewire('small-bookmark-button', ['torrent' => $torrent, 'isBookmarked' => $torrent->bookmarks_exists, 'user' => auth()->user()], key('torrent-' . $torrent->id))`

Here is the loading time with it not commented out: 
![rkUA0mcI8p](https://user-images.githubusercontent.com/5929772/234939601-ed4cd005-5ee8-4276-868c-35278663c0ce.png)

And here it is with it commented out.
![FG5nUAIk3q](https://user-images.githubusercontent.com/5929772/234939213-372df223-ea6d-4886-ba7e-d8440d20587a.png)

### Stack trace & logs

```shell
Nothing
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by Roardom** [comment]
I'm not able to find anything in the code or through testing that looks to be an issue besides it simply being a large number. Not seeing any n+1 queries. Might just be too much for the framework to handle for a single page.

**Comment by HDVinnie** [comment]
> I'm not able to find anything in the code or through testing that looks to be an issue besides it simply being a large number. Not seeing any n+1 queries. Might just be too much for the framework to handle for a single page.

only thing I can think of is because the whole model is passed.

`@livewire('small-bookmark-button', ['torrent' => $torrent, 'isBookmarked' => $torrent->bookmarks_exists, 'user' => auth()->user()], key('torrent-'.$torrent->id))`

`'torrent' => $torrent` includes everything like media info, decription, etc which is probably why theres a large memory increase and slower.

**Comment by HDVinnie** [comment]
> ### UNIT3D Version
> 7.x.x
> 
> ### PHP & Platform
> 8.2.4
> 
> ### Laravel verion
> 10.7.1
> 
> ### Have you done this?
> * [x]  I am willing to share my stack trace and logs
> * [ ]  I can suggest a fix as a Pull Request
> 
> ### Expectation
> .
> 
> ### Description
> The bookmark button seems to be hogging alot processing power when there is a very large amount of torrents (2600) on the similar page. `@livewire('small-bookmark-button', ['torrent' => $torrent, 'isBookmarked' => $torrent->bookmarks_exists, 'user' => auth()->user()], key('torrent-' . $torrent->id))`
> 
> Here is the loading time with it not commented out: ![rkUA0mcI8p](https://user-images.githubusercontent.com/5929772/234939601-ed4cd005-5ee8-4276-868c-35278663c0ce.png)
> 
> And here it is with it commented out. ![FG5nUAIk3q](https://user-images.githubusercontent.com/5929772/234939213-372df223-ea6d-4886-ba7e-d8440d20587a.png)
> 
> ### Stack trace & logs
> ```shell
> Nothing
> ```
> 
> ### Are you a UNIT3D sponsor?
> Yes, with my username

regardless of my previous comment to @Roardom. Im not able t replicate your drastic load time with bookmark button on latest v7. Can you check again? Im seeing `This page took 0.111 seconds to render and 12.00 MB of memory` consistently on prod site using Opcache and preloading.

This page took 0.228 seconds to render and 14.00 MB of memory on demo site with no Opcache or preloading.
This page took 0.181 seconds to render and 12.00 MB of memory on demo with Opcache and preloading.

**Comment by HDVinnie** [comment]
@LostRager
