### ISSUE TITLE
[NOBUG]

### ISSUE THREAD

**Issue by klapvogn** [HDInnovations/UNIT3D-Community-Edition#2804]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2.2 - 8.0.32-0ubuntu0.20.04.2

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I was doing a guide in the forum, when I noticed when you do : `[code][img=250]img path[/img][/code]`
is show like a regular tag (will show the image) could it be possible to do it like:

if you would like to show the user how to use a tag in like code tag it does not try to show the image, but how to make the tag

### Description

I was doing a guide in the forum, when I noticed when you do : `[code][img=250]img path[/img][/code]`
is show like a regular tag (will show the image) could it be possible to do it like:

if you would like to show the user how to use a tag in like code tag it does not try to show the image, but how to make the tag

### Stack trace & logs

```shell
none
```

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by Roardom** [comment]
This is functioning as intended. It would break many existing torrent descriptions and forum posts if images within code blocks stopped working.
