### ISSUE TITLE
Roles and Permissions System (RBAC)

### ISSUE THREAD

**Issue by croplex** [HDInnovations/UNIT3D-Community-Edition#284]
Add can_forum
Add can_privateMessage

**Comment by poppabear8883** [comment]
I would like to re-work the entire permissions/roles system eventually .. as you can see there can be any number of permissions someone may want, this is why we should have had a table structure like:

`Users BelongsTo a Role`
`A Role hasMany Permissions`
`A Permission hasMany Roles`

This would have enabled admin/staff to create there own permissions and roles.

Or similar.

**Comment by HDVinnie** [comment]
This will be addressed in https://github.com/HDInnovations/UNIT3D/tree/RBAC(role-based-access-control) branch at some point.

**Comment by DXDHD** [comment]
Has this idea been dropped ?

**Comment by HDVinnie** [comment]
No. Just no one has gotten to it yet unfortunately.
