### ISSUE TITLE
[Bug] - No image in torrent page and error in laravel log

### ISSUE THREAD

**Issue by carloangeletti** [HDInnovations/UNIT3D-Community-Edition#3073]
### UNIT3D Version

6.5.0

### PHP & Platform

8.2 - ubuntu 22.04

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When you open the tab of the uploaded torrent it should preview images and fetch data from TMDB

### Description

I uploaded the first test torrent file and it worked. Now I'm uploading new files but the detail tab doesn't work properly, it doesn't show images. When I click on the image and it goes in the similar from error 500 and I have a specific error in Laravel.

`Attempt to read property "name" on null {"view":{"view":"/var/www/html/resources/views/torrent/similar.blade.php","data":[]},"userId":3,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Attempt to read property \"name\" on null at /var/www/html/resources/views/torrent/similar.blade.php:4)
`
-

`The MAC is invalid. {"exception":"[object] (Illuminate\\Contracts\\Encryption\\DecryptException(code: 0): The MAC is invalid. at /var/www/html/vendor/laravel/framework/src/Illuminate/Encryption/Encrypter.php:218)
`

<img width="1719" alt="Screenshot 2023-08-20 alle 00 27 31" src="https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/18361214/a4f13eaf-0554-486f-926e-4f59eafa87c6">
<img width="1650" alt="Screenshot 2023-08-20 alle 00 27 16" src="https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/18361214/b26fcecf-ddd2-4e82-82eb-f18f230b570e">
<img width="644" alt="Screenshot 2023-08-20 alle 00 28 24" src="https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/18361214/aeb57e0d-ae58-4b1b-bc02-319816e0729c">

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by carloangeletti** [comment]
This appen when server are reboot 🤨

**Comment by HDVinnie** [comment]
Seems like maybe your queue workers are not running. Maybe try running `php artisan set:all_cache && sudo systemctl restart php8.2-fpm && php artisan queue:restart` and then editing the upload and seeing if meta updates. Also make sure in Category settings on staff dashboard that Movie category has ONLY movie_meta selected.

**Comment by carloangeletti** [comment]
I tried a clean install. I uploaded a few torrents and then it gave the same problem again. I have the first 3 torrents uploaded fine and the new ones don't work after a while.

With this, your system seems to be working again. Thank you.

**Comment by carloangeletti** [comment]
Hi @HDVinnie, unfortunately I keep having this problem.
Now even restarting everything seems not to work properly.

Do you have any suggestion about it?
I also tried to set the default language to IT but the meta data is always in English.

Thanks

**Comment by HDVinnie** [comment]
No need to open a duplicate issue. Can continue here. Im not able to replicate your issue. If you want to DM me soon discord I can look at your site to see what your doing wrong.

**Comment by carloangeletti** [comment]
Thanks a lot, sorry for duplicate 🙏🏻.
