### ISSUE TITLE
[suggestion] Delay before search

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3170]
In most areas, any character entered into any search box appears to be a new search.

IMO, there should be a small delay, after the last character is entered, before running the actual search, 

Expected outcome: Perhaps less resource usage, but mostly, when the back button is pressed, it goes back a page, not back through every single character entered into the search form.

**Comment by HDVinnie** [comment]
Issue board is for bugs only. Please use discussions for feature ideas, suggestions, etc.

https://github.com/HDInnovations/UNIT3D-Community-Edition/discussions
