### ISSUE TITLE
[Bug] Forums - Parent Forums (New Category) not working.

### ISSUE THREAD

**Issue by ThyThal** [HDInnovations/UNIT3D-Community-Edition#3188]
### UNIT3D Version

7.0.0

### PHP & Platform

8.2.11 - Ubuntu 22.04 x64

### Laravel verion

10.26.2

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Creates a new category from the title.

### Description

When creating new forums or categories the new function does not allow to be used, you need to use an already existing one.
I delete the main forum to try out, and now I can not add anything because I have no parent to choose from.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
fixed in v7.0.3
