### ISSUE TITLE
[Bug] 7.x.x database migration bug

### ISSUE THREAD

**Issue by Slikkster** [HDInnovations/UNIT3D-Community-Edition#3196]
### UNIT3D Version

7.0.2

### PHP & Platform

8.2.11 - Ubuntu 20.04 x64

### Laravel verion

9.41.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

DB migration from 6.5 to 7.0 completes without errors

### Description

When running php artisan migrate, the below errors occur and the migration does not complete. It appears that in these two files:
- [2022_11_24_032502_update_torrents_table.php](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/database/migrations/2022_11_24_032502_update_torrents_table.php)
- [2022_11_24_032521_update_requests_table.php](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/database/migrations/2022_11_24_032521_update_requests_table.php)

all instances of `'not regex'` should actually be `'not regexp'`. At least, this seemed to fix the problem for me, and the migration was able to complete successfully.

### Stack trace & logs

```shell
In Connection.php line 760:

  SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'not regex' (SQL: update `requests` set `imdb` = 0 where `imdb` is null or `imdb` < 0 or `imdb` > 200000
  0000 or `imdb` = not regex)


In Exception.php line 18:

  SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'not regex'


In PDOStatement.php line 117:

  SQLSTATE[22007]: Invalid datetime format: 1292 Truncated incorrect DOUBLE value: 'not regex'
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
fixed in v7.0.3
