### ISSUE TITLE
[Bug] Application Signup Text Area

### ISSUE THREAD

**Issue by edge20200** [HDInnovations/UNIT3D-Community-Edition#3199]
### UNIT3D Version

7.0.0

### PHP & Platform

8.2.11 - Ubuntu 22.04 x64

### Laravel verion

10.26.2

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Be able to type in the text area where it would normally ask for why you want to join or who referred you etc.

### Description

Text area is not usable and can not be typed in. 
![app](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/126633394/f4f52bc9-ec27-47c7-b766-36e7fab83098)

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
fixed in v7.0.3
