### ISSUE TITLE
[Bug] when someone connects to a torrent, it is counted in the torrent table, but not recorded in table peers

### ISSUE THREAD

**Issue by klemendv** [HDInnovations/UNIT3D-Community-Edition#3214]
### UNIT3D Version

7.00

### PHP & Platform

8.1.2 ubuntu

### Laravel verion

9.2.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

I expected that when someone connects to the tracker with a torrent that he has uploaded to the page, it will appear in the torrents table and in the peers table

### Description

I have installed the latest version of unit3d on my ubuntu 22nd server hosted by contabu. When I uploaded one torrent for the test, it uploaded it, then when I downloaded it to start seeding, it showed in the torrent client that it was working, the seed was added to the torrents table, but not in the peers table, and even when it wants to someone download that torrent, peer shows him, but the download does not start

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
Is this new install or upgrade from older UNIT3D?

**Comment by klemendv** [comment]
Hi, the server is a fresh install and unit3d is a fresh install, so it's a fresh install

**Comment by HDVinnie** [comment]
What's redis-server --version return when run in terminal?

**Comment by klemendv** [comment]
7.0.14

**Comment by HDVinnie** [comment]
> 7.0.14

What about the second command?

**Comment by klemendv** [comment]
I reinstalled the server again and I will reinstall unit3d so that we have accurate data and log records of what is happening

**Comment by HDVinnie** [comment]
@klemendv i have to get back to work but will be around tonight. Pretty much follow step 6 and 7 here in release notes https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v7.0.0 then restart php and redis. Then report back. I'll look into installer tonight to see if there is a new issue with it as I just used it last week with no problems.

**Comment by alexdinu05** [comment]
I have the same problem after installing the latest version of unit3d.

**Comment by klemendv** [comment]
ok i installed ubuntu 22.04 i installed united i followed the steps as you said but the peer is still not in the peers table and the download doesn't start, i doubt it's my problem considering that others are also reporting problems.

**Comment by alexdinu05** [comment]
I noticed the same problem is also on https://unit3d.site/ .
I uploaded the torrent https://unit3d.site/torrents/90 , it is set to seed on seedbox and if I try to download from another terminal the download does not start

**Comment by HDVinnie** [comment]
> I noticed the same problem is also on https://unit3d.site/ .
> 
> I uploaded the torrent https://unit3d.site/torrents/90 , it is set to seed on seedbox and if I try to download from another terminal the download does not start

Peer and history shows there fine. You cannot seed/leech to yourself. In private trackers that's cheating and is blocked in UNIT3D. You need to upload / seed from one account and leech from another.

**Comment by kovalensky** [comment]
@HDVinnie Didn't want to start another issue, since there are only two options for bugs and vulnerabilities.

Mine is a question, afaik Unit3D has some anti-cheat system for announcer (or maybe I'm wrong), we were looking to upgrade ours but wasn't sure where to get modern one.
Could you please refer to files where I could look at its code and adapt to our needs, the search in repository by keywords by me didn't bring satisfactory results.
With permission of course.

**Comment by alexdinu05** [comment]
> > I noticed the same problem is also on https://unit3d.site/ .
> > I uploaded the torrent https://unit3d.site/torrents/90 , it is set to seed on seedbox and if I try to download from another terminal the download does not start
> 
> Peer and history shows there fine. You cannot seed/leech to yourself. In private trackers that's cheating and is blocked in UNIT3D. You need to upload / seed from one account and leech from another.

I tried to download from different accounts but it still doesn't work.

**Comment by kovalensky** [comment]
> @HDVinnie Didn't want to start another issue, since there are only two options for bugs and vulnerabilities....

@HDVinnie ?

**Comment by HDVinnie** [comment]
None of us can replicate any issues.
