### ISSUE TITLE
[Bug] Email are no longer working

### ISSUE THREAD

**Issue by l3oncoder** [HDInnovations/UNIT3D-Community-Edition#3321]
### UNIT3D Version

7.1.3

### PHP & Platform

8.2.x Ubuntu 22.04

### Laravel verion

Latest

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Emails to send out, instead of timing out

### Description

Has anything change in terms of mailer, between 7.1.2 and 7.1.3, as we have test our smtp and confirmed our details are correct, however the site timing out when trying to send invite out etc

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by clandestine8** [comment]
99% of email issues are related to the infrastructure or configuration provided by the site administrator. The email systems in unit3d is provided by the framework, Laravel, and is used across 1000s of applications without issue. 

If you are experiencing issues with email, it is most likely a configuration error on your end, but if you feel it is part of the program, there would error logs to indicate this and they will need to be provided.

**Comment by HDVinnie** [comment]
Not able to replicate any email issues. Try using `php artisan test:email`. If it works then you may want to try and restart your queue. `php artisan queue:restart && sudo supervisorctl reread && sudo supervisorctl update && sudo supervisorctl reload`

**Comment by l3oncoder** [comment]
Mind telling us what port and encryption your using?
