### ISSUE TITLE
[Bug] optional field not optional

### ISSUE THREAD

**Issue by bitappend** [HDInnovations/UNIT3D-Community-Edition#3334]
### UNIT3D Version

v7.0.0

### PHP & Platform

8.2.12 8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.26.2

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

expect to save a films profile. without imdb id labeled optional.

### Description

will not save page unless you populate the field.
![optionalnot](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/45378636/02132624-754e-4977-b8ff-4e421e98cae5)

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by Roardom** [comment]
Appears to only be an issue on the torrent edit page, the torrent create page is fine. Will write up a fix soon.

**Comment by HDVinnie** [comment]
Fix will be in v7.2.1 release
