### ISSUE TITLE
[Bug] Unhandled null in resources/views/components/torrent/card.blade.php

### ISSUE THREAD

**Issue by clandestine8** [HDInnovations/UNIT3D-Community-Edition#3352]
### UNIT3D Version

7.2.0

### PHP & Platform

8.3 - Ubuntu 22.04

### Laravel verion

10.37.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

No Error

### Description

Attempt to read property "vote_average" on null (View: /var/www/new/resources/views/components/torrent/card.blade.php)

### Stack trace & logs

```shell
Attempt to read property "vote_average" on null (View: /var/www/new/resources/views/components/torrent/card.blade.php)
```

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
Fix will be in v7.2.1 release
