### ISSUE TITLE
[Bug] nerdbot still nerding

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3357]
### UNIT3D Version

v7.2.0

### PHP & Platform

8.3.1 8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.37.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

with nerbot disabled i would not expect it to still send messages to the chat.

### Description

nerdbot has been disabled for weeks but it still randomly* posting in the chatbox.
I'm sure this is a minor problem, and mostly just annoying with all the clutter.
it would almost be better if we had a seperate secondary Bot Room (or perhaps a ticker) so the user chats don't get drowned out.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
config/chat.php you set nerd bot to false here and then ran php artisan set:all_cache?

**Comment by BitPyrate** [comment]
it was disabled in the normal staff dashboard for bots.
and i have cleared cache on the command screen  many times over the last few weeks. i just noticed today that nerd bot had been posting in there for a while, i mentally tune out most of those messages the system gives me there.

if you are instructing me to manually do it in the chat.php and run that command in the cli i can if you want, just let me know. its non critical item and can live with it for now.  just would like to clean it up eventually.

**Comment by BitPyrate** [comment]
interesting. i just checked that file. and it says true in there but it says disabled in the admin interface. ill leave it as is for another few hours if you want any further information from me before i change it.

**Comment by BitPyrate** [comment]
im wonder if the upgrade from 7.0.0 to 7.2 caused it. because its been a while since we touched anything bot related.

**Comment by HDVinnie** [comment]
I have told you what to do....
