### ISSUE TITLE
[Bug] Request page fails on various validations. 

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3363]
### UNIT3D Version

v7.2.0

### PHP & Platform

8.3.1 8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.37.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Trying to file a test request for a film.

### Description

there seems to be 2  problems validating the fields.  

1. default bounty fails, but so does any amount.  the description says at minimum 100, however error says not greater than 2

2. is discussed elsewhere regarding the meta agent field when editing existing torrent information with an update coming in 7.2.1 from what i read. Might be related to that issue.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by BitPyrate** [comment]
![request](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/155480328/ff1c50ee-4807-468b-b5f1-eb663508ec06)

**Comment by BitPyrate** [comment]
![Uploading res2.png…]()

**Comment by HDVinnie** [comment]
> ![res2](https://private-user-images.githubusercontent.com/155480328/295058852-85c168e1-1722-49c3-850a-a03b21a17b9b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTYxMzcsIm5iZiI6MTcwNDc1NTgzNywicGF0aCI6Ii8xNTU0ODAzMjgvMjk1MDU4ODUyLTg1YzE2OGUxLTE3MjItNDljMy04NTBhLWEwM2IyMWExN2I5Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQyMzE3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NDhmZDY4ZTQ4Nzk2ZmFlODRkZmQyNjgwYjM4YjgxYzlkZDM3YWE4OTM5ODI5MTFmMDcxYjFkMzFiNDc4ZDNmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VVLP-RlHr9nV2kvTL0ahSrAy4SuhPfkjg9HsnYS6J4M)

I dont see the issue here.....if its not anime then put a 0 for MAL_ID

**Comment by HDVinnie** [comment]
> ![request](https://private-user-images.githubusercontent.com/155480328/295058598-ff1c50ee-4807-468b-b5f1-eb663508ec06.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTYxMzcsIm5iZiI6MTcwNDc1NTgzNywicGF0aCI6Ii8xNTU0ODAzMjgvMjk1MDU4NTk4LWZmMWM1MGVlLTQ4MDctNDY4Yi1iNWYxLWViNjYzNTA4ZWMwNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOFQyMzE3MTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmRiMTY0OTEwYTQ2NjEzM2RiM2NlNjExMzA5MWE5NTFhMmY2MTFlM2NlNDMyZjdjYWI3NmRlYjRiYmIwNGE2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.in6wu32x6ioxA1qR1K2tDsUD9bOUVEahm9Akd3Ev0fI)

How much BON does this account you tested with have?

**Comment by BitPyrate** [comment]
> I dont see the issue here.....if its not anime then put a 0 for MAL_ID

that is the lesser issue. i do however think it makes sense for that to default

**Comment by BitPyrate** [comment]
> How much BON does this account you tested with have?

close ticket, that was it. not very clear as you don't see the amount of bon on that page or how it works. Suggest available bon be shown near the field.

**Comment by HDVinnie** [comment]
Yes the validation for BON needs to be made more clear. Closing this. Will be addressed in next release.
