### ISSUE TITLE
[Bug] Torrent files downloaded from the site have no creation date

### ISSUE THREAD

**Issue by Slikkster** [HDInnovations/UNIT3D-Community-Edition#3382]
### UNIT3D Version

7.2.0

### PHP & Platform

8.2.14 - Ubuntu 20.04 x64

### Laravel verion

10.37.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Torrent files should have a creation date, probably the date when the torrent was uploaded to the site.

### Description

With no creation date, qbittorrent shows the creation date as 1/1/1970. Other clients are probably similar.

The creation date gets filtered out on upload by the normalizeTorrent() function in the TorrentTools helper, and is never set anywhere else. Setting the date can be done immediately before writing the .torrent file to the disk when a torrent is uploaded:

`$decodedTorrent['creation date'] = Carbon::now()->getTimestamp();`

in app/Http/Controllers/API/TorrentController.php and app/Http/Controllers/TorrentController.php.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
The whole storage system is being refactored and this will be sorted in next release. Leaving open until PR is opened, reviewed and merged.

**Comment by HDVinnie** [comment]
@Slikkster @Roardom can we confirm that clients expect a unix timestamp?

If so we can just add `$result['creation date'] = now()->getTimestamp();` to TorrentTool.php helper after the `$result['created by']`. This would set initial creation date aka uploaded on. Unless the goal is more a torrent file downloaded date in which case it would be put in the DL functions in controller as suggested by OP. Or maybe both?

**Comment by Slikkster** [comment]
> @Slikkster @Roardom can we confirm that clients expect a unix timestamp?
> 
> If so we can just add `$result['creation date'] = now()->getTimestamp();` to TorrentTool.php helper after the `$result['created by']`. This would set initial creation date aka uploaded on. Unless the goal is more a torrent file downloaded date in which case it would be put in the DL functions in controller as suggested by OP. Or maybe both?

I can confirm that a unix timestamp works for qbittorrent. I checked another torrent file with a good timestamp to see what format it used, but didn't do any research beyond that.

I don't think it should be the torrent file download date, the torrent uploaded date makes more sense to me. It looks like putting it in TorrentTool.php would work.

Also, this doesn't fix existing torrent files already saved to disk. While a script or command could be written to alter them, it seemed easier to add a check for the creation date in TorrentDownloadController.php and TorrentZipController.php:
```
if (!array_key_exists('creation date', $dict)) {
    $dict['creation date'] = $torrent->created_at->getTimestamp();
}
```

**Comment by Roardom** [comment]
Indeed looks to be unix timestamp: https://wiki.theory.org/BitTorrentSpecification#Metainfo_File_Structure

Since we scrub this info out upon upload, both the torrent upload timestamp and download timestamp would be wrong to be injected into the torrent. The download timestamp would make more sense since the torrent is edited and saved at that point, but the upload date might be more useful for trying to find the torrent on site if only given that timestamp and no other information (though we already include the link to the torrent in the comment anyway so this point is kind of moot).

Ideally, clients shouldn't be making up their own value if the key doesn't exist since this key isn't mandatory.

**Comment by HDVinnie** [comment]
I think it makes more sense for it to be the initial torrent creation date a.k.a. when the torrent was uploaded to site and altered. Doesn't seem like it's proper for this field but if someone wanted that it could probably be appended to downloaded torrent file name in brackets or part of the comment field. As for existing tour files, we can create a migration that sets all existing torrent files date to the respective torrent created_at date?

**Comment by Roardom** [comment]
We've discussed this internally and concluded this isn't an issue with UNIT3D and it should instead be fixed client-side. The key is optional and the client should say the value is unknown rather than assuming it to be 0
