### ISSUE TITLE
[Bug] similar posts 404.

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3413]
### UNIT3D Version

v7.2.3 & v7.3.0

### PHP & Platform

php8.3.1    8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.40.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

search for title on main page goes to 404. reproducible everytime if i look for some titles like  "mame"
similar issues less reproducible on the torrents page for some sorting methods.

### Description

. i didn't really notice it until recently.
its giving a Error 404: Page Not Found
No Similar Torrents Found
if i search for example mame
https://XXX.net/torrents/similar/1.35275 comes up.

Even though the dropdown preview does show the correct title that is on the system.

interestingly
on the normal torrents page it does resolve to a different address
https://XXX.net/torrents/similar/25.35275

almost feels like a cache or a db entry didn't update properly. I have cleared cache.
this could be something i did but woudl love to hear someone else tell me im retarded and missed something.

ran update which brought me to 7.30 but still present.

### Are you a UNIT3D sponsor?

Yes, with my username

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3413">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3413/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3413/pledge.svg">
</picture>
</a>

**Comment by BitPyrate** [comment]
do you think its a db issue?

**Comment by Roardom** [comment]
It simply means you don't have any approved torrents with that tmdb and that category. Currently the quick search hard codes the category ids to the default movie/tv categories that come with unit3d.

**Comment by BitPyrate** [comment]
i think i follow you a little bit on this.
1 is the category number for general films.
it probably was listed under that at one time until i moved it to a different category..... 25
on the torrents page when i search is does pull up the proper category 25. then begs the question to why the search bar on the main page doesn't know the change.
is that a field that didn't get updated somewhere?

**Comment by BitPyrate** [comment]
it just clicked in my brain.  i was just not reading what you said properly... that field it is in fact hardcoded to category 1...
since category 1 is only a fraction of the db i might be better off disabling it... unless you guys anticipated having it generate that search bar dynamically based on the category_id table.

**Comment by Roardom** [comment]
Yes, the query in https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/app/Http/Livewire/QuickSearchDropdown.php would have to be changed in a future update to include the category id from at least one torrent that belongs to one of the movie/tv generated. That way, the view knows which category id to use. Maybe a `->with('torrents', fn ($query) => $query->limit(1))` would work and then using `$search_result->torrents->first()->category_id` in https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/master/resources/views/livewire/quick-search-dropdown.blade.php. Feel free to test.

**Comment by BitPyrate** [comment]
I'll try your suggestion when i get out of bed. 


In idea i was thinking.  Add  quickfilm  and  quinktv to catagory_id tinyint(1)
psudo code  for search bar:
For each where true quickfilm
Do the search
Else 404

This might make easy  way to add for user customization

**Comment by BitPyrate** [comment]
Small correction i was half awake when i wrote my last message. I meant TABLE categories not catgory_id.
by adding the two true/false columns in there to set where to search.

**Comment by BitPyrate** [comment]
Suggestion for this case since this keeps falling to the bottom of my priority to tinker with it.

If the documentation or labeling was a bit more clear, this feels more like a feature request.
my own solution was in top_nav.blade.php 
comment out line 7  {{-- <livewire:quick-search-dropdown /> --}} 

Solved 99.9% of the my users and my own issues with it.

My recommendation:
1. slap a better label on it call it category 1 and 2 quick search  or some kind of indication on the dashboard/categories control panel, indicating changes here affect the quick search tied to 1 and 2

2. move my this ticket to a feature request (or i can), of having it dynamically generate the categories based on  quick_search tinyint(1) column added to categories TABLE.   you could have it generate what radio buttons appear for the quick-search-dropdown.
this could add  admin customizability to the dashboard/categories panel

3. Close this bug-report.

My gut says this is the most elegant solution.
