### ISSUE TITLE
[Bug] perPage is hardcoded, documentation says otherwise

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3418]
### UNIT3D Version

v7.2.3

### PHP & Platform

8.3.1 8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.40.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

according to documentation:
https://github.com/HDInnovations/UNIT3D-Community-Edition/wiki/Torrent-API-(UNIT3D-v7.0.0)

optional parameter perPage is int default  25 

setting it to anything returns 25 no matter what

### Description

 it's hard coded in TorrentController.php line 70.
 
 
 for my situation i can change that value to  something like 100 ... but i dont think thats elegant. as i don't like touching anything on the server.
  
  
  something like

  public function index(Request $request): TorrentsResource
{
    $perPage = $request->input('perPage', $this->perPage);

    $torrents = Torrent::with(['user:id,username', 'category', 'type', 'resolution', 'region', 'distributor'])
        ->select('*')
        some stuff
        ->paginate($perPage);

        
        
I'm still new to this type of code so i hope im not off my rocker on this, don't want to annoy yall too much with my ignorance. 

I might also be in the wrong spot entirely.

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
Documents is wrong and has been updated. Torrent index is indeed supposed to return just latest 25. If want to use parameters the filter is the right endpoint to use.
