### ISSUE TITLE
[Bug] mass validate user don't work

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#3427]
### UNIT3D Version

7.2.3

### PHP & Platform

8.3.2 ubuntu 20.04.1

### Laravel verion

10.40.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

when I use the function I expect the users to be validated

### Description

they are moved to the user group without validation

### Are you a UNIT3D sponsor?

Yes, with my username

**Comment by HDVinnie** [comment]
You sure your code is not just messed up since you make custom changes? This was fixed here https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3298

**Comment by Gideon75** [comment]
Is not a bug
Solved

**Comment by Gideon75** [comment]
Thanks to Roar
