### ISSUE TITLE
[Bug] Illegal port 1 error with Socks5

### ISSUE THREAD

**Issue by kakkini** [HDInnovations/UNIT3D-Community-Edition#3428]
### UNIT3D Version

7.2.3

### PHP & Platform

8.3.2 ubuntu 20.04.1

### Laravel verion

10.40.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Enable Socks5 on my client (qbittorrent Connection settings-> Proxy server-> "Use proxy for bittorrent purposes" and "Use proxy for peer connections" both enabled) and connect successfully to the tracker

### Description

"Illegal port 1. Port should between 6881-64999"
I think this issue started with https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3329
Other users with different vpn services all report the same issue when using socks5 (Port 1)

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by Roardom** [comment]
99.9% of people that use port 1 are not actually listening on port 1 and if you try connecting to that port it will 99.9% of the time never work. But, they're still reporting port 1 to the tracker. This harms the rest of the swarm who is actually connectable. How would you like it if you tried to download a torrent and all the users were faking their ports so you couldn't connect with them? Of course we want to block such peers to prevent this situation. This is exactly what that PR is intended to block. Include the actual port you're connectable on instead of a fake port and you won't be blocked.

**Comment by Roardom** [comment]
> This issue appears to be happening because libtorrent defaults to announcing port 1 when there's no listen port. There's no listen port because you can't forward natively with SOCKS5. While it makes sense that you'd want to enforce a valid range, is this logic also intended to block users without any listen port? If so, it might be helpful to users to at least update the error message (opportunity to fix the grammar as well).

Listening from system reserved ports requires running the torrent client as root, which is not a good security practice, regardless of if the port is forwarded or not.

**Comment by HDVinnie** [comment]
> > Listening from system reserved ports requires running the torrent client as root, which is not a good security practice, regardless of if the port is forwarded or not.
> 
> 
> 
> I don't think anyone is advocating for that.
> 
> 
> 
> I simply wanted to clarify if this feature is intended to block users _without_ a listening port.  libtorrent defaults to reporting no port as port 1.  It determines there is no port because there is a proxy configured.
> 
> 
> 
> If this is the intended consequence, the error message should probably be updated.  The current messaging is unclear to users that are already configured with a listening port in the required range but are using a proxy which cannot forward that listening port.

Yes we should return a proper message that port 1 was detected for SOCKS5. We will add it.
