### ISSUE TITLE
[Bug] Approve button in Staff Application page doesn't work

### ISSUE THREAD

**Issue by Slikkster** [HDInnovations/UNIT3D-Community-Edition#3436]
### UNIT3D Version

7.2.5

### PHP & Platform

8.3.1 - Ubuntu 20.04 x64

### Laravel verion

10.42.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Clicking the approve button on an application should show a dialog to enter an approval message.

### Description

No dialog is shown. No reaction from the page whatsoever. Application is not approved.

Changing [line 117 in resources/views/Staff/application/show.blade.php](https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/0de9472e1dfbe8c1bc34e0901c44cea2f70acca8/resources/views/Staff/application/show.blade.php#L117C29-L117C48) from `x-data="showDialog"` to `x-bind="showDialog"` fixed it for me.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by HDVinnie** [comment]
will be part oof next release v7.2.6
