### ISSUE TITLE
[Bug] GitHub project "Website" URL is a domain parking page

### ISSUE THREAD

**Issue by rpatterson** [HDInnovations/UNIT3D-Community-Edition#3518]
### UNIT3D Version

N/A

### PHP & Platform

N/A

### Laravel verion

N/A

### Have you done this?

~~[ ] I am willing to share my stack trace and logs~~
- [ ] I can suggest a fix as a Pull Request

### Expectation

When clicking on the link under the project description under "About" at the top of the right side-bar I expect to arrive at official content about the project itself.

### Description

Instead I see a GoDaddy domain parking page that displays large adds and offers to sell the domain.

### Are you a UNIT3D sponsor?

No, don't give priority to this

**Comment by rpatterson** [comment]
For example, I clicked on the link looking around for details on submitting feature requests as opposed to bug reports.

**Comment by HDVinnie** [comment]
Demo is offline
