### ISSUE TITLE
Configurable Bonus Points System

### ISSUE THREAD

**Issue by DXDHD** [HDInnovations/UNIT3D-Community-Edition#360]
Requesting for a more elegant / configurable Bonus Points system.

### Description:

Well, right now users can redeem uploads and perhaps buy invitations exchanging their seedbonus. I was thinking to make this idea even broader. If we have options to add custom rewards in exchange of X number of Seedbonus then it would be an amazing option to have.

**Comment by togwar** [comment]
PLEASE!

**Comment by torman365** [comment]
cannot find if a solution has been found

**Comment by HDVinnie** [comment]
The issue is still open yes? There for it has not been done.
