### ISSUE TITLE
[Request] Donation System

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D-Community-Edition#3635]
A configurable donations system with gateways, packages and more.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3635">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3635/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3635/pledge.svg">
</picture>
</a>

**Comment by BitPyrate** [comment]
Is this a crypto payment processing idea?  We dont need fiat, but want simplified payment method for users to pay crypto.

Or would that be a seperate item for me to put ny bounty on?

**Comment by HDVinnie** [comment]
This is a simplified system where sysops can add the following.

Packages:
Name, Description, Cost, Upload Credit, Invites, Immune, Freeleech, BON, Days

Example: Silver, Show some love, $10, 100GiB, 1, true, true, 10,000 BON, 30 days

Gateways:
Name, Address

Examples: (can use whatever want)
BTC, hksjhjdjkkjhkjdhjksjkhjkahjkashjk
Paypal, mylinkhere
CashApp, $cashtaghere

Then of course donation page and donation tools to approve/reject a donation after sysops confirms it.

Crud example but should get idea across. We want too avoid using any services directly like PayPal or nowpayments

**Comment by Gideon75** [comment]
can I have an approximate release date?

**Comment by HDVinnie** [comment]
> can I have an approximate release date?

Im finishing up the final cleanup and testing now. Will be included in this weeks release this week. Closing this request.

<img width="1440" alt="Screen Shot 2024-05-07 at 10 59 11 AM" src="https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/12850699/8538a4b1-a05f-4595-ba2e-373211f0f9bc">

**Comment by xsixtyfour** [comment]
Incredible work Vinnie! Looking forward to this.
