### ISSUE TITLE
[Request] Transform site links into clickable text representing the link

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3660]
Currently, pasting a profile link into a user note log for instance, leaves just the raw text (not clickable). Having this transformed into a clickable text representing the users name would be nice.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3660">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3660/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3660/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
This is done for Note and TicketNote models. If have others open new request stating all wanted.
