### ISSUE TITLE
[Request] Torrent history grouping by month option

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3663]
Add an option to sort by monthly grouping or not.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3663">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3663/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3663/pledge.svg">
</picture>
</a>

**Comment by Audionut** [comment]
Monthly grouping was removed.

**Comment by Roardom** [comment]
Monthly grouping was removed because when sorting by column, it made no sense.
