### ISSUE TITLE
[Request] Add More Tabs to top_uploaders.blade from Stats Page

### ISSUE THREAD

**Issue by EkoNesLeg** [HDInnovations/UNIT3D-Community-Edition#3676]
Addition of more tabs to `top_uploaders.blade.php` reflecting the user section on the Stats page. The new tabs should display the followining:

1. Top Uploaders (by volume)
2. Top Downloaders (by data)
3. Top Seeders (average seed time)
4. Top Seedtime (current seed size)
5. Most Users Served (top uploaders by snatches)

Each tab should display a list of users who top in the respective category. The list should include the user's name and the corresponding value for the category (e.g., volume of uploads, amount of data downloaded, etc.).

This feature would provide a more prominent view of user activity and contributions to each community. It would also encourage healthy competition among users, promoting more engagement and participation.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3676">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3676/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3676/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Added in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/3742
