### ISSUE TITLE
[Request] Autogroup Torrent Upload Requirement.

### ISSUE THREAD

**Issue by ThyThal** [HDInnovations/UNIT3D-Community-Edition#3692]
Would be nice to also be allowed to set an amount of torrents that should be uploaded for a requirement.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3692">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3692/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3692/pledge.svg">
</picture>
</a>

**Comment by Kha-kis** [comment]
Are you stating that the upload count of a user is associated with the group the user would be a part of?

**Comment by ThyThal** [comment]
> Are you stating that the upload count of a user is associated with the group the user would be a part of?

Yes.

for example the Uploader class would require that the user has uploaded 50 torrents.

**Comment by Kha-kis** [comment]
Awesome, having it as a requirement for any class you would want to configure would be great!
