### ISSUE TITLE
[Bug] font awesome 6.5.1 vs 5.14.4

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3702]
### UNIT3D Version

8.0.1

### PHP & Platform

8.3.2-1+ubuntu22.04.1+deb.sury.org+1

### Laravel verion

10.48.4

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

set an icon to a newer icon from font awesome

### Description

the newer version font awesome fonts do work in some areas but not others
example if you set the group icon to:
fa-solid fa-worm

it shows up in the group manager. but everywhere else it fails to load.

the failure to load does seem to be tied to how it handles the version.

i suspect it's stylisation related 
it may not be practical to fix, but it possibly should be noted.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3702">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3702/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3702/pledge.svg">
</picture>
</a>

**Comment by BitPyrate** [comment]
this is a bad example as "fas fa-worm"  however not all 6.5.1 have a "fas" equivalent

**Comment by HDVinnie** [comment]
You need to use shorthand. fa-solid would be fas. 

fas, far, fat, fal, fad, etc

**Comment by BitPyrate** [comment]
would that also apply to:
"fa-brands fa-phoenix-framework"

**Comment by HDVinnie** [comment]
Im not able to replicate any issues with example provided. If can provide a icon please feel free to reopen.
