### ISSUE TITLE
[Bug] two-factor-auth-form.blade.php line 24

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3714]
### UNIT3D Version

v8.0.1

### PHP & Platform

8.3.1 8.0.35-0ubuntu0.22.04.1

### Laravel verion

10.48.4

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

google authenticator is not required

### Description

Id call this a bug as its worded incorrectly and it does cause problems with some users with aversions to google
I think this line needs a simple rewording similar to line 384 of user.php which is more clear that you can use an alternative to google

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3714">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3714/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3714/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
This is a super easy pull request anyone can tackle.

**Comment by BitPyrate** [comment]
i suppose this is a good noninvasive change for me to do my first pull request on.

**Comment by BitPyrate** [comment]
Pull request #3716 submitted. Regardless if approved im closing  this issue .
