### ISSUE TITLE
[Request] Allow retrieving own user info in API

### ISSUE THREAD

**Issue by SlovakianCanon** [HDInnovations/UNIT3D-Community-Edition#3747]
It would be really useful if one could query their own user information (upload, download, HnR, bonus, etc) using the API. My personal use-case is to be able to retrieve and store uploaded / downloaded amounts every n hours and store it to keep track of my ratio over time across different trackers. But I'm sure other people would find useful applications for it too.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3747">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3747/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3747/pledge.svg">
</picture>
</a>

**Comment by Dekumori** [comment]
This would be great!  Ideally, we could receive {class, download total, notifications, ratio, upload total, username}.

**Comment by HDVinnie** [comment]
@SlovakianCanon this look sufficient for you?

```json
{
"username":"UNIT3D",
"group":"Owner",
"uploaded":"50 GiB",
"downloaded":"1 GiB",
"ratio":"50",
"buffer":"124 GiB",
"seeding":0,
"leeching":0,
"seedbonus":"0.00",
"hit_and_runs":0
}
```

**Comment by HDVinnie** [comment]
Added in v8.x.x for next release

**Comment by nate34k** [comment]
Could downloaded_bytes, uploaded_bytes be added to the API response? It would make parsing easier for certain systems in that you wouldn't need to deal with strings and could use int/number instead, and could also be more accurate (down to the byte).
