### ISSUE TITLE
[Request] Rate limit IP's at the login page

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3777]
Perhaps they can have 2 attempts first, then rate limited afterwards. Ideally the rate limiting would have increased severity with each additional unsuccessful attempt. This should be IP based, without any account association.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3777">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3777/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3777/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
This is already a thing. 

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/1ebcff0a9b8f7da571af02ce00a74bc3b375eda0/app/Providers/FortifyServiceProvider.php#L145-L153
