### ISSUE TITLE
[Bug] Strips releasenames of . . . . and adds spaces

### ISSUE THREAD

**Issue by ghost** [HDInnovations/UNIT3D-Community-Edition#3790]
### UNIT3D Version

8.1.1

### PHP & Platform

8.3 Ubuntu 20

### Laravel verion

Latest in 8.1.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

When uploading it should not remove the . . . in the releasename when putting in torrentfile

### Description

. . . . are removed when uploading torrent 

like this  Release.name.2014.xvid-GRP   

is automated stripped to  Release name 2014 xvid GRP   

Maybe an option to set on/off

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3790">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3790/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3790/pledge.svg">
</picture>
</a>

**Comment by FuNFooKaS** [comment]
it is only for the view on site it does not actually remove form the torrent file itself, if you download the torrent file it still has the dots.

**Comment by Neodkbits** [comment]
Yes but irc announces it without the . . . . . and that bugs pretimes and
such. Where can i change?

man. 29. apr. 2024 14.00 skrev Clicker ***@***.***>:
