### ISSUE TITLE
[Request] Mass email

### ISSUE THREAD

**Issue by timmy171297** [HDInnovations/UNIT3D-Community-Edition#3792]
I've noticed that UNIT3D has many awesome features. I don't know them all, but they enable you to use the site to get what you want without even logging in at all. You can't see what's new or possibly meet new members. Sometimes, I've seen profiles that are actively downloading/seeding, etc. for over 3 weeks... which is fine too of course but i would not say ideal and here i am to place feature REQ and see how that goes on.... for now

I would like to take a moment to remind these members to check in more often by email tool in the staff panel them.

Here, I can remind them of any latest site news, updates on free leech events, and other general matters in particular, or just sask them to come and say hello now and again, add a little spirit!!

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3792">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3792/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3792/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Code is merged into v8.x.x branch and will be in v8.1.3 release
