### ISSUE TITLE
Edit/Delete Polls

### ISSUE THREAD

**Issue by ghost** [HDInnovations/UNIT3D-Community-Edition#380]
Edit and delete buttons for existing polls do nothing

### Issue Type
- [x] Bug Report

### End User Info

-- UNIT3D Version: 1.8.5

-- Laravel Version: 5.6.33

-- PHP Version: 7.2.8

-- Database Driver & Version: MySql Ver 14.14 Distrib 5.7.23

-- Web Server Driver & Version: Nginx 1.15.0

-- OS Driver and Version: Ubuntu 18.04.1 LTS

### Expected Behavior:

Open and editor to modify poll or delete entirely.

### Actual Behavior:

Nothing

### Steps To Reproduce The Problem:

Open "polls" in staff panel and click edit or delete buttons next to any poll

### Possible Fix:

?

**Comment by tuxfrw** [comment]
Hi,

I just found this bug in your system. Is there any forecast to fix this bug? Because it's bad not being able to edit or delete a poll. I´m using version 1.9

**Comment by singularity43** [comment]
This is a known issue.

Polls were never completed.

They will be completed for 2.0.

They are on the agenda.
