### ISSUE TITLE
[Bug] TMDB Background Poster breaking theme.

### ISSUE THREAD

**Issue by Neodkbits** [HDInnovations/UNIT3D-Community-Edition#3804]
### UNIT3D Version

8.1.3

### PHP & Platform

8.3 Ubuntu 20

### Laravel verion

Latest in 8.1.3

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Background poster should be shown correctly in tmdb section only.

### Description

When tmdb info is found, the background poster i breaking the theme and overlaps over navigation and topbanner/header

![proof3](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/74866068/92556de3-6501-4e85-8eef-29a70cda7772)

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3804">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3804/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3804/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
I've never seen this happen before... can you please provide more detailed instructions to reproduce?

**Comment by Neodkbits** [comment]
both my issiues i have fixed now, my fault.

Close
