### ISSUE TITLE
[Request] buff missing from top torrents.... and a possible fix?

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3815]
people are complaining that Freeleech icon stopped working ever since we upgraded to 8.0.1

while tinkering with the code chasing something unrelated i added        app/Http/Livewire/TopTorrents.php
'free',  below the section around line 14.

below
 $torrents = Torrent::query()
            ->select([
            
            
            
            ... and it fixed that feature that people have been asking about.  I did not put in a pull request because I have no idea what else this effects or if it was intentional. I was not even looking to fix this missing feature.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3815">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3815/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3815/pledge.svg">
</picture>
</a>

**Comment by BitPyrate** [comment]
also added
                'refundable',
                'doubleup',
                
                
                holy cow works better than ever
                
                was this an intentional choice to omit speed up the home page?

**Comment by HDVinnie** [comment]
Honestly just think this was missed and overlooked. @Roardom can confirm?

**Comment by Roardom** [comment]
It was missed and overlooked. Because of the selectRaw further down, all the columns have to be manually selected and it looks like a few columns were missed.
