### ISSUE TITLE
Bookmarked

### ISSUE THREAD

**Issue by Gideon75** [HDInnovations/UNIT3D-Community-Edition#3826]
If a torrent is bookmarked, users are notified if a similar one is uploaded

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3826">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3826/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3826/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
"Subscribing" to a movie/tv is probably a better way to phrase it

**Comment by Gideon75** [comment]
Sure!

I agree with you. Is there already a way to do it and I didn't notice?

**Comment by Roardom** [comment]
Nope, currently there's no way to do this right now. But if it's added, I think it should be its own thing and unrelated to bookmarks.

**Comment by HDVinnie** [comment]
There is wishlist which pretty much does same. Butt only notifies on first upload that meets wished title

**Comment by Gideon75** [comment]
IMHO a user who follows many TV series finds it useful to receive notification when a new episode is published

**Comment by Roardom** [comment]
I forgot about wishlist - wishes are in dire need of a refactor. They could be changed to depend on an existing request or torrent and add a subscribe button in the 3-dot menu. 

On one site implementing this functionality, they have the following text:

> The wishlist is a list of films or TV series you would like to see. If you can't find a film/TV in the format you want, or at all, add it to your wishlist. [The site] will send you a message when someone uploads a title on your wishlist.
>
> Simply paste the IMDB URL for the film/TV you want in the box below. You can also add an item from the browse page by pressing the add to wishlist button
>
> Entries shown in green are already on the site. You can remove a wishlisted item with the icon to the left of its name
>
> In case of TV, you will be notified on each first season upload (E01) and season pack uploaded.
