### ISSUE TITLE
Questions on Configuration

### ISSUE THREAD

**Issue by RealMrCactus** [HDInnovations/UNIT3D-Community-Edition#3834]
How do i change SMTP port configured in the installer

Accidentally enabled maintenance mode how do i turn it off

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3834">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3834/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3834/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
@RealMrCactus This issue board is for Bugs and Requests. Not support.  Support is offered to subscribers via Discord. https://github.com/HDInnovations/UNIT3D-Community-Edition?tab=readme-ov-file#--support-unit3d

This is a one off. 

`php artisan up` takes site out of maintenance mode.
Mail settings is in `.env` file.
