### ISSUE TITLE
[Bug] Chat Refresh 

### ISSUE THREAD

**Issue by BitPyrate** [HDInnovations/UNIT3D-Community-Edition#3851]
### UNIT3D Version

v8.1.3

### PHP & Platform

8.3.4 8.0.36-0ubuntu0.22.04.1

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

chat to refresh itself

### Description

recently did an upgrade to the lasted unit3d.
chat stopped posting automatically everyone needs to manually hit refresh.
currently no laravel error log entries. 

should i clear a certain cache?
issue with the messages table?
any easy things i should try?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3851">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3851/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3851/pledge.svg">
</picture>
</a>

**Comment by Slikkster** [comment]
Check your supervisord logs, usually this happens because the chat server isn't able to start due to incorrect permissions on the SSL certificate files.
