### ISSUE TITLE
[Bug]On the login and application screens, there are some "auth." words

### ISSUE THREAD

**Issue by darklandy** [HDInnovations/UNIT3D-Community-Edition#3891]
### UNIT3D Version

8.0.2

### PHP & Platform

8.3.4-Ubuntu 20.04

### Laravel verion

10.48.4

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

There are no superfluous “auth. ”words

### Description

![IMG_6697](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/137611511/49ab0d88-8caa-4029-a4e4-1fc29990a94f)
![IMG_6696](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/137611511/e35cb611-f135-4256-9f5f-e849645f5743)
![IMG_6698](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/137611511/19a09b80-3ccc-4fa2-8764-4402413eb1bc)
On the login and application screens, there are some "auth." words

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3891">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3891/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3891/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Not able to replicate this from new installs.

1) I suggest updating to latest unit3d release.
2) Have you change any configs in relations to lang. Such as `config/app.php` config `locale` or `fallback_locale` keys?
3)Have you made changes to the `config/language.php` config?

**Comment by darklandy** [comment]
Yes, I changed some of the configs in the app.php, I changed to Chinese, and now I'm back to English, okay, the problem is solved！thank you！！
