### ISSUE TITLE
[Bug] Interrupted registration blocks `Username` and `E-mail`

### ISSUE THREAD

**Issue by rpatterson** [HDInnovations/UNIT3D-Community-Edition#3929]
### UNIT3D Version

unknown

### PHP & Platform

unknown

### Laravel verion

unknown

### Have you done this?

- [ ] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

User self-registration should either proceed though to sending the activation email or the user should be able to restart registration with the same `Username` and `E-mail`. Interrupted registration should not "lock" or "block" registering with the same `Username` and `E-mail`.

### Description

If something interrupts the registration process after submitting the first form, there's no way to get back to the second step but the process hasn't gotten to sending the activation email, so it's not possible to resume the process.  Neither is it possible to *restart* the process because the `Username` and `E-mail` are now taken.

This can happen, for example if the site goes down, the browser crashes, or the user accidentally closes the tab after clicking the submit button on the first form.

### Stack trace & logs

```shell
While I'm certainly willing to share my stack trace and logs, there are none to share because I'm just a user. ;-)
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3929">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3929/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3929/pledge.svg">
</picture>
</a>

**Comment by rpatterson** [comment]
For context I've had this happen on two different sites. Once was my own user error, I think I navigated back or loaded another site in the tab. The other time the site went down or was under high load and the response was a `5XX` response but the `Username` and `E-mail` were taken when I tried again.

**Comment by Roardom** [comment]
I assume this isn't relevant for invite only registration codes? I just tested creating an account with a username that already existed and it worked fine after erroring the first time.

**Comment by rpatterson** [comment]
> I assume this isn't relevant for invite only registration codes?

Yes. I'm pretty sure both times I encountered were open registration,  no invite code.

> I just tested creating an account with a username that already existed and it worked fine after erroring the first time.

I thought this was worth writing down given that it happened to me twice. But it doesn't actively bother me and I'm not going to be much help reproducing it. I understand if you need to close this until someone is better able to confirm it.

**Comment by rpatterson** [comment]
> 9. I cleared my cookies to sign out (to re-enact your "worst case scenarios") and revisited the login page
> 10. I entered my username and password, submitted the form, and received the following message: `This account has not been activated and is still in validating group. Please check your email for activation link. If you did not receive the activation code, please click "forgot password" and complete the steps.`

Ah, there's the confusion. From a UX perspective, I was trying to register. Something interrupted my registration. I got no email or anything else indicating I had registered. So I went back to the registration form, not the login form. You obviously knew that's what to do, but there's nothing pointing a user without your specific experience to use the login form as a way to resume registration. It's counter-intuitive and thus bad UX.

The logic that detects an in-progress registration on the login form should be extended to the registration form so that users that who return there also get pointed in the right direction.

**Comment by Roardom** [comment]
Why do you think that registration failed in such a case? Why was your session interrupted? It takes a very rare series of events for this to occur, and I don't see why you'd automatically think the registration failed after pressing submit? Your computer or browser would have to crash immediately after clicking submit and your cookies to be deleted to not see the "send email confirmation" page.

**Comment by Roardom** [comment]
No matter what page you visit on the site after registering, you will be redirected to the "send verification email" page until your cookies are cleared. So you would have had to been in an incognito window or similar.
