### ISSUE TITLE
[Bug] New Chat ID won't take effect immediately

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#3940]
### UNIT3D Version

8.1.3

### PHP & Platform

PHP 8.3.8 - Ubuntu Ubuntu 22.04.4 LTS

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

New chat ID to take effect without any intervention

### Description

If you update your `system_chatroom` in config/chat.php it will immediately take effect for messages sent to the chatbox like "_Bob left a comment in your upload_", but for other things like Forums (_Bob create a new topic_) those changes will take effect only after a `config:clear`.

In case a user is migrating a DB to a brand new installation, that could cause problems like Error 500 because the default value of `system_chatroom` is `'General'` which many times won't match what's on the DB

### Stack trace & logs

```shell
https://gist.github.com/costaht/3646f70adffe0c3e927725ed5a7febae
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3940">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3940/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3940/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Anytime you change a config value you NEED to run `php artisan set:all_cache`
