### ISSUE TITLE
[Bug] Setting Cache error

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#3941]
### UNIT3D Version

8.1.3

### PHP & Platform

PHP 8.3.8 - Ubuntu Ubuntu 22.04.4 LTS

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Run set cache without any issue.

### Description

I got this error during the update from 7.2.5 to 8.1.3. Oddly enough I opened the GitUpdater.php, got all the commands in order, and ran them manually and didn't get any error. So I'm reporting just in case someone else faces the same issue.

### Stack trace & logs

```shell
https://gist.github.com/costaht/09d9f57e46b39c80c023ec5cc5996f2f
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3941">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3941/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3941/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
It's a race condition that happens sometimes. It's fixed in next release.
