### ISSUE TITLE
Upgrading from UNIT3D Community Edition (Nex-Gen Torrent Tracker) v3.0.0 to newer version(s)

### ISSUE THREAD

**Issue by Tzuriel25** [HDInnovations/UNIT3D-Community-Edition#3953]
We are running a very old version with lots of customizations.  Is there any path to upgrading to a newer version?  It seems the schema has changed as well as many many files.  Is there anyway to incorporate some of the new code into the old site without breaking it and losing the customizations?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3953">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3953/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3953/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Tons has changed since then. Like every file. You would need to update to latest and then reimplement custom changes into NEW files.

**Comment by Tzuriel25** [comment]
Is there a path to upgrade to latest from 3.0.0 or do I have to stand up a
brand new vanilla instance and modify that with our customizations?

**Comment by HDVinnie** [comment]
You would have to follow all release notes from v3-v8. Thats a big task because your on such an old version.

If your not comfortable I do offer updating services for a small fee.

**Comment by Tzuriel25** [comment]
Hi Vinnie,

Can you provide a quote for updating our site to the latest tracker?  Aside
from the cost, what else would you need from us?  We don't have a dev site.
