### ISSUE TITLE
[Bug]tracker not work shearing

### ISSUE THREAD

**Issue by leech24** [HDInnovations/UNIT3D-Community-Edition#3963]
### UNIT3D Version

v8.1.3

### PHP & Platform

8.3.8

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

tracker not work shearing

### Description

![0002](https://github.com/HDInnovations/UNIT3D-Community-Edition/assets/44282709/c75033f8-3c66-4630-ab19-f988169492d3)

.env file
TRACKER_KEY=
TRACKER_HOST=127.0.0.1
TRACKER_PORT=6969

it that correct

### Stack trace & logs

```shell
non
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3963">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3963/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3963/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
Can you clarify what "tracker not work shearing" means?

Also, the environment variables you listed are for unit3d-announce (still under development), they aren't used for unit3d's default built-in tracker.

**Comment by leech24** [comment]
transfer data  doesn't work

member after download  and found  tracker work
no data going to member
i make seed
and i try download by qbittorrent or Utorrent

**Comment by Roardom** [comment]
Transferring data works perfectly fine. There is no current issue with the tracker not transferring data. Try a client more suitable for debugging like Tixati. Tixati shows when it tries to connect to peers, and doesn't remove peers if they fail to connect which makes debugging easier. It's most likely the peer causing your issue. Or you're trying to seed to yourself, which is blocked by the tracker as that's considered cheating.

**Comment by jujuforce** [comment]
@Roardom  I have the exact same issue than leech24, troubling ...

**Comment by Roardom** [comment]
> @Roardom I have the exact same issue than leech24, troubling ...

Please detail exactly what you're experiencing:

- Do you receive a list of ips of other peers in the swarm?
- Is your client attempting connections to them?
- Are you using the same account to seed and leech at the same time (which is intentionally blocked)?
- Are you announcing multiple times per announce interval and being rate limited?

I am currently having no issues receiving IPs of other peers in the swarm and cannot replicate this issue.

**Comment by jujuforce** [comment]
I found the issue, it was Cloudflare, so not related to UNIT3D.
Reverting to the original dns nameservers solved everything.

**Comment by HDVinnie** [comment]
When using Cloudflare you need to uncomment.....https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/68ef67e0fd44e430c1130ef7520c4a7479c0ba53/app/Http/Kernel.php#L33

**Comment by jujuforce** [comment]
Wow that's great, thanks for the help, going to try that rn!

**Comment by jujuforce** [comment]
Works great, thanks again!
