### ISSUE TITLE
[Help] 500 Internal server error

### ISSUE THREAD

**Issue by mibj2** [HDInnovations/UNIT3D-Community-Edition#3984]
I should receive a series of torrents based on the type_id.

`https://xxx.xxx/api/torrents/filter?api_token=[token]&types%5B%5D=1&perPage=150`

It works only when perPage is equal to 50 or less; otherwise, the server returns a 500 internal server error

I don't know if it's a bug. Could it depend on the server's performance?

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3984">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3984/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3984/pledge.svg">
</picture>
</a>

**Comment by mibj2** [comment]
nginx folder , 

```access.log    access.log.2.gz  access.log.4.gz  access.log.6.gz  access.log.8.gz  error.log    error.log.2.gz  error.log.4.gz  error.log.6.gz  error.log.8.gz
access.log.1  access.log.3.gz  access.log.5.gz  access.log.7.gz  access.log.9.gz  error.log.1  error.log.3.gz  error.log.5.gz  error.log.7.gz  error.log.9.gz```

I checked access.log and error.log, but there is no trace of my IP
Where  can I check ?

**Comment by Roardom** [comment]
Check the staff dashboard -> Laravel Log

Or they can be found in <project root directory>/storage/logs.

**Comment by mibj2** [comment]
he look like there are not new log but the old one

**Comment by Roardom** [comment]
Generating the error 500 again will create another new stacktrace that can be found in the log. Please send the stack trace here (with any sensitive data redacted).

**Comment by mibj2** [comment]
Thank you, I'll retry later, I'm on the road at the moment. But I have a question: the parameter 'perPage' returns the amount of results per page (default: 25). How do I know how many items are available from the server so I can split the whole list by pages? I can't select a virtual page either

**Comment by Roardom** [comment]
> Thank you, I'll retry later, I'm on the road at the moment. But I have a question: the parameter 'perPage' returns the amount of results per page (default: 25). How do I know how many items are available from the server so I can split the whole list by pages( i mean on terminal)? I can't select a virtual page either

That's intentional. Calculating the hundreds of thousands of matching results was a large bottleneck in the (current) database search. The json response has a `links` key that provides the links to the next/previous pages. The `links.next` key is null if it's there is no next page (i.e. it's the last page). Doing it this way allows much more efficient pagination. The alternative is using something like #3061 but it will only return pagination up to the top 1000 matching results and won't return beyond that.

**Comment by mibj2** [comment]
news :
1 ) The links.next is a nice trick, and I was able to solve my problem without overloading the server 

2) 500 error log: 
```
ERROR  Allowed memory size of 134217728 bytes exhausted (tried to allocate 20480 bytes)

Allowed memory size of 134217728 bytes exhausted (tried to allocate 27267072 bytes) {"userId":1179,"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\FatalError(code: 0): Allowed memory size of 134217728 bytes exhausted (tried to allocate 27267072 bytes) at /var/www/html/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php:406)
[stacktrace]
#0 {main}
"}
```

**Comment by Roardom** [comment]
You will have to tune your server: https://www.php.net/manual/en/ini.core.php#ini.memory-limit

**Comment by mibj2** [comment]
Thank you
