### ISSUE TITLE
[Request] Thread priorities

### ISSUE THREAD

**Issue by Audionut** [HDInnovations/UNIT3D-Community-Edition#3989]
It can be useful, for instance with a forum section rules thread, to always have that thread at the very top of the section. The only current method to accomplish this is with pinning, however this only works with 1 pinned thread, else all pinned threads default to last posted.

Request a priority system to that threads can be specifically delegated a position.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/3989">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3989/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/3989/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
So instead of a checkmark, have a box with a number input? Higher number appears first in the topic listings, and 0 is the default? Or is null / non-existent priority the default? How do other forum softwares handle this?

**Comment by Audionut** [comment]
No idea on other software. I know gazelle has the same "issue".

Probably a value next to or under the 'pin' option, to assign priority. 0 sounds like the best default, with higher numbers having more priority to remain at the top.
