### ISSUE TITLE
[Request] Torrent Checker Role

### ISSUE THREAD

**Issue by EkoNesLeg** [HDInnovations/UNIT3D-Community-Edition#4003]
Add a Torrent Checker (or Editor+) role with limited permissions to assist staff with the mod queue.

Requirements:

- Access to mod queue (`/dashboard/moderation`) only; no access to any other area of `/dashboard`.
- Permissions: approve, postpone, reject, edit torrents.
- No delete permission
- No discount/doubleUp permissions

This will make the Rejection button more meaningful as the button would become an instrument to refer deletions requests to full staff.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4003">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4003/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4003/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
These should really be two separate requests, as you've identified with the subsequent title change.

**Comment by EkoNesLeg** [comment]
Agreed, I only appreciated this after the second change, but didn't want to spam you with notifications. I'll make the necessary changes right away.
