### ISSUE TITLE
[Request] Expose mod_queue_opt_in in upload API

### ISSUE THREAD

**Issue by TGKx** [HDInnovations/UNIT3D-Community-Edition#4012]
## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4012">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4012/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4012/pledge.svg">
</picture>
</a>

**Comment by TGKx** [comment]
Hi, would it be possible to please expose the mod_queue_opt_in to the upload API so that users can self-opt in to mod queue?  That way uploader tools like Upload Assistant can expose the flag via CLI and let users opt in.  Thanks!

**Comment by HDVinnie** [comment]
Will be in v8.2.1 release.
