### ISSUE TITLE
[HELP]  Cover Image parameter

### ISSUE THREAD

**Issue by mibj2** [HDInnovations/UNIT3D-Community-Edition#4016]
What parameter in the API call do I have to use to upload a cover for the e-book category, excluding the description parameter?

I mean the large image like this one : [cover](https://ibb.co/2kF3cVQ)

Thank you

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4016">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4016/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4016/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
The API is documented in the github wiki: https://github.com/HDInnovations/UNIT3D-Community-Edition/wiki/Torrent-API-(UNIT3D-v8.x.x)
