### ISSUE TITLE
[HELP] inmune low ratio

### ISSUE THREAD

**Issue by garrafondorado** [HDInnovations/UNIT3D-Community-Edition#4020]
hello. How to do to a selected group, be inmune to low ratio. Thanks

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4020">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4020/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4020/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
What are you trying to say? What issue are you having?

What is the difference between this issue you reported and #4019 ?

**Comment by Roardom** [comment]
Please also include all the information that you removed from the original issue template

**Comment by garrafondorado** [comment]
sorry for inconvenience i mean how to... ejem moderator usergroup will be inmune to global download ratio thats is 0.8 ... thanks

**Comment by Roardom** [comment]
Moderators have freeleech which allows that. I still don't understand your issue. You omitted all the required fields in the template. Please describe exactly what you did to trigger the issue. Include what happened, and what you expected to happen.
