### ISSUE TITLE
[Request] Cover Image 

### ISSUE THREAD

**Issue by mibj2** [HDInnovations/UNIT3D-Community-Edition#4023]
Dear [Roardom](https://github.com/Roardom)

I had already consulted the documentation before asking. Why did you close the request without letting me respond? In the documentation, I cannot find the appropriate field for submitting a link or an image, or perhaps I am not familiar with certain concepts. If the documentation is that clear, I kindly ask you to suggest the appropriate field for this purpose. How can I use the paid version if I don't understand some aspects first? I don't want to be presumptuous, but I am neither the contributor nor the author of the project. I can only ask you for assistance

Thank you

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4023">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4023/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4023/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
I closed it. You opening duplicate issue/requests. https://github.com/HDInnovations/UNIT3D-Community-Edition/issues/3897

Please search before opening or your account will be blocked.
