### ISSUE TITLE
[Bug]Applications don't appear on dashboard

### ISSUE THREAD

**Issue by kokus81** [HDInnovations/UNIT3D-Community-Edition#4074]
### UNIT3D Version

8.2.0

### PHP & Platform

8.3.10 - Ubuntu 22.04 x64

### Laravel verion

11.19.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

I wanted to test my application system to see if it works, but unfortunately, I didn't get any info on my dashboard.
There are no popups or errors, and the logs are also empty.

### Description

No errors

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4074">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4074/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4074/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Not home atm but my guess would be it broke here.

https://github.com/HDInnovations/UNIT3D-Community-Edition/commit/0cb58d421120d7a33e97ed3bd7cd7ea1305118a2

@Roardom

**Comment by Roardom** [comment]
I found an issue, but it gave a very obvious error on submission, and you reported never receiving an error

**Comment by HDVinnie** [comment]
@kokus81 sharing a image from roar. Just making sure if you try to submit an application you are indeed getting these validation errors. ![image](https://github.com/user-attachments/assets/068e0ec4-bb99-46a0-8b29-aeb153942fc4)

**Comment by kokus81** [comment]
Sorry guys, for late answer but was busy with work and my internet is now bad. I wasn't concentrating on error what was post buy HDVinnie, but about I don't get any application in dashboard. Yes, I get this error.
