### ISSUE TITLE
[Request] Please lower minimum announce interval to 5 minutes or less.  High minimum affects torrent health, may lead to unintentional bans.

### ISSUE THREAD

**Issue by theirongiant82** [HDInnovations/UNIT3D-Community-Edition#4146]
### REQUEST:
Please lower the minimum announce period to somewhere between 60-300 seconds. 

### ISSUE:
If my client announces within a few minutes of the first announce, it's told to back off ("please respect the min interval") and future announcing is blocked for about 15 minutes.  I've never encountered this on *any* other trackers in the last 20 years.  

### IMPACT:

1. Clients who join early in a torrent's life, and then are forced to wait the minimum of 30 minutes, will miss the **"peer swarm"** of people who join a few minutes after them; this will limit their ability contribute to the torrent and increase their ratio, unless they happen to get lucky.  
2. Without enough peers, the torrent performance slows down significantly.  Clients need to ask the tracker frequently at the beginning to ensure they have all the peers they will get, so they can help the swarm.
3. Clients unable to announce in a timely fashion will be unable to report their statistics—a requirement to remain part of some private trackers—which could lead to unintentional bans.

### PROBABLE ROOT CAUSES:
First, there's a **HARD CODED** announce limit in AnnounceController that appears to be a number ... I think it's meant to be 1800 seconds (30 minutes), but it has an underscore.  

Link: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/5125cd33d6c05027f5c2ac16cbeba192dc44ad39/app/Http/Controllers/AnnounceController.php#L46-L48

I've never seen an integer written with an underscore, ever.  Not even for the thousands place.

Second, in the checkMinInterval function.  

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/5125cd33d6c05027f5c2ac16cbeba192dc44ad39/app/Http/Controllers/AnnounceController.php#L450-L494

It only has a caveat for qBittorrent, but not Transmission, which announces at different intervals.  And it penalizes the client for announcing too quickly with no adaptation for early announcements at the beginning of the torrent's life.  Again, this is not a problem on Gazelle-based trackers, libtorrent, or any other tracker.  Literally.  UNIT3D is the first and only platform to complain about too-frequent announces and actively punish users for doing so.

There's a lot of confused users out there who don't know why their tracker is complaining, and they have no way to adjust the announce period client-side, and this is creating support headaches for site admins.  

Please reduce the minimum period.

**Comment by Audionut** [comment]
Unless I'm missing something, which is quite possible, new leechers always get an updated peer table which, includes peers who do not have an updated table, and thus new peers (coss-seeders announces as seeders, and leechers) will be able to connect to these other existing peers, regardless of the existing peers peer table, or the minimum announce interval you complain about.

How does a peer connect to an existing seed if it requires the seed to announce and obtain a new peer list......

**Comment by Roardom** [comment]
> The reason for my request is that UNIT3D's minimum interval is extremely long compared to most other trackers. Transmission, like other clients, already has backoff logic to prevent the user from hammering the announce. The option is greyed out until the app's own internal minimum timer has run down, which is something like 30 seconds, then 5 minutes, then 15 minutes, etc.

Most trackers use 1800 seconds or greater:

https://github.com/WhatCD/Ocelot/blob/972c8d6659a27faa2730b353c2389c2b563a2cd7/config.cpp#L66

https://github.com/OPSnet/Ocelot/blob/d4aaff7bb50315286e9e720be7568a1c235fa6c8/src/config.cpp#L72

https://github.com/Empornium/Radiance/blob/bd1829dcedfa8265fbac3789108491fdca0d5461/src/config.cpp#L87

https://github.com/OlafvdSpek/xbt/blob/d821256d5fdd1c8306e4fb0b93aec229d6623d01/Tracker/config.cpp#L42

https://github.com/anniemaybytes/chihaya/blob/d24100861c0a5e7df9c99edca6eab9ba7fe0b9eb/README.md#L114-L122

> I checked the blame log. It used to be MIN=3600 and MAX=5400 (actually, 3_600 and 5_400), and git blame shows it was last changed in August 2023 (from 7.0.0 to 8.x). Can you help me understand the decision around this?

I would recommend becoming familiar with how to scale mysql to handle several hundred thousand transactions per minute on minimal budget.

> Clients who join early in a torrent's life, and then are forced to wait the minimum of 30 minutes, will miss the "peer swarm" of people who join a few minutes after them

The people joining after them will receive the IPs of the first clients that joined and connect to them.

> Clients unable to announce in a timely fashion will be unable to report their statistics

Stopped events aren't blocked

> I've never seen an integer written with an underscore, ever. Not even for the thousands place.

I don't recall ever using a programming language that doesn't offer underscores for improved readability as thousands separators.

> There's a lot of confused users out there who don't know why their tracker is complaining, and they have no way to adjust the announce period client-side, and this is creating support headaches for site admins.

If these users used clients that respected the minimum interval, then this would never happen.
