### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by bitchcrazy1** [HDInnovations/UNIT3D-Community-Edition#4155]
### UNIT3D Version

v8.2.0

### PHP & Platform

8.3.11 Ubuntu 22.04

### Laravel verion

11.19.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Site name too large for login page, register page and two-factor-challenge page

### Description

Would like the writing to be a bit smaller so all my site name fits instead of running over the box on all three pages

### Stack trace & logs

```shell
N/A
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4155">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4155/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4155/pledge.svg">
</picture>
</a>

**Comment by bitchcrazy1** [comment]
https://i.gyazo.com/30c92cf9e7631dbf7af221a11b5bd185.png - here is a picture of the two-factor-challenge page just so you know what I am talking about

**Comment by FuNFooKaS** [comment]
why is that site pretending to be skipthecommericals when going to privatesilverscreen.xyz????

**Comment by bitchcrazy1** [comment]
nothing is related to YOUR old site, take your domain off my server

**Comment by FuNFooKaS** [comment]
this is not even a bug, just change the font size lmao

**Comment by bitchcrazy1** [comment]
Clicker please do one and leave me alone.. also this is now fixed.

**Comment by FuNFooKaS** [comment]
glad you got it fixed Seeder,good luck keeping this one open
