### ISSUE TITLE
Empornium's Luminance DB import

### ISSUE THREAD

**Issue by goodsushi** [HDInnovations/UNIT3D-Community-Edition#422]
### Issue Type
- [x] Feature Idea

Would it be possible for emporiums Luminance (upgraded gazelle) to be imported into a new install?

https://github.com/Empornium/Luminance

**Comment by HDVinnie** [comment]
Its possible.....well it should be. I will have to look over there DB schema. No ETA though as I got a lot on plate with UNIT3D right now.

**Comment by HDVinnie** [comment]
@goodsushi I should have the initial release done for this weekend.

https://github.com/HDInnovations/luminance-to-unit3d
