### ISSUE TITLE
[Bug] Updating from 8.3.1 to 8.3.2

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#4269]
### UNIT3D Version

8.3.2

### PHP & Platform

8.3.12

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Update without any errors

### Description

When updating an instance from 8.3.1 to 8.3.2 I got the message bellow in a red square:

```
Please report any errors or issues.
[Done]

In ClassLoader.php line 576:
                                                                                                                                                                          
  include(/var/www/html/vendor/composer/../nunomaduro/collision/src/SolutionsRepositories/NullSolutionsRepository.php): Failed to open stream: No such file or directory 
```
The full trace log can be seen in the link below

### Stack trace & logs

```shell
https://gist.github.com/costaht/ebb5eb45ded0d302d667cdb7b96140e7
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4269">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4269/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4269/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
`composer install --prefer-dist --no-dev -o && bun install && bun run build && sudo php artisan migrate && sudo php artisan scout:sync-index-settings && sudo php artisan set:all_cache && sudo systemctl restart php8.3-fpm && sudo php artisan queue:restart && sudo php artisan auto:sync_torrents_to_meilisearch && sudo php artisan auto:sync_people_to_meilisearch sudo php artisan up`
