### ISSUE TITLE
[Bug]"Error in donation system when deleting packages that have already been donated"

### ISSUE THREAD

**Issue by bilboss02** [HDInnovations/UNIT3D-Community-Edition#4277]
### UNIT3D Version

8.3.2

### PHP & Platform

PHP 8.3.12 Database 8.0.39-0ubuntu0.20.04.1

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [X] I can suggest a fix as a Pull Request

### Expectation

display the page correctly
/dashboard/donations

The problem is that packages you donated no longer exist. Basically, you can edit the package, but if you delete a package that someone donated before, you will get an error.

once you removed from the the database donations to packages that don't exist anymore the problem was solved

### Description

STAFF DONATION PAGE DOES NOT LOAD
/dashboard/donations

### Stack trace & logs

```shell
Attempt to read property "cost" on null {"view":{"view":"/var/www/html/resources/views/Staff/donation/index.blade.php","data":[]},"userId":3,"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Attempt to read property \"cost\" on null at /var/www/html/resources/views/Staff/donation/index.blade.php:55)
[stacktrace]
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(123): require('...')
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Filesystem/Filesystem.php(124): Illuminate\\Filesystem\\Filesystem::Illuminate\\Filesystem\\{closure}()
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/PhpEngine.php(58): Illuminate\\Filesystem\\Filesystem->getRequire()
#3 /var/www/html/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(22): Illuminate\\View\\Engines\\PhpEngine->evaluatePath()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(74): Livewire\\Mechanisms\\ExtendBlade\\ExtendedCompilerEngine->evaluatePath()
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4277">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4277/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4277/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
Ideally here if a package has been used in a donation it should fail validation to delete and instead make package active column to false. Or better yet we add soft deletes to packages and cover withTrashed packages on donations index.
