### ISSUE TITLE
[Bug] Leading zeros on IMDB ID are being removed

### ISSUE THREAD

**Issue by costaht** [HDInnovations/UNIT3D-Community-Edition#4280]
### UNIT3D Version

v8.3.2

### PHP & Platform

8.3.12

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

The leading zeros on IMDB IDs should be kept as part of the ID.

### Description

I believe they are being removed when stored as `int unsigned` on the table torrents. They would also be discarted from the RSS feed if they existed 
https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/619c61c2e4c3e7a1d59f7f80f20445e3d1f17476/app/Http/Controllers/RssController.php#L167

So far, I noticed only one place where this has an impact, which is the RSS feed. The URL that should be `https://anon.to?http://www.imdb.com/title/tt0758752`, in the feed is being shown as `https://anon.to?http://www.imdb.com/title/tt758752`. I don't know how but the torrent search is working even if I add the missing zeros.

I noticed that on the Movies and TV tables, `imdb_id` is being stored as `varchar` which keeps the leading zeros.

Here are some other IDs you can test:
https://www.imdb.com/title/tt0758752/
https://www.imdb.com/title/tt0065571/
https://www.imdb.com/title/tt0076239/

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4280">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4280/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4280/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
We store the imdb ids as integers instead of strings for improved performance and efficiency. We then regenerate the link to include the extra zeros. It seems rss was missed in this and it can be fixed similarly to how it's done on the similar page.

**Comment by Roardom** [comment]
> > It can be fixed similarly to how it's done on the similar page
> 
> Sorry, I looked around but I couldn't find or understand where the `imdb_id` is being concatenated with tt0 or tt00.

Here's a good example: https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/437c8dcc880bf7a201d2586be4d17080fa2f11f7/resources/views/torrent/partials/movie_meta.blade.php#L120

**Comment by HDVinnie** [comment]
Will be in next patch release. v8.3.4
Thank you for the contribution.
