### ISSUE TITLE
[Bug] strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D-Community-Edition#4284]
### UNIT3D Version

v8.3.3

### PHP & Platform

8.3.12

### Laravel verion

11.29.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

No deprecations in log.

### Description

resources/views/components/torrent/card.blade.php
```php
        <p class="torrent-card__plot">
            {{ Str::limit(strip_tags($meta?->overview ?: $meta?->summary), 350, '...') }}
        </p>
```

### Stack trace & logs

```shell
strip_tags(): Passing null to parameter #1 ($string) of type string is deprecated in /var/www/html/storage/framework/views/bb35d48a9669f8523afe2b09a6b1d90b.php on line 141
```

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4284">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4284/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4284/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
The following laravel function casts null to an empty string first:

https://laravel.com/docs/11.x/strings#method-fluent-str-strip-tags
