### ISSUE TITLE
[Question] What are Seed Lists/Leech Lists and their limits?

### ISSUE THREAD

**Issue by 9Oc** [HDInnovations/UNIT3D-Community-Edition#4347]
I have some users that seem to be hitting a type of limit for downloading/seeding but I'm not sure what the limits mean or how they are reached.

![HBFOahb 1](https://github.com/user-attachments/assets/a3cce26c-5e61-4a83-bb21-369d9948b93c)
Seen here this user seems to have hit some limit where they cannot download anything even though their total download slot limit in their user profile hasn't been reached.

I tried looking through the UNIT3D code to see if their was documentation on this but couldn't find any comments about what these lists and their respective max numbers mean. If someone could explain to me what these are and how to change them so people don't get blocked from downloading/seeding it would be much appreciated.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4347">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4347/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4347/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
> I tried looking through the UNIT3D code to see if their was documentation on this but couldn't find any comments about what these lists and their respective max numbers mean. If someone could explain to me what these are and how to change them so people don't get blocked from downloading/seeding it would be much appreciated.

It's because this isn't part of UNIT3D, I see you've already made an issue here: https://github.com/Roardom/UNIT3D-Announce/issues/13
