### ISSUE TITLE
[Bug] wireguard

### ISSUE THREAD

**Issue by bitappend** [HDInnovations/UNIT3D-Community-Edition#4352]
### UNIT3D Version

v8.1.3

### PHP & Platform

8.3.8

### Laravel verion

11.5.0

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

torrent transfers through the vpn

### Description

We have had many users over the year complain about Wireguard on their vpns. the normal website works normal. its isolated to torrent transfer issues.
if users switched to normal openvpn protocols it works.
We have chalked it up to wireguard for a while however we have new information.
According to users its also a problem on some of the other unit3d trackers, a notable exception is blu post its relaunch.  
This made me think perhaps there is a setting or configuration issue on our end.
We don't know if its related to us using just ipv4,  or perhaps its still on wireguards end. 
we have only lost a handful of users unwilling to deal with the slower vpn speeds, but think it might be worth checking out if it is also affecting other unit3d trackers.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4352">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4352/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4352/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
> torrent transfers through the vpn

Users have to install their own BitTorrent client which communicates directly with other users' BitTorrent clients to transfer torrents, whether or not through wireguard. UNIT3D is server software and is irrelevant to the transfer of torrents between peers besides providing peers a list of other client ips for their client to connect to. You should look into possible BitTorrent client bugs. Tracker bugs are not within this scope of your issue unless you're receiving a tracker error, which you're not.

> the normal website works normal

If this didn't work, then there'd be a problem.
