### ISSUE TITLE
[Request] Reports shown on torrent page

### ISSUE THREAD

**Issue by tuningman9790** [HDInnovations/UNIT3D-Community-Edition#4353]
The idea is that staff would be able to go on any torrent and see directly if 1 or more reports are open on that specific torrent.

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4353">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4353/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4353/pledge.svg">
</picture>
</a>

**Comment by HDVinnie** [comment]
This is a good one. I'll definitely get it added.
