### ISSUE TITLE
[Question] Is there a way to batch edit multiple torrent descriptions?

### ISSUE THREAD

**Issue by 9Oc** [HDInnovations/UNIT3D-Community-Edition#4378]
Is there a method in the UNIT3D tracker front-end web interface to batch edit many torrent descriptions at once to add the same text/edit the same parameter like torrent category to every torrent you select? I couldn't find this option anywhere poking around myself.

Thanks for your time and appreciate the work ya'll have done on UNIT3D ❤️

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/HDInnovations) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/HDInnovations/UNIT3D-Community-Edition/issues/4378">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4378/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/HDInnovations/UNIT3D-Community-Edition/issues/4378/pledge.svg">
</picture>
</a>

**Comment by Roardom** [comment]
If this is a question and not a feature request, then the answer is No.

**Comment by 9Oc** [comment]
It is a question not request, thank you for info appreciate it.
