### ISSUE TITLE
[Bug] Duplicate results in navbar search

### ISSUE THREAD

**Issue by Slikkster** [HDInnovations/UNIT3D-Community-Edition#4392]
### UNIT3D Version

8.3.4

### PHP & Platform

8.3.14 - Ubuntu 20.04

### Laravel verion

11.28.1

### Have you done this?

- [X] I am willing to share my stack trace and logs
- [ ] I can suggest a fix as a Pull Request

### Expectation

Searching won't produce duplicate results, i.e. the same movie listed twice in the results.
<img width="195" alt="dupesearch" src="https://github.com/user-attachments/assets/a3648f6d-ed7e-4023-bac8-4c3567541587" />

### Description

Only seen it happen with one title so far. Rebuilding the search database didn't fix it; neither did upgrading to the latest release of Meilisearch (1.12.0). Unsure how else to troubleshoot.

**Comment by Roardom** [comment]
This is caused by not using the same imdb for all torrents of that movie. For each distinct imdb you have saved on torrents of that movie, another entry will appear. You can fix it by adding the correct imdb to all torrents of that movie.

**Comment by Slikkster** [comment]
> This is caused by not using the same imdb for all torrents of that movie. For each distinct imdb you have saved on torrents of that movie, another entry will appear. You can fix it by adding the correct imdb to all torrents of that movie.

That was indeed the issue, thank you very much.
