### ISSUE TITLE
Error when running artisan migrate:refresh --seed

### ISSUE THREAD

**Issue by werrpy** [HDInnovations/UNIT3D-Community-Edition#457]
### Issue Type
- [x] Bug Report
- [x] Technical Discussion

### Actual Behavior:

vagrant@homestead:~/projects/UNIT3D$ php artisan migrate:refresh --seed
Rolling back: 2018_11_09_010002_add_immune_to_history_table
Rolled back:  2018_11_09_010002_add_immune_to_history_table
Rolling back: 2018_1_20_070937_create_two_step_auth_table
Rolled back:  2018_1_20_070937_create_two_step_auth_table
Rolling back: 2018_1_10_020753_create_freeleech_tokens_table
Rolled back:  2018_1_10_020753_create_freeleech_tokens_table
Rolling back: 2018_09_29_164525_add_anon_to_request_bounty_table
Rolled back:  2018_09_29_164525_add_anon_to_request_bounty_table
Rolling back: 2018_09_29_163937_add_anon_to_requests_table
Rolled back:  2018_09_29_163937_add_anon_to_requests_table
Rolling back: 2018_09_24_205852_add_internal_to_torrents_table
Rolled back:  2018_09_24_205852_add_internal_to_torrents_table
Rolling back: 2018_09_08_153849_add_soft_deletes_to_user_table
Rolled back:  2018_09_08_153849_add_soft_deletes_to_user_table
Rolling back: 2018_08_19_212319_create_git_updates_table
Rolled back:  2018_08_19_212319_create_git_updates_table
Rolling back: 2018_07_12_114125_add_soft_deletes_to_warnings
Rolled back:  2018_07_12_114125_add_soft_deletes_to_warnings
Rolling back: 2018_06_11_110000_create_topic_subscriptions_table
Rolled back:  2018_06_11_110000_create_topic_subscriptions_table
Rolling back: 2018_05_31_120955_create_images_table
Rolled back:  2018_05_31_120955_create_images_table
Rolling back: 2018_05_31_120936_create_albums_table
Rolled back:  2018_05_31_120936_create_albums_table
Rolling back: 2018_05_22_224911_alter_private_messages_table

   Doctrine\DBAL\Schema\SchemaException  : There is no column with name 'reciever_id' on table 'private_messages'.

  at /home/vagrant/projects/UNIT3D/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/SchemaException.php: 89
  85:      * @return \Doctrine\DBAL\Schema\SchemaException
  86:      */
  87:     public static function columnDoesNotExist($columnName, $table)
  88:     {
  89:         return new self("There is no column with name '$columnName' on table '$table'.", self::COLUMN_DOESNT_EXIST);
  90:     }
  91:
  92:     /**
  93:      * @param string $namespaceName
  94:      *

  Exception trace:

  1   Doctrine\DBAL\Schema\SchemaException::columnDoesNotExist("reciever_id", "private_messages")
      /home/vagrant/projects/UNIT3D/vendor/doctrine/dbal/lib/Doctrine/DBAL/Schema/Table.php : 694

  2   Doctrine\DBAL\Schema\Table::getColumn("reciever_id")
      /home/vagrant/projects/UNIT3D/vendor/laravel/framework/src/Illuminate/Database/Connection.php : 875

  Please use the argument -v to see more details.

### Steps To Reproduce The Problem:
1. Clean clone of UNIT3D

**Comment by HDVinnie** [comment]
If this is a clean clone / install then no need to use refresh. 

Run `php artisan migrate --seed` or `php artisan migrate:fresh --seed`
