### ISSUE TITLE
Cruddy Controllers

### ISSUE THREAD

**Issue by HDVinnie** [HDInnovations/UNIT3D-Community-Edition#472]
### Issue Type
- [x] Enhancement

Essentially, we want to limit our controllers to the 7 resourceful actions. Anything else is an opportunity to create additional controllers.

Example:

Verb | URI | Action | Route Name
-- | -- | -- | --
GET | /photos | index | photos.index
GET | /photos/create | create | photos.create
POST | /photos | store | photos.store
GET | /photos/{photo} | show | photos.show
GET | /photos/{photo}/edit | edit | photos.edit
PUT/PATCH | /photos/{photo} | update | photos.update
DELETE | /photos/{photo} | destroy | photos.destroy

**Comment by singularity43** [comment]
@HDVinnie You should go a step further and require all future controllers with applicable characters to use resources.

**Comment by HDVinnie** [comment]
To be completed for UNIT3D Community Edition v1.9.5
- ref https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/Cruddy-By-Design

**Comment by HDVinnie** [comment]
Closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/releases/tag/v2.0.0
