### ISSUE TITLE
Hide Meta fields on non-meta categories

### ISSUE THREAD

**Issue by xR4E** [HDInnovations/UNIT3D-Community-Edition#473]
Hi,

it would be kinda nice to have the ability to hide meta fields on the upload blade (and edit) on uploads that are not even in a meta category. Maybe it could hide and show as you choose the category - in case something was categorized wrong.

Cheers

**Comment by LayerCorp** [comment]
This will be added @HDVinnie ? Will be great!

**Comment by HDVinnie** [comment]
This is done in `2.x.x` branch. This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.
