### ISSUE TITLE
Add Option to upload torrent image 

### ISSUE THREAD

**Issue by MuzahidGithub** [HDInnovations/UNIT3D-Community-Edition#578]
Feature Idea:

Add option to upload image and screenshot for torrent.

**Comment by LayerCorp** [comment]
this is a must! Not all torrents can get image data from IMDB or other movie/tv info, so manual upload would be great!

**Comment by dedmulehed** [comment]
Absolutely Needed

**Comment by christ84** [comment]
I would also like to. because on /torrents/view/cards or /torrents.php I would sometimes like to put a personal (thumb) image on it. thank you
