### ISSUE TITLE
Save Filters/Search Link

### ISSUE THREAD

**Issue by Havenstd06** [HDInnovations/UNIT3D-Community-Edition#622]
### Issue Type
- [x] Feature Idea

To be able to save the links of a specific search or specific filters or both.

**Comment by waldens** [comment]
Just for reference, [Jpopsuki](https://jpopsuki.eu) also has this issue by default mode, but an option "Disables AJAX behavior on Torrents/Artists Browse Pages. Only check this if you really need to." is provided to resolve this issue.
* uncheck - using AJAX (by default)
* check - using GET

Users on both sides happy.
![screenshot](https://i.loli.net/2019/03/16/5c8cc2e34bae0.png)
