### ISSUE TITLE
Confirmation on some tools from dashboard

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D-Community-Edition#681]
### Issue Type
- [x] Enhancement

### End User Info
-- UNIT3D Version: 1.9.2

There are some tools on the staff_dashboard who should have a confirmation modal window or something, like the "Mass validate users" and "flush ghost peers". First time I clicked on mass validate users to know more about that option, I just mass validate all the users lol (yeah I know the button is for that) but I think that will be much better to click some confirm button or something. I thought that by clicking I would open another window...

Regards!

**Comment by TorrentTop** [comment]
good one
