### ISSUE TITLE
Reported torrents on Torrent Moderation area

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D-Community-Edition#682]
### Issue Type
- [x] Enhancement

### End User Info
-- UNIT3D Version: 1.9.2

Maybe will be good idea to move reported torrents to the torrent moderation area, this way we can get notification (on the topbar) when new reports are in, and also less steps/windows to do all the torrent moderation process.

Regards!

**Comment by sir55** [comment]
it's a very good idea
