### ISSUE TITLE
jquery.wysibb.js need attention

### ISSUE THREAD

**Issue by MatheusRV** [HDInnovations/UNIT3D-Community-Edition#686]
### Issue Type
- [X] Bug Report

This file needs atention, 8 errors.

https://lgtm.com/projects/g/HDInnovations/UNIT3D/alerts/?mode=tree

**Comment by HDVinnie** [comment]
Wysibb is junk to be honest. I did so much work as it is to the JS making is work with latest jQuery and more. Its a dead project. Im going wind up just removing it and replacing with CKEditor or alike. Ill leave this open and close once make the move.
