### ISSUE TITLE
Manual creation of users

### ISSUE THREAD

**Issue by LayerCorp** [HDInnovations/UNIT3D-Community-Edition#690]
### Issue Type
- [x] Feature Idea

### End User Info
-- UNIT3D Version: 1.9.2

This is really a must, if HDvinnie can help us with this can be awesome!

**Comment by dedmulehed** [comment]
I'd really like to use unit3d to replace my aging tracker. Manual creation of users is a deal breaker TBH.

**Comment by loudyin1** [comment]
has this addon been added yet?

**Comment by HDVinnie** [comment]
nope
