### ISSUE TITLE
Report a Bug Form

### ISSUE THREAD

**Issue by DON-IDE** [HDInnovations/UNIT3D-Community-Edition#696]
### Issue Type
- [X] Enhancement

On "Report a Bug" I think the system shouldn't let you fill the name / e-mail. If a user wants he could make a script and fill that with any name and any e-mail and start spamming. Sending bugs again and again. I am not sure if there is a way to find which user did that. So i think it should auto fill like it does now but the user shouldn't be able to change those fields.

### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Expected Behavior:
Being able to send e-mail only with users registered e-mail/username

### Actual Behavior:
You can send E-mail with any e-mail/username you like.

### Steps To Reproduce The Problem:
1. Go to Report a Bug
2. Use any e-mail/username
3. Send a bug report.
4. Repeat with different username/e-mail.

### Possible Fix:
Make it so the user will not be able to edit the fields username/e-mail on that form.

**Comment by HDVinnie** [comment]
The bug report feature is removed in [UNIT3D Community Edition v2.0.0](https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/v2.0.0-LTS). Users can instead use the contact us page. In future a Helpdesk will also be added.
