### ISSUE TITLE
Possible Object Collision in MovieScrapper

### ISSUE THREAD

**Issue by Maliko** [HDInnovations/UNIT3D-Community-Edition#703]
### Issue Type
- [x] Bug Report

`$omdb_movie = $tmdb_movie = new Movie();`

I found a possible Object Collision in the MovieScrapper. When the snipped is used and you changed the Value of $tmdb_movie (change not override), then $omdb_movie is changing too, because both variables has the same reference to the Object. 

So i recommand to use the following snipped:

`$omdb_movie = new Movie();
 $tmdb_movie = new Movie();`

The Same problem exists in line 72.

**Comment by HDVinnie** [comment]
This was fixed but forgot to close.
