### ISSUE TITLE
[BUG] 2 step verification doesnt work

### ISSUE THREAD

**Issue by wht3v34** [HDInnovations/UNIT3D-Community-Edition#736]
Hi. 2 step verification doesnt work on site. M on latest version of site. It wasnt working on 1. 9.2 either. Can u pls check and give a fix for it if possible. Thanks. Getmethos is not supported. Supported methods post.

**Comment by Omniusol** [comment]
@HDVinnie On Blutopia it is broken and the ```Didn't receive verification code?``` button does not work. It returns the error: ```Nof Found```
