### ISSUE TITLE
Two-factor authentication (2FA) with QR code

### ISSUE THREAD

**Issue by Zephilinox** [HDInnovations/UNIT3D-Community-Edition#756]
### Issue Type
- [x] Enhancement

The current two-step authentication uses your email as the second step. A 2FA that uses TOTP (QR code) is better due to requiring a physical device. Any chance of seeing this type of 2FA implemented sometime in the future?

**Comment by diamant-x** [comment]
This might be relevant, already for PHP 
https://github.com/sonata-project/GoogleAuthenticator
