### ISSUE TITLE
User page 404 not found when use chinese user id

### ISSUE THREAD

**Issue by buaapyj** [HDInnovations/UNIT3D-Community-Edition#792]
Issue Type
Bug
End User Info
-- UNIT3D Version: Currently Running UNIT3D Nex-Gen Torrent Tracker v1.9.3(branch master)

-- Laravel Version: Laravel Framework 5.8.16

-- PHP Version:7.3.4-1

-- Database Driver & Version: mysql 5.7

-- Web Server Driver & Version: nginx，nginx version: nginx/1.15.8

-- OS Driver and Version: ubuntu 16.04

Expected Behavior:
It's right to jump the user page when i click user name
Actual Behavior:
![QQ截图20190526211744](https://user-images.githubusercontent.com/25047090/58382358-c29b7e80-7ffb-11e9-9f5a-c9e078f502b1.jpg)
404 not found 

Steps To Reproduce The Problem:
In Home page click person Setting or Forum page click user name（maybe more related page）
But some page it works such as Online people list of Home page and search user of administrator page

**Comment by HDVinnie** [comment]
This is no longer a issue in v2.0.0 +

ID's are no longer used in user urls.
