### ISSUE TITLE
Auth USB U2F

### ISSUE THREAD

**Issue by MyAlien** [HDInnovations/UNIT3D-Community-Edition#851]
- [X] Feature Idea
- [X] Question
- [X] Enhancement
-- UNIT3D Version: 1.9.4

Hello,
Have you thought about Authentication: with USB U2F?
Is it possible to integrate it with UNIT3D?

U2F USB KEY : 🥇 
1) [https://shop.imageinnetwork.fr/gb/security/293-yubikey-5-nfc-5060408461426.html](url)
2) [https://www.google.com/shopping/product/1291463030792706824?q=usb+U2F](url)

Regards

**Comment by HDVinnie** [comment]
It is possible yes.
