### ISSUE TITLE
Language Issue

### ISSUE THREAD

**Issue by theman480** [HDInnovations/UNIT3D-Community-Edition#860]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: #.#.#
 v1.9.4
-- Laravel Version: #.#.#
Ver. 6.0.3
-- PHP Version:
php7.3.9-1+ubuntu18.04.1+deb.sury.org+
-- Database Driver & Version:
5.7.27-0ubuntu0.18.04.1
-- Web Server Driver & Version:

-- OS Driver and Version:
Ubuntu 18.04

### Expected Behavior:

To select languages

### Actual Behavior:
With a fresh install the only language working is English.
I'm receiving this error: Error 404: Page Not Found when selecting the others languages.

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by HDVinnie** [comment]
Able to replicate. Will look into this soon!

**Comment by theman480** [comment]
> Able to replicate. Will look into this soon!

Ok, thanks!
