### ISSUE TITLE
Category can't have both TV and Movie META

### ISSUE THREAD

**Issue by JP9k** [HDInnovations/UNIT3D-Community-Edition#872]
### Issue Type
- [X ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#
1.9.4
-- Laravel Version: #.#.#
6
-- PHP Version:
7
-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Expected Behavior:
To show either TV or Movie META

### Actual Behavior:
TV has to be in category with only TV Meta and vice versa 

### Steps To Reproduce The Problem:
1.Have a category with both METAS
2.Upload a Movie
3.Site can't figure it out, and will probably show wrong Meta, tho TMDB ID is right

**Comment by HDVinnie** [comment]
This is not a bug. A category cannot and should not have both metas. One meta type per category. It is designed this way to know which API to hit. I cannot think of any reason a category should have both. You have a Movie cat and a TV cat......
