### ISSUE TITLE
Bot edit double forward slash on link

### ISSUE THREAD

**Issue by ufo56** [HDInnovations/UNIT3D-Community-Edition#873]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: #.#.#
Latest UNIT3D, installed with autoinstaller

### Steps To Reproduce The Problem:
1.Staff dashboard -> Bots -> Edit [ /staff_dashboard/bots//edit?id=2  (Double forward slash) ]

**Comment by HDVinnie** [comment]
Closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/v2.0.0-LTS

Soon to be released.
