### ISSUE TITLE
unit3d.org is down for demo, docs and manual installation instructions

### ISSUE THREAD

**Issue by StuartRothrock** [HDInnovations/UNIT3D-Community-Edition#874]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [x] Question

Receive either 404 or 503 on site links referenced - may cause potential customers to go with another solution.

Please fix.

**Comment by HDVinnie** [comment]
Demo and Docs are now back online.
