### ISSUE TITLE
HTML Tags Not Contained / Elevated within user-generated body (posts, comments, signature)

### ISSUE THREAD

**Issue by gitStX** [HDInnovations/UNIT3D-Community-Edition#875]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: #.#.#
1.9.4

-- Laravel Version: #.#.#
Unknown

-- PHP Version:
php 7.3.8-1

-- Database Driver & Version:
-- Web Server Driver & Version:
-- OS Driver and Version:
Unknown 

### Expected Behavior:
Prevention of code elevation from user-generated bodies into actual site via input sanitation or other forms of execution prevention. 

### Actual Behavior:
HTML posted by user becomes part of site-run HTML, allowing for malicious activity such as site breaking. 

### Steps To Reproduce The Problem:
1. User makes a body and declares HTML
2. User enters a spoiler tag, inserts a HTML table in tag but doesn't close table
3. All other HTML elements become loaded as part of that table, even outside of user-generated content body.

Alternatively:
4. User can perform malicious activity. I.e. "<script type="text/undefined">" and break page loading after the user-generated body.

### Possible Fix:
Prevent specific HTML tags from being valid input in user-generated bodies alltogether or,
Prevent HTML code from exiting / elevating outside of user-generated body by containment or,
Sanitize HTML code to only accept specific tags or,
completely ignore script and HTML within user-generated bodies or,
a variety of these.

And definitely prevent any script loading.

**Comment by HDVinnie** [comment]
Thanks for the report!

**Comment by gitStX** [comment]
Thanks HDVinnie, for the amazing platform you've build so far. May I ask what solution you've implemented and when it goes 'live'?

On a side note, I have some non-security related bugs (mainly about spam and flood prevention).  I've been in between about making a ticket for them or not... Should I?

**Comment by HDVinnie** [comment]
If its not security related open all the issues you want. If it is it would be better you email me at hdinnnovations@protonmail.com or unit3d@protonmail.com.

As for the fix. Its already live pushed to master making use of the HTML Purifier UNIT3D already had.
