### ISSUE TITLE
Can't connect to server, pushes random binary instead

### ISSUE THREAD

**Issue by gitStX** [HDInnovations/UNIT3D-Community-Edition#878]
### Issue Type
- [x] Bug Report

### End User Info
-- UNIT3D Version: #.#.#
1.9.4

-- Laravel Version: #.#.#
Unknown

-- PHP Version:
7.3.8-1

-- Database Driver & Version:
-- Web Server Driver & Version:
-- OS Driver and Version:
Unknown

### Expected Behavior:
Site data is received and a connection is established

### Actual Behavior:
When connecting with some browsers (Chrome, Safari), they cannot resolve the raw binary in OCTET-STREAM type the server hands them. They download a file containing the data instead of establishing a connection. Firefox does not show this issue and resolves fine.

OCTET-STREAM file data:
~57 bytes 
application/octet-stream
Header:
`00 00 12 04 00 00 00 00 00 00 03 00 00 00 80 00 04 00 01 00 00 00 05 00 FF FF FF 00 00 04 08 00 00 00 00 00 7F FF 00 00 00 00 08 07 00 00 00 00 00 00 00 00 00 00 00 00 01`

### Steps To Reproduce The Problem:
1. Connect to implementation of UNIT3D (DXD)
2. Use Chrome
3. Notice a file is downloaded, but sile isn't loaded.

### Possible Fix:
Unsure. Likely on DXD's end. Ticket made per staff-member request.

**Comment by HDVinnie** [comment]
I cannot replicate such behavior on DEMO. 

https://unit3d.org
username and pass is UNIT3D

You can please test on demo site or a local environment before opening issue as demo is always in sync with UNIT3D master branch. I do not know what ver DXD is using or if its modified.

EDIT:
Im also able to browse DXD using Safari Version 12.1.2 (14607.3.9) just fine.
