### ISSUE TITLE
[Enhancement] Inbox Search

### ISSUE THREAD

**Issue by torman365** [HDInnovations/UNIT3D-Community-Edition#883]
### Issue Type
- [ ] Bug Report
- [ ] Feature Idea
- [x] Enhancement
- [ ] Technical Discussion
- [ ] Question

The mailbox search function only allows searches by "subject". A search by "member" would be helpful as many subjects are the same.
### End User Info
-- UNIT3D Version: #.#.#

-- Laravel Version: #.#.#

-- PHP Version:

-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Steps To Reproduce The Problem:
1.
2.
3.

**Comment by poppabear8883** [comment]
Ideally this can be nice if we utilize VueJS and created a Filtered Search which would enhance the user experience quite a bit. Should be fairly easy to do.
