### ISSUE TITLE
Edit User results in error

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#886]
### Issue Type
- [ x] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [ ] Question

### End User Info
-- UNIT3D Version: #.#.#
v2
-- Laravel Version: #.#.#
on demo site
-- PHP Version:
on demo site
-- Database Driver & Version:

-- Web Server Driver & Version:

-- OS Driver and Version:

### Expected Behavior:
Edit user page

### Actual Behavior:
Symfony\Component\Debug\Exception\FatalThrowableError
Too few arguments to function App\Http\Controllers\Staff\UserController::settings(), 1 passed and exactly 2 expected
https://unit3d.org/dashboard/users/Theron/settings

### Steps To Reproduce The Problem:
1. Click edit user from user list or user profile page
2.
3.

**Comment by HDVinnie** [comment]
Fixed
