### ISSUE TITLE
No 'SD' selection in 'Types'

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#889]
### Issue Type
- [ x] Bug Report
- [ ] Feature Idea
- [ ] Enhancement
- [ ] Technical Discussion
- [x ] Question

### End User Info
-- UNIT3D Version: #.#.#
Demo version
-- Laravel Version: #.#.#
Demo version
-- PHP Version:
Demo version
-- Database Driver & Version:
Demo version
-- Web Server Driver & Version:
Demo version
-- OS Driver and Version:
Demo version

### Expected Behavior:
SD to appear in 'Types' check boxes to allow selection of only SD individual episode torrents (no packs, no HD)

### Actual Behavior:
There is no 'SD' check box displayed. No way of selecting only SD episodes. (There is an 'SD Content' flag, but filtering on this will include SD packs as well as individual episodes.)

### Steps To Reproduce The Problem:
1. Look in 'Filters' or 'RSS', Create RSS feed pages.
2.
3.

### Possible Fix:
Include 'SD' in the 'Types' selection.

**Comment by HDVinnie** [comment]
Closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/v2.0.0-LTS

Soon to be released.

**Comment by innocente205** [comment]
Great stuff! Many thanks.
