### ISSUE TITLE
Wrong country flag

### ISSUE THREAD

**Issue by Setaran** [HDInnovations/UNIT3D-Community-Edition#894]
### Issue Type
- [ * ] Enhancement

### End User Info
-- UNIT3D Version: Latest

### Expected Behavior:
This is Iran's flag:
https://en.wikipedia.org/wiki/Iran#/media/File:Flag_of_Iran.svg

### Actual Behavior:
The fa.png flag currently used is from 40 years ago.

**Comment by HDVinnie** [comment]
Closed in v2.0.0 https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/v2.0.0-LTS

Soon to be released.
