### ISSUE TITLE
Demo Site: Unable to Invite

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#901]
When try to send invite I get:
Error 404: Page Not Found
No query results for model [App\Models\User].

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Send Invite'

**Expected behavior**
I expect the Invite page to open

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.0
- Laravel Version: 6.5.0
- PHP Version:  7.3.11
- Database Driver & Version: 5.7.27
- Web Server Driver & Version: 
- OS Driver and Version: Linux

**Desktop (please complete the following information):**
 - OS: win 7
 - Browser: Chrome
 - Version: 77

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/Bug-Fixes which will be released as `v2.1.1`
