### ISSUE TITLE
Demo Site: Bookmarks do nothing

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#902]
**Describe the bug**
When clicking to bookmark button, nothing happens, looks like it's a dead button
When you go to profile bookmarks nothing is there
**To Reproduce**
1. Go to 'torrents and select any 1 and open it's page'
2. Click on 'BookMark'
3. Go to Profile->Bookmarks

**Expected behavior**
Expected to see some sort of acknowledgement of clicking on bookmark and finding it in profile bookmarks

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.0
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/Bug-Fixes which will be released as `v2.1.1`
