### ISSUE TITLE
Demo Site: Unable to delete a Gallery Album or image within

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#903]
When trying to delete a Album
Error 405: Method Not Allowed!
The GET method is not supported for this route. Supported methods: DELETE.

When trying to delete a Images within an Album
Error 405: Method Not Allowed!
The GET method is not supported for this route. Supported methods: DELETE

**To Reproduce**
1. Go to 'Gallery'
2. Select any Album
3. Click on Delete Album
4. See error above

1. Go to 'Gallery'
2. Select any Album
3. Click on an X on any image within that album
4. See error above

**Expected behavior**
For either I would expect Album or Image to delete

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.0
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/Bug-Fixes which will be released as `v2.1.1`
