### ISSUE TITLE
Demo Site: Notifications, can not mark as read

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#904]
**Describe the bug**
Unable to mark notifications as read
Error 405: Method Not Allowed!
The GET method is not supported for this route. Supported methods: POST.

**To Reproduce**
1. Go to 'Notifications...'
2. Click on 'Mark as read....'
3. See error

**Expected behavior**
I expected it to mark the notification as read

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.0
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/Bug-Fixes which will be released as `v2.1.1`
