### ISSUE TITLE
Demo Site: Notifications - Mark all as Read 405

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#906]
**Describe the bug**
In Notifications, selecting mark all as read gets:
Error 405: Method Not Allowed!
The GET method is not supported for this route. Supported methods: POST.

**To Reproduce**
1. Go to 'Notifications'
2. Click on 'Mark All as Read'
3. See error above

**Expected behavior**
To mark all notifications as read.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.x
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by innocente205** [comment]
Also applies to 'Delete all' (405), and links to notification title targets get a 404 .

**Comment by HDVinnie** [comment]
@innocente205 Old notifications will be invalid links. New ones should not be.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Soon to be released.
