### ISSUE TITLE
Demo Site: Full/File/Database Backups do nothing

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#909]
**Describe the bug**
None of the 3 backup choices work, no acknowledgement of anything happening

**To Reproduce**
1. Go to 'Backup Manager'
2. Click on 'Any of the 3 Choices'

**Expected behavior**
For all 3 of the backups commands to work

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Soon to be released.

**Comment by HD4Free-Gizmo3D** [comment]
Deleting a backup gives error "backup.delete_error_title"
