### ISSUE TITLE
Errors Messages/Issues updating from 1.9.4 to 2.1.1

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#910]
Received the following errors running git_update:

==================================================
Backing Up Files
==================================================

The path 'public/img/emojione' is invalid

cp: cannot stat '/var/www/html/public/img/emojione': No such file or directory

==================================================
Restoring Backups
==================================================

cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
cp: cannot create regular file '/var/www/html/public/fonts/wysibb': No such file or directory
cp: failed to access '/var/www/html/public/img/joypixels/joypixels/_alt': Not a directory
cp: cannot stat '/var/www/html/storage/gitupdate/public/img/emojione/*': No such file or directory
cp: cannot overwrite non-directory '/var/www/html/public/img/joypixels/joypixels' with directory '/var/www/html/storage/gitupdate/public/img/joypixels/joypixels'

Manual Updates:

error: pathspec 'app/Http/Controllers/Staff/TorrentController.php' did not match any file(s) known to git.
error: pathspec 'resources/views/Staff/forum/add.blade.php' did not match any file(s) known to git.
error: pathspec 'resources/views/Staff/torrent/index.blade.php' did not match any file(s) known to git.
error: pathspec 'resources/views/Staff/type/add.blade.php' did not match any file(s) known to git.
error: pathspec 'resources/views/bug/bug.blade.php' did not match any file(s) known to git.
error: pathspec 'resources/views/category/category.blade.php' did not match any file(s) known to git.
error: pathspec 'resources/views/user/members.blade.php' did not match any file(s) known to git.

**Comment by HDVinnie** [comment]
Normal. Certain files were removed and or renamed.

**Comment by innocente205** [comment]
Thanks. I have these directories in the storage section:

storage/gitupdate/public/img
├── emojione
├── flags
├── footer
└── joypixels
    ├── _alt
    └── joypixels
        ├── _alt
        └── joypixels
            └── _alt

three levels of 'joypixels' doesn't look right to me. Could this be a problem related to: "cp: cannot overwrite non-directory '/var/www/html/public/img/joypixels/joypixels' with directory '/var/www/html/storage/gitupdate/public/img/joypixels/joypixels'" in the update procedure?

**Comment by innocente205** [comment]
This seems to have been corrected on the latest update, but has left me with three levels of 'files' directories under public:
`public/files
├── files
│   ├── files
│   │   ├── img
│   │   ├── tmp
│   │   └── torrents
│   ├── img
│   ├── tmp
│   └── torrents
├── img
├── tmp
└── torrents
`

Is it safe to assume the extra 'files' subdirectories can be deleted?

Thanks.

**Comment by innocente205** [comment]
I'll put this here to save opening another issue. Errors from the latest update:

They are all in this form, it seems it is trying to write to a file, not a directory?:
```
cp -Rfp /var/www/html/storage/gitupdate/public/fonts/wysibb/wysibbiconfont-wb.ttf /var/www/html/public/fonts/wysibb
[============================] (Done!)
cp: cannot create regular file '/var/www/html/public/fonts/wysibb': No such file or directory
```




```
Line 6617: cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
	Line 6622: cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
	Line 6627: cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
	Line 6632: cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
	Line 6637: cp: cannot create regular file '/var/www/html/public/fonts/bootstrap': No such file or directory
	Line 6642: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6647: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6652: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6657: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6662: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6667: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6672: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6677: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6682: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6687: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6692: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6697: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6702: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6707: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6712: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6717: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6722: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6727: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6732: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6737: cp: cannot create regular file '/var/www/html/public/fonts/font-awesome': No such file or directory
	Line 6742: cp: cannot create regular file '/var/www/html/public/fonts/wysibb': No such file or directory
	Line 6747: cp: cannot create regular file '/var/www/html/public/fonts/wysibb': No such file or directory
```
