### ISSUE TITLE
[Bug] Poll system buttons

### ISSUE THREAD

**Issue by nikosuk** [HDInnovations/UNIT3D-Community-Edition#911]
**Describe the bug**
Editing and deleting a poll is not possible

**To Reproduce**
1. Go to '/dashboard/polls'
2. Click on 'edit or delete'
3. See error

**Expected behavior**
Poll should be edited or deleted accordingly

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Comment by nikosuk** [comment]
also a 404 error comes when you go to vote on a poll :
https://unit3d.org/poll/vote

**Comment by clandestine8** [comment]
@HDVinnie Should be fixed here when merged
https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/916

**Comment by clandestine8** [comment]
Seems this needs an Edit and Delete controller added to App\Http\Controllers\Staff

**Comment by HDVinnie** [comment]
Poll System is going to be refactored.
