### ISSUE TITLE
error 404 when I vote

### ISSUE THREAD

**Issue by christ84** [HDInnovations/UNIT3D-Community-Edition#912]
I select my choice of vote, and when I click "vote" I have a page 404

**Comment by clandestine8** [comment]
@HDVinnie Should be fixed here when merged
https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/916

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Soon to be released. Thanks @clandestine8
