### ISSUE TITLE
Demo Site: Unable to delete a comment on torrent - 404

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#913]
**Describe the bug**
When I click on the X to delete a comment on a torrent I get:
Error 404: Page Not Found
No query results for model [App\Models\Torrent] {URL-2}

**To Reproduce**
1. Go to 'Torrents-> Pick any torrent'
3. Scroll down to 'any comment' and click the X
4. See error above

**Expected behavior**
The comment should be deleted

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1 (if that's correct on demo site)
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Im not able to replicate this. I can delete comments here just fine.

https://unit3d.org/torrents/95

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Soon to be released.
