### ISSUE TITLE
Demo Site: Unable to sort uploads/downloads by size in Profile, get the working..

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#914]
**Describe the bug**
In profile selecting Uploads or Downloads then select sort by size, get the working on it thingy

**To Reproduce**
1. Go to 'Profile'
2. Click on 'Uploads or Downloads'
3. Select Sort 'Size'

**Expected behavior**
Expecting a qwk sort by size

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1 (if correct)
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HD4Free-Gizmo3D** [comment]
additional info: going to Profile->Active and check box for Seeding or Leeching same results

**Comment by clandestine8** [comment]
@HDVinnie Should be fixed here when merged
https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/916

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Soon to be released. Thanks @clandestine8
