### ISSUE TITLE
404 error when sending test email.

### ISSUE THREAD

**Issue by fcofrank36** [HDInnovations/UNIT3D-Community-Edition#918]
**Describe the bug**
Error 404 al ingresar a  Command Shortcuts ->
 Send Test Email

** To Play **
enter dashboard
Commands option
  Send Test Email.

**Expected behavior**
error 404 

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1+ubuntu18.04.1+deb.sury.org+1
- Database Driver & Version: 5.7.27-0ubuntu0.18.04.1

In demonstration site error 404 is also shown when sending test email.
https://unit3d.org/dashboard/command/test-email
![8b48e7cbef7e2c5b202cfee825f28304 1](https://user-images.githubusercontent.com/43528045/68633066-43c5cf80-04cf-11ea-8bb6-b5b89b91fdea.png)

**Comment by fcofrank36** [comment]
In the previous photo I don't show the complete url of the error.
![dc59795bc67fec02fd3e6b07704b214c 1](https://user-images.githubusercontent.com/43528045/68633146-8a1b2e80-04cf-11ea-87c7-d3fbe9e072aa.png)

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. `v2.2.2`
