### ISSUE TITLE
Upload Guide Link on Publish Page - 404

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#920]
**Describe the bug**
On the publish page the link to Upload Guide gives 404 error

**To Reproduce**
1. Go to 'Publish'
2. Click on 'Link for Upload Guide'
3. See error

**Expected behavior**
The Upload Guide would open

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.2
