### ISSUE TITLE
[Localization] Dashboard Articles

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#921]
**Describe the multilingual issue**
/dashboard/articles is missing the ability to translate the following fields/areas into Danish:

- Header 2 Articles
- Ad and Article burron
- Title label
- Author label
- Date label

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

da ressource file looking like this:
```
<?php

return [
  'articles' => 'Artikler',
  'meta-articles' => 'Artikler og nyheder om tracker og samfundet',
  'published-at' => 'Udgivet den',
  'read-more' => 'Læs mere',
];
```

![image](https://user-images.githubusercontent.com/1777418/68701077-53541f80-0586-11ea-8a20-69e6fcdda72d.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Articles = Artikler
Add A Article = Tilføj en artikel
Title = Titel
Author = Oprettet af
Date = Dato

**Comment by Globbered** [comment]
Hej @JP9k inden du går totalt i oversættelsemode så er det ikke oversættelser jeg mangler, jeg ved godt hvad de skal oversættes til - problemet er at de ikke kan oversættes da der ikke er nogle referencer nogen steder!

**Comment by HDVinnie** [comment]
@Globbered @JP9k I have closed this issue and all the other Danish translations issues due to being stale. If one of you are actually going to make a Pull Request feel free to reopen them and then close with your PR.
