### ISSUE TITLE
[Localization] Dashboard forums

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#922]
**Describe the multilingual issue**
/dashboard/forums is missing the ability to translate the following fields/areas into Danish:

- Header 2 Forums
- Add new category/forum button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
da ressource file attached.

![image](https://user-images.githubusercontent.com/1777418/68701496-35d38580-0587-11ea-95df-e4ec64a30f14.png)

**Possible Fix?**
[forum.zip](https://github.com/HDInnovations/UNIT3D-Community-Edition/files/3837744/forum.zip)

Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Forums = Fora
Add new category/Forum = Tilføj ny kategori/fora
