### ISSUE TITLE
[Localization] Dashboard groups

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#923]
**Describe the multilingual issue**
/dashboard/groups is missing the ability to translate the following fields/areas into Danish:

- breadcrumb
- Header 2s
- Table labels
- Add new group button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68701757-c0b48000-0587-11ea-81b4-8c30eb102725.png)
![image](https://user-images.githubusercontent.com/1777418/68701760-c4480700-0587-11ea-84da-dd9fe16333a1.png)
![image](https://user-images.githubusercontent.com/1777418/68701774-c90cbb00-0587-11ea-9b83-e2e986347011.png)

Also seem to miss a ressource file for translation.

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Bruger Groups = Brugergrupper
Groups = Grupper
Add new group = Tilføj ny gruppe
Position = Position
Level = Niveau
Color = Farve
Icon = Ikon
Effect = Effekt
Internal = Intern
Modo = Moderator
Admin = Administrator
Owner = Ejer
Trusted = Betroet
Immune = Immun
Freeleech = Freeleech
Incognito = Incognito
Upload = Upload
Autogroup = Autogruppe
Owner Permissions = Ejer Rettigheder
