### ISSUE TITLE
[Localization] Dashboard pages

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#924]
**Describe the multilingual issue**
/dashboard/articles is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- H2 heading Pages
- Add new page button
- Title and Date table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
da ressource file seems to be missing?

![image](https://user-images.githubusercontent.com/1777418/68702040-594b0000-0588-11ea-9a34-6197eefda9d6.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Pages = Sider
Add a new page = Tilføj en ny side
Title = Titel
Date = Dato
