### ISSUE TITLE
[Localization] Dashboard polls

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#925]
**Describe the multilingual issue**
/dashboard/polls is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- H2 header
- Add new poll button
Title and Date labels

- H2 Make poll
- CReate poll text
- Warning Title
- Title: label
- Option labels
- Add option button
- Enable duplicate text
- Allow multiple answers text
- Create poll butoon

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
da ressource file looking like this but doesn´t seem to be utilized correctly
```
<?php

return [
  'add-option' => 'Tilføj mulighed',
  'create-poll' => 'Opret afstemning',
  'current' => 'Nuværende afstemning (er)',
  'delete-option' => 'Slet valgmulighed',
  'ip-checking' => 'Denne afstemning har dobbelt stemme kontrol. Du kan kun stemme en gang.',
  'ip-checking-warrning' => 'Kun nødvendig, hvis webstedet er i offentlig tilstand',
  'multiple-choice' => 'Der kan afgives flere valg. Vælg så mange svar som du vil.',
  'option' => 'Mulighed',
  'poll' => 'Afstemning',
  'polls' => 'Afstemninger',
  'results' => 'Afstemningsresultater',
  'title' => 'Titel',
  'total' => 'Samlet antal stemmer nogensinde',
  'vote' => 'Stem',
  'vote-now' => 'Stem nu!',
  'votes' => 'Stemmer',
];
```

![image](https://user-images.githubusercontent.com/1777418/68702444-1fc6c480-0589-11ea-9792-f47f262b1298.png)
![image](https://user-images.githubusercontent.com/1777418/68702454-23f2e200-0589-11ea-9871-b243159d1a7b.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Polls = Afstemning
Manage polls = Håndter afstemninger
Add a new poll = Tilføj en ny afstemning
Title = Titel
Date = Dato
Make poll = Lav afstemning
Create a poll = Lav en afstemning
Option = Mulighed
Add option = Tilføj mulighed
Slet option = Slet mulighed

Enable duplicate IP checking (NEEDED TO PREVENT DUPLICATE VOTING FROM USERS) = Aktiver IP logning (NØDVENDIGT FOR AT FORHINDRE AT BRUGERE STEMMER FLERE GANGE)

Allow multiple answers = Tillad at stemme flere gange

Create Poll = Tilføj afstemning
