### ISSUE TITLE
[Localization] Dashboard RSS

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#926]
**Describe the multilingual issue**
/dashboard/rss is missing the ability to translate the following fields/areas into Danish:

- Header 2s
- Create RSS feed button
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

/dashboard/rss/create is looking alright.

da ressource file looking like this:
```
<?php

return [
  'create' => 'Opret',
  'create-private-feed' => 'Opret privat RSS-feed',
  'create-public-feed' => 'Opret offentligt RSS-feed',
  'delete' => 'Slet',
  'edit' => 'Rediger',
  'edit-private-feed' => 'Rediger Privat RSS Feed',
  'edit-public-feed' => 'Rediger offentligt RSS-feed',
  'feed' => 'Feed',
  'feeds' => 'Feeds',
  'name' => 'Navn',
  'public' => 'Offentlig',
  'private' => 'Privat',
  'rss' => 'RSS',
  'rss-feed' => 'RSS Feed',
  'type' => 'Type',
];
```
![image](https://user-images.githubusercontent.com/1777418/68702722-9499fe80-0589-11ea-98c9-5af80381b8b2.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Create RSS feed = Tilføj RSS Feed
Categories = Kategorier
Genres = Genre
Discounts = Tilbud
Special = Special
Health = Helbred
