### ISSUE TITLE
[Localization] Dashboard moderation

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#927]
**Describe the multilingual issue**
/dashboard/moderation is missing the ability to translate the following fields/areas into Danish:

- Header 2 Postponed Torrents
- Table Labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68703043-20138f80-058a-11ea-9d53-4c9710247b0e.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
@Globbered use the [Localization] prefix in titles please as is in default issue template.

**Comment by JP9k** [comment]
Since = Siden
Category = Kategori
Size = Størrelse
Approve = Godkendt
Postpone = Udsæt
Reject = Afvis

Postponed Torrents = Afviste torrents
