### ISSUE TITLE
[Localization] Dashboard categories

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#928]
**Describe the multilingual issue**
/dashboard/categories is missing the ability to translate the following fields/areas into Danish:

- breadcrumb 
- Header 2 Categories
- Add a category button
- Table labels
- Rediger A category header almost translated
- Icon
- Select an image if text
- Meta text selection

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish.
All resources available translated.

![image](https://user-images.githubusercontent.com/1777418/68703336-bc3d9680-058a-11ea-90e4-34041a527f10.png)

![image](https://user-images.githubusercontent.com/1777418/68703356-c364a480-058a-11ea-84c9-0e10d9776dc7.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Categories = Kategorier
Add a category = Tilføj en kategori
Icon = Ikon
Image = Billede
Movie meta = Film meta
TV meta = TV meta
Game meta = Spil meta
Music meta = Musik meta
No meta = Ingen meta

Rediger torrent category = Rediger torrent kategori
Rediger a category = Rediger en kategori
Select an image if not using a fontawesome icon = Vælg et billede hvis der ikke bliver brugt fontawesome ikon

Movie meta data = Film meta data 
TV meta data  = TV meta data 
Game meta data  = Spil meta data 
Music meta data  = Musik meta data 
No meta data  = Ingen meta data
