### ISSUE TITLE
[Localization] Dashboard types

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#929]
**Describe the multilingual issue**
/dashboard/types is missing the ability to translate the following fields/areas into Danish:

- breadcrumb text
- Ad a torrent type button
- H2 header

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

All resources available translated.

![image](https://user-images.githubusercontent.com/1777418/68703648-57cf0700-058b-11ea-9126-3c6ba5480ea5.png)

![image](https://user-images.githubusercontent.com/1777418/68703661-5ef61500-058b-11ea-8d40-1b97077c3682.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Torrenttyper = Torrent typer
Typer = Typer
Add a torrent type = Tilføj en torrent type
Add torrent type = Tilføj torrent type
