### ISSUE TITLE
[Localization]Dashboard tags

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#930]
**Describe the multilingual issue**
/dashboard/tagsis missing the ability to translate the following fields/areas into Danish:

- Breadcrumb text
- H2 headers
- Add a torrent tag button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

All resources available translated.

![image](https://user-images.githubusercontent.com/1777418/68703891-bdbb8e80-058b-11ea-8b72-960ae4c43e9e.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Torrent tags = Torrent mærke ----- (I would still use "tags" tho)
Tags (Genres) = Mærke (Genre) ----- (Again, i would still use tags) 
Add a torrent tag = Tilføj et torrent mærke ----- (Still tags)
