### ISSUE TITLE
[Localization]Dashboard users

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#931]
**Describe the multilingual issue**
/dashboard/users is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Tab text
- Table labels
- Search button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68704343-771a6400-058c-11ea-869b-ba914341350c.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Bruger search = Bruger søgning
All members = Alle medlemmer
Uploaders = Uploaders
Moderators = Moderatorer
Administrators = Administratorer
Coders = Kodere

Navn and role = Navn og rolle
E-mail = E-mail
Settings = Indstillinger
Search = Søg
Rediger profile = Rediger profil
