### ISSUE TITLE
[Localization]Dashboard gifts

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#932]
**Describe the multilingual issue**
/dashboard/gifts is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb 
- Header 2 
- BON text
- lnvites
- FL Tokens text

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68704657-ef812500-058c-11ea-8c14-e751a1937c6a.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Gifting = Giv gaver
Gifts = Gaver
BON = BON
Invites = Invitationer
FL Tokens = FL Mønter
