### ISSUE TITLE
[Localization]Dashboard mass-actions mass-pm

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#933]
**Describe the multilingual issue**
/dashboard/mass-actions/mass-pm is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2
- Subject
- Message
- Send button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

![image](https://user-images.githubusercontent.com/1777418/68704975-83eb8780-058d-11ea-8f6a-1922aa8e71ec.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Mass PM = Masse PM (Or "Masse Besked")
Subject = Emne
Message = Besked
