### ISSUE TITLE
[Localization]cheaters ghost-leechers

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#934]
**Describe the multilingual issue**
/dashboard/cheaters/ghost-leechers is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2
- Red warning textl
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

![image](https://user-images.githubusercontent.com/1777418/68705149-d462e500-058d-11ea-83c3-30e3ec40bbe4.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Possible leech cheaters = Mulige leech snydere
Possible cheaters = Mulige snydere
Group = Gruppe
Joined = Blev medlem
Last login = Sidste login
