### ISSUE TITLE
[Localization]Dashboard seedboxes

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#935]
**Describe the multilingual issue**
/dashboard/seedboxes is missing the ability to translate the following fields/areas into Danish:

- Created on label

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

![image](https://user-images.githubusercontent.com/1777418/68705311-20158e80-058e-11ea-9222-d9b730d00fb0.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Created on = Tilføjet d.
