### ISSUE TITLE
[Localization]Dashboard bans

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#937]
**Describe the multilingual issue**
/dashboard/articlesis missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Warning text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68705635-b5b11e00-058e-11ea-9ed2-cfa0f15c0a8f.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Bans = Bannede
Judge = Dommer
Ban reason = Grund til ban
Unban reason = Grund til fjernelse af ban
Created = Tilføjet
Removed = Fjernet
