### ISSUE TITLE
[Localization]Dashboard authentications

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#938]
**Describe the multilingual issue**
/dashboard/authentications is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2s
- Black info text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

![image](https://user-images.githubusercontent.com/1777418/68705858-180a1e80-058f-11ea-8f80-829e54fc0cfb.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Authentications log = Godkendelses log
Failed login attempts log = Fejlede login forsøg
Failed logins = Fejlede login forsøg
The are no failed login entries in the database = Der er ikke registreret nogen fejlede logins, i databasen
Username = Brugernavn
IP Address = IP Adresse 
Created on = Tilføjet d.
