### ISSUE TITLE
[Localization]Dashboard invites

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#939]
**Describe the multilingual issue**
/dashboard/invites is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2s
- Black warning text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68706004-5ef81400-058f-11ea-8182-2d0c57a7f40e.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Invites log = Invitations log
Invites sent = Invitationer sendt
The are no invite logs in the database for this user = Der er ikke nogen invitations logs for denne bruger, i databasen
Sender = Afsender
Email = Email
Code = Kode
Created on = Tilføjet d.
Expires on = Udløber d.
Accepted by = Accepteret af
Accepted at = Accepteret d.
