### ISSUE TITLE
[Localization]Dashboard notes

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#940]
**Describe the multilingual issue**
/dashboard/notes is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2
- Black info text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish

![image](https://user-images.githubusercontent.com/1777418/68706380-070ddd00-0590-11ea-9d50-3e5387006824.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Bruger notes = Bruger noter
Bruger notes log = Bruger note log
Notes = Noter
The are no notes in database for this user = Der er ikke nogen noter for denne bruger, i databasen
Staff = Personale
Message = Besked
Created on = Tilføjet d.
