### ISSUE TITLE
[Localization]Dashboard reports

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#941]
**Describe the multilingual issue**
/dashboard/reports is missing the ability to translate the following fields/areas into Danish:

- Breadcrumb
- Header 2
- Red text
- Black information text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68706637-75529f80-0590-11ea-9ffa-3935f67fbeb7.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Reports = Rapporter
Type = Type
Title = Titel
Reported = Rapporteret
Reporter = Reporter
Created = Tilføjet d.
Judge = Dommer
Solved = Afklaret
