### ISSUE TITLE
[Localization]Dashboard warnings

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#942]
**Describe the multilingual issue**
/dashboard/warnings is missing the ability to translate the following fields/areas into Danish:

- Breadcrub
- Header 2s
- Black info text
- Table labels

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68706836-df6b4480-0590-11ea-9508-55c2f9899b78.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Warnings log = Advarsels log
Warnings = Advarelser
Warned by = Advaret af
Torrent = Torrent
Reason = Grund
Created on = Tilføjet d.
Expires on = Udløber d.
Active = Aktiv
