### ISSUE TITLE
[Localization]Achievement popup

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#943]
**Describe the multilingual issue**
Achievement popup is missing the ability to translate the following fields/areas into Danish:

- Text under icon
- All achievement button

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68707299-c44d0480-0591-11ea-9343-b2b0783d3af2.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Well done = Godt gået
All achivcements = Alle resultater
