### ISSUE TITLE
[Localization]/torent filters

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#944]
**Describe the multilingual issue**
/torrents is missing the ability to translate the following fields/areas into Danish 

- Year range

and
/torrents/x is missing the ability to translate the following fields/areas into Danish:

- Define Tip Amount

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68707498-2d347c80-0592-11ea-86be-836be9bc146d.png)

![image](https://user-images.githubusercontent.com/1777418/68709308-bdc08c00-0595-11ea-9213-2407d0de2efc.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Year range = År
Start year = Start år
End year = Slut år
Define a tip amount = Definer et beløb

**Comment by HDVinnie** [comment]
Closed in https://github.com/HDInnovations/UNIT3D-Community-Edition/pull/961#partial-pull-merging. Thanks @Globbered
