### ISSUE TITLE
[Localization]Forum related

### ISSUE THREAD

**Issue by Globbered** [HDInnovations/UNIT3D-Community-Edition#945]
**Describe the multilingual issue**
/forums/x  is missing the ability to translate the following fields/areas into Danish:

- Subscribe button

and
/torrents/x is missing the ability to translate the following fields/areas into Danish:

- Subscribe button
- Tip this poster text

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: php7.3.11-1
- Database Driver & Version: 5.7.27-
- Web Server Driver & Version:
- OS Driver and Version: UB18

**Additional context**
Screenshot added while on Danish
All resources available translated.
![image](https://user-images.githubusercontent.com/1777418/68708856-d54b4500-0594-11ea-93ac-6cad788aa29b.png)

![image](https://user-images.githubusercontent.com/1777418/68708867-d8decc00-0594-11ea-9830-9270835e788b.png)

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by JP9k** [comment]
Subscribe = Abonnere
Tip this poster = Giv en tip
