### ISSUE TITLE
[Enhancement] Impossible to make an article if it has less than 100 characters

### ISSUE THREAD

**Issue by christ84** [HDInnovations/UNIT3D-Community-Edition#946]
put 20 characters minimum would be nice

**Comment by JP9k** [comment]
Just change it it \App\Models\Article.php line 80

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.4
