### ISSUE TITLE
[Enhancement] Option To Disable IMDB & TMDB

### ISSUE THREAD

**Issue by cryptorrents** [HDInnovations/UNIT3D-Community-Edition#947]
**Is your feature request related to a problem? Please describe.**
No

**Describe the enhancement you'd like**

Option to disable the IMDB and TMDB requirement based on category selected (upload page). Example for movies and TV it is fine but for apps it might not be wanted.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by HD4Free-Gizmo3D** [comment]
This is in Staff Dashboard/Torrent Categories, you edit them and select which lookup if any are required

**Comment by cryptorrents** [comment]
Maybe I am missing something. I created a new category which has either nothing selected for meta, or has "No Meta" selected. But when I go to the upload page it still states that:

> TMDB and IMDB is required for all uploads! It is used to grab Posters/Backdrops and ExtraInfo!

Also in the fields:

IMDB ID (Required)
TMDB ID (Required)
IGDB ID (Required)

Am I misunderstanding how this works?

**Comment by HD4Free-Gizmo3D** [comment]
it's just a wording thing, when you upload you only enter the fields required for your category, so if you set a category to no meta then you would leave all the fields with the 0's and carry on with description etc.

**Comment by cryptorrents** [comment]
I think this could be tweeked to be a bit less confusing, maybe something like:

> Some fields may be required in order to upload

To smooth it out a bit when you select your torrent category have the fields refresh and show only "Required" next to a field where certain meta has been selected by the admin. If one field is filled out and it satisfies the meta requirement then other fields change to optional.

Example I select Category TV and IMDB, TMDB, IGDB all say "Required". Once I enter an ID in IMDB the other two fields change to "Optional".

Might be a lot of work for a little thing but would be a nice touch.

**Comment by HDVinnie** [comment]
What would be optimal is some JS to only show the META ID inputs when a specific category from the dropdown is selected that requires them.

**Comment by cryptorrents** [comment]
^^ That would be excellent.

**Comment by HDVinnie** [comment]
This is done in `2.x.x` branch. This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.
