### ISSUE TITLE
[Bug] Latest Forum Post Block and Ampersand symbol

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#948]
**Describe the bug**
When you save a forum post which includes the &  symbol, the Latest Forum Post displays it as \&amp;

**To Reproduce**
1. Go to 'any forum thread and make a post with the & symbol in the first dozen or so characters and save'
2. Click on 'Home Button'
3. Scroll down to 'Latest Forum Post Block'
4. You'll see the \&amp;

**Expected behavior**
to display the & symbol as & 

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.1
- Laravel Version: 6.5.0
- PHP Version: 7.3.11
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.2
