### ISSUE TITLE
[Bug] Some user links in shoutbox go to 404 error

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#950]
**Describe the bug**
Some links to users in the shoutbox are in the form: "/users/user" (these work ok) and some are in the form: "/user.id" where "id" is a number (these return a 404 page)

**To Reproduce**
1. Go to shoutbox in the home page
2. Hover over any user link, check its url
3. Click on a user link like "Mohammad.84". 404 page follows.

**Expected behavior**
User's profile page should be served.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: Current Demo site
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Already Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.2
