### ISSUE TITLE
[Bug] Next page/page number links on user profile page are broken

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#951]
**Describe the bug**
Active, Torrents, Downloads, Uploads, Seeds pages in the user profile will not display past page 1 using the page buttons at the bottom.

**To Reproduce**
1. Go to user profile
2. Click on any list that has more than one page of entries.
3. Scroll down to the bottom, click on page "2"
4. See error, only the revolving dots. no list is rendered.

**Expected behavior**
Page 2 should appear.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1
- Laravel Version: 6.0.4
- PHP Version: 7.3.10-1
- Database Driver & Version: mysql 5.7
- Web Server Driver & Version: nginx
- OS Driver and Version: ubuntu 18.4

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**
The correct url is shown in the status: e.g. users/username/uploads?page/2 and this will open in a new tab correctly after right clicking. However, left clicking on the page number appears to incorrectly append "#page/2" to the existing url, which will not work.

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.2
