### ISSUE TITLE
[Bug] Click on "Follow"/"Unfollow" on user profile page results in Error 405

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#952]
**Describe the bug**
Can not follow or unfollow a user. Error 405: Method Not Allowed!
The GET method is not supported for this route. Supported methods: POST, DELETE.

**To Reproduce**
1. Go to user profile page
2. Click on 'Follow' button

**Expected behavior**
Current user should follow or unfollow the selected user.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: Demo Site
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.4
