### ISSUE TITLE
[Not A Bug]

### ISSUE THREAD

**Issue by christ84** [HDInnovations/UNIT3D-Community-Edition#953]
i's not a bug, but in common.php, line 7 we have:
  'achievement-unlocked'
and too line 163:
  'unlocked-achievement'
same thing or not? thx

- UNIT3D Version: 2.2.1
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Comment by HDVinnie** [comment]
They are not the same. For questions like this do not open a issue and instead use the discord server.
