### ISSUE TITLE
[Bug] Link to guide on Upload page Incorrect

### ISSUE THREAD

**Issue by cryptorrents** [HDInnovations/UNIT3D-Community-Edition#965]
**Describe the bug**

> Having Trouble? See Our Guide HERE

 "HERE" links to https://domain.com/pages/5 and it should link to >> https://domain.com/pages/4

**Comment by HDVinnie** [comment]
I suppose this should be configurable since ppl might have diff IDs

https://github.com/HDInnovations/UNIT3D-Community-Edition/blob/cbc1cb9e53daf9b246177449cd43afd80de4527e/config/other.php#L180-L194

**Comment by cryptorrents** [comment]
That would be great!

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.4
