### ISSUE TITLE
Ability To Upload Images Through Editor

### ISSUE THREAD

**Issue by cryptorrents** [HDInnovations/UNIT3D-Community-Edition#966]
**Is your feature request related to a problem? Please describe.**
No

**Describe the enhancement you'd like**
Ability to upload images in the editor for uploads, pages, forums, etc. Best to keep everything internal and not linking out to images.

**Describe alternatives you've considered**
NA

**Additional context**
NA

**Comment by shareisland** [comment]
it's nice for music and program without images
