### ISSUE TITLE
[Bug] Tags in table tag_torrent are never cleared

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#967]
**Describe the bug**
Genre tags scraped from IMDB etc. are added to table tag_torrent on every change of IMDB number.

**To Reproduce**
1. Go to a torrent
2. Click on Edit
3. Scroll down to IMDB, change number to another program with different genres
4. See error, all genres from both programs are displayed.

**Expected behavior**
Existing genres should be removed, only new genres should be added

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.1.1
- Laravel Version: 6.0.4
- PHP Version: 7.3
- Database Driver & Version: mysql 5.7
- Web Server Driver & Version: nginx
- OS Driver and Version: ubuntu 18.04

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.5
