### ISSUE TITLE
[Enhancement] Display Chat Messages instantly

### ISSUE THREAD

**Issue by GitPubHub** [HDInnovations/UNIT3D-Community-Edition#970]
Currently, chat messages are only displayed after a reload of the page.

[https://gyazo.com/75a5f8a2f2da883412b83c211ed1a279](https://gyazo.com/75a5f8a2f2da883412b83c211ed1a279)

If this only happens for me just convert it into a bug report

**Comment by GitPubHub** [comment]
Ok now I see on the demo page the message will be displayed immediately.
What do I need to do to fix this issue on my server?

**Comment by HDVinnie** [comment]
Open a new issue if that's the case.

**Comment by GitPubHub** [comment]
`ufw allow ssh && ufw enable && supervisorctl reread && supervisorctl update && supervisorctl reload` unfortunately did not solve the problem for me.

I have opened a new report: #990
