### ISSUE TITLE
[Enhancement] Sidebar Navigation stay open

### ISSUE THREAD

**Issue by GitPubHub** [HDInnovations/UNIT3D-Community-Edition#971]
Currently the sidebar navigation closes after each click / refresh.To improve the user experience, the sidebar navigation should remain open if the user also wants to see the text.

[https://gyazo.com/283e74b14967f571c40985f3d866708e](https://gyazo.com/283e74b14967f571c40985f3d866708e)

**Comment by HDVinnie** [comment]
You can already do this.

[![Image from Gyazo](https://i.gyazo.com/ba046450165e666c7d3c05b067a757d3.gif)](https://gyazo.com/ba046450165e666c7d3c05b067a757d3)

**Comment by GitPubHub** [comment]
That's a beginning :D
However, I mean that a user can change something like that with a single click on the three dashes.
Overall, the general user settings are a bit too hidden. As an experienced user you have to click 5 times alone to set this.

In the UI area it is one of the most important things that the user has to make as few clicks as possible.
The design itself is not bad don't get me wrong, but there is still a lot of room for improvement on this matter.
