### ISSUE TITLE
[Enhancement] Staff Dashboard Navigation on every Staff page

### ISSUE THREAD

**Issue by GitPubHub** [HDInnovations/UNIT3D-Community-Edition#972]
At the moment you have to navigate back to the Staff Dashboard to see the full overview of the Staff Navigation. I propose that this should be displayed on every staff page without having to click multiple times.

[https://gyazo.com/b0ea258c4986404b86e55aa8fa514a1a](https://gyazo.com/b0ea258c4986404b86e55aa8fa514a1a)

**Comment by HVRVKVT** [comment]
makes sense
