### ISSUE TITLE
[Bug] Links under author avatar in forum pages are in the old format

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#973]
**Describe the bug**
In forum pages, if you click on the Topics or Posts links in the member's box in a forum post, you get a 404 Not Found error.

**To Reproduce**
1. Go to a forum page
2. Click on Topics under the member avatar
3. 
4. See error 404

**Expected behavior**
Should go to the users 'Topics' page.

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.3
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**
Links are in the old users format /users/topics?id=xxxx
should be /users/username/topics
Similarly with posts.

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.4

**Comment by innocente205** [comment]
Thank you!
