### ISSUE TITLE
[Bug] - Notification: User Has followed you

### ISSUE THREAD

**Issue by HD4Free-Gizmo3D** [HDInnovations/UNIT3D-Community-Edition#995]
**Describe the bug**
When you get a notification that a user has followed you, you click on the link you get:
Error 404: Page Not Found
No query results for model [App\Models\User].

**To Reproduce**
1. Go to 'Notificatons'
2. Click on 'the link for So & So has followed you!'
3. See error

**Expected behavior**
It should take you to that users profile

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: 2.2.4
- Laravel Version: 6.5
- PHP Version: 7.3.11
- Database Driver & Version: 5.7.28
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Same as some others, it's trying to go to userid not username

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. v2.2.5
