### ISSUE TITLE
[Bug] Disabling Bots

### ISSUE THREAD

**Issue by innocente205** [HDInnovations/UNIT3D-Community-Edition#998]
**Describe the bug**
All the disable buttons on the Bots screen result in 404 errors.

**To Reproduce**
1. Go to Staff Dashboard
2. Click on Bots
3. Click on 'Disable'

**Expected behavior**
Bot should be disabled

**Screenshots**

**UNIT3D (please complete the following information):**
- UNIT3D Version: Demo site v2.2.4
- Laravel Version:
- PHP Version:
- Database Driver & Version:
- Web Server Driver & Version:
- OS Driver and Version:

**Desktop (please complete the following information):**
 - OS:
 - Browser:
 - Version:

**Additional context**

**Possible Fix?**
Have a idea on how to fix? Write it here.

**Comment by HDVinnie** [comment]
This will be released in the next release. `UNIT3D Community Edition v2.3.0` which is a week out max.

**Comment by HDVinnie** [comment]
Fixed in https://github.com/HDInnovations/UNIT3D-Community-Edition/tree/2.x.x
Patch soon to be released. `v2.3.0`
